import{createHash}from"node:crypto";import{cpSync,mkdtempSync,readFileSync,rmSync,writeFileSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";import{fileURLToPath}from"node:url";import{afterEach,describe,expect,it}from"vitest";import{runCF045}from"../src/product/cf045-generated-health-fault-campaign.js";import{composedRecoveryDigest}from"../src/product/composed-runtime-recovery.js";import{createCF047FixtureLifecycleAuthority}from"./support/cf047-lifecycle-authority.js";
const v=fileURLToPath(new URL("../validation/cf-045-generated-health-fault-v3/",import.meta.url)),cf044=fileURLToPath(new URL("../validation/cf-044-registry-snapshot-mixed-family-v3/",import.meta.url)),cf033=fileURLToPath(new URL("../validation/cf-033-mixed-family-goal-v1/",import.meta.url)),cf031=fileURLToPath(new URL("../validation/cf-031-family-routing-benchmark-v1/",import.meta.url)),cf032=fileURLToPath(new URL("../validation/cf-032-runtime-family-conformance-v1/",import.meta.url)),roots:string[]=[];afterEach(()=>{for(const x of roots.splice(0))rmSync(x,{recursive:true,force:true})});async function run(directory=v){const root=mkdtempSync(join(tmpdir(),"cf045-"));roots.push(root);return runCF045({directory,workRoot:root,cf044Directory:cf044,cf033Directory:cf033,cf031Directory:cf031,cf032Directory:cf032,lifecycleAuthority:createCF047FixtureLifecycleAuthority()})}
describe("CF-045 generated post-verification health fault campaign",()=>{
 it("covers every fault at every meaningful graph boundary without replay",async()=>{const r=await run();expect(r).toMatchObject({status:"passed",coverage:{faults:6,boundaries:3,transitions:18,restarts:18,priorActionsReplayed:0,secondParentResumptions:0},originalSealsModified:0,modelCalls:0,paidSpendUsd:0});expect(new Set(r.transitions.map(x=>`${x.fault}:${x.boundary}`)).size).toBe(18);expect(r.transitions.every(x=>x.priorActionsReplayed===0)).toBe(true)});
 it("separates safe no-op, compatible replacement and precise handoff",async()=>{const r=await run();expect(r.coverage).toMatchObject({safeNoOps:3,replacements:5,handoffs:10,incompatibleReplacementsBlocked:20,parentResumptions:8});expect(r.transitions.filter(x=>x.disposition==="replacement").every(x=>x.lineage&&x.oldSnapshotBlocked&&x.newAggregateExternalProof)).toBe(true);expect(r.transitions.filter(x=>x.disposition==="precise-handoff").every(x=>x.parentResumptions===0&&!x.newAggregateExternalProof)).toBe(true)});
 it("rejects substituted evidence atomically and blocks every real health fault",async()=>{const r=await run();expect(r.transitions.filter(x=>x.fault==="evidence-source-change").every(x=>x.disposition==="safe-no-op"&&!x.oldSnapshotBlocked)).toBe(true);expect(r.transitions.filter(x=>x.fault!=="evidence-source-change").every(x=>x.oldSnapshotBlocked)).toBe(true)});
 it("preserves verified prefixes and resumes only the remaining graph",async()=>{const r=await run();for(const x of r.transitions)if(x.disposition!=="precise-handoff")expect(x.writesAfterRestart).toBe(3-x.verifiedBefore)});
 it("is deterministic",async()=>{expect((await run()).receiptDigest).toBe((await run()).receiptDigest)})
 it("rejects a cryptographically resealed but future-dated corpus",async()=>{const root=mkdtempSync(join(tmpdir(),"cf045-future-"));roots.push(root);cpSync(v,root,{recursive:true});const p=join(root,"corpus.json"),s=join(root,"seal.json"),corpus=JSON.parse(readFileSync(p,"utf8")),seal=JSON.parse(readFileSync(s,"utf8"));corpus.frozenAt="2999-01-01T00:00:00.000Z";writeFileSync(p,JSON.stringify(corpus));seal.corpusSha256=createHash("sha256").update(readFileSync(p)).digest("hex");const{sealDigest:_old,...unsigned}=seal;seal.sealDigest=composedRecoveryDigest(unsigned);writeFileSync(s,JSON.stringify(seal));await expect(run(root)).rejects.toThrow(/future-dated/)})
});
