import { createHash, generateKeyPairSync, X509Certificate, type KeyObject } from "node:crypto";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync, spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { DatabaseSync } from "node:sqlite";
import { afterEach, describe, expect, it } from "vitest";
import { createLocalFixtureBindingQualification } from "../src/product/customer-local-binding-qualification.js";
import { CustomerLocalHttpAuthorityTrustStore, signWorkspaceHttpAuthorityActivationRevocation } from "../src/product/customer-local-http-authority-trust.js";
import { createCustomerLocalHttpNotStartedObserverSigner, createTestCustomerLocalHttpWriteAuthorityFromTrustStore, customerLocalHttpAuthorityTrustContractDigest, signWorkspaceHttpAuthorityActivation, type CustomerLocalHttpWriteAuthorityContractInput, type CustomerLocalHttpWriteAuthorityIssuer, type CustomerLocalHttpWriteAuthorityVerifier } from "../src/product/customer-local-http-write-authority.js";
import { CustomerLocalTrustStore, type CustomerLocalTrustConfiguration } from "../src/product/customer-local-trust-backup.js";
import { createAuthorityEnforcedCustomerLocalPinnedHttpsTransport, createCustomerLocalPinnedHttpsTransport, pinnedHttpsAuthorityBoundaryDigest, type CustomerLocalPinnedHttpsTransportConfig } from "../src/product/customer-local-pinned-https-transport.js";
import { CompiledHttpActionDispatchUncertainError, compileReviewedHttpBindings, httpBindingCompilerDigest, type CompiledHttpActionInput, type CompiledHttpObservationInput, type CompiledHttpRequest, type CustomerLocalCredentialResolver, type CustomerLocalHttpTransport } from "../src/product/http-binding-compiler.js";
import { JsonFileGenericAcceptanceCampaignStore, runGenericAcceptanceCampaign, type GenericAcceptanceAttemptContext, type GenericAcceptanceBinding } from "../src/product/generic-acceptance-executor.js";
import { REQUIRED_PILOT_ADAPTER_CASES, type PilotAdapterAcceptanceCase, type PilotAdapterAcceptanceResult } from "../src/product/pilot-adapter.js";
import { Cf053ContentAddressedCandidateRegistry, deriveCf053ProviderNeutralContract } from "../src/product/local-declarative-exact-record-core.js";
import { compileCf058AuthorityEnforcedReviewedHttpBindings, joinCf058OpaqueCausalHttpBridge, type Cf058CausalBridgeHandle } from "../src/product/cf058-opaque-causal-http-bridge.js";
import { cf058ColdChainSplitReviewedSource } from "./fixtures/cf058-cold-chain-runtime-source.js";
import { createCf058ColdChainProductionDerivationFixture } from "./fixtures/cf058-cold-chain-upstream.js";
import { CF058_COLD_CHAIN_ACTION_CREDENTIAL_ALIAS, CF058_COLD_CHAIN_ACTION_DRIVER, CF058_COLD_CHAIN_ACTION_OPERATION, CF058_COLD_CHAIN_ACTION_PATH, CF058_COLD_CHAIN_OBSERVER_CREDENTIAL_ALIAS, CF058_COLD_CHAIN_OBSERVER_DRIVER, CF058_COLD_CHAIN_OBSERVER_OPERATION, CF058_COLD_CHAIN_OBSERVER_PATH, CF058_COLD_CHAIN_OBSERVER_SOURCE, CF058_COLD_CHAIN_TARGET_ALIAS } from "./fixtures/cf058-cold-chain-reviewed-source.js";

const roots: string[] = [], children: ChildProcessWithoutNullStreams[] = [], closers: Array<() => void> = [];
afterEach(async () => { for (const close of closers.splice(0).reverse()) { try { close(); } catch {} } for (const child of children.splice(0)) if (child.exitCode === null && child.signalCode === null) { child.kill("SIGTERM"); await new Promise<void>((resolve) => child.once("exit", () => resolve())); } for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); });

const canonical = (value: unknown): string => Array.isArray(value) ? `[${value.map(canonical).join(",")}]` : value && typeof value === "object" ? `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(",")}}` : JSON.stringify(value);
const digest = (value: unknown): string => createHash("sha256").update(canonical(value)).digest("hex");
type Directive = { directive_ref: string; lot_code: string; hold_quantity?: number; reason_confirmed?: boolean; status: "quarantined" | "partial"; version: number; updated_at: string };
type World = { schemaVersion: "1.0"; sequence: number; writes: number; precommitDrops: number; postcommitDrops: number; directives: Record<string, Directive>; faultByDirective: Record<string, "precommit-drop" | "postcommit-drop"> };
const emptyWorld = (): World => ({ schemaVersion: "1.0", sequence: 0, writes: 0, precommitDrops: 0, postcommitDrops: 0, directives: {}, faultByDirective: {} });
function writeWorld(path: string, world: World): void { writeFileSync(path, `${JSON.stringify({ body: world, digest: digest(world) })}\n`, { mode: 0o600 }); }
function readWorld(path: string): World { const envelope = JSON.parse(readFileSync(path, "utf8")) as { body: World; digest: string }; expect(envelope.digest).toBe(digest(envelope.body)); return envelope.body; }

function certificate(root: string, name: string) { const keyPath = join(root, `${name}-key.pem`), certificatePath = join(root, `${name}-cert.pem`), config = join(root, `${name}-openssl.cnf`); writeFileSync(config, "[req]\ndistinguished_name=dn\nx509_extensions=v3\nprompt=no\n[dn]\nCN=localhost\n[v3]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n"); execFileSync("/usr/bin/openssl", ["req", "-x509", "-newkey", "rsa:2048", "-nodes", "-days", "1", "-keyout", keyPath, "-out", certificatePath, "-config", config], { stdio: "ignore" }); const pem = readFileSync(certificatePath, "utf8"), sha256 = createHash("sha256").update(new X509Certificate(pem).raw).digest("hex"); return { keyPath, certificatePath, pem, sha256 }; }
async function launch(worker: string, tls: ReturnType<typeof certificate>, statePath: string, env: Record<string, string>) { const tsx = join(process.cwd(), "node_modules/tsx/dist/loader.mjs"), child = spawn(process.execPath, ["--import", tsx, worker, tls.keyPath, tls.certificatePath, statePath], { env: { ...process.env, ...env } }); children.push(child); return await new Promise<{ child: ChildProcessWithoutNullStreams; serverUrl: string }>((resolve, reject) => { let stdout = "", stderr = ""; const timer = setTimeout(() => reject(new Error(`CF-058 provider launch timeout: ${stderr}`)), 5_000); child.stdout.on("data", (chunk) => { stdout += String(chunk); const newline = stdout.indexOf("\n"); if (newline >= 0) { clearTimeout(timer); resolve({ child, serverUrl: (JSON.parse(stdout.slice(0, newline)) as { serverUrl: string }).serverUrl }); } }); child.stderr.on("data", (chunk) => { stderr += String(chunk); }); child.once("exit", () => { clearTimeout(timer); reject(new Error(`CF-058 provider exited before ready: ${stderr}`)); }); }); }

function trust(root: string, draft: CustomerLocalHttpWriteAuthorityContractInput, admin: { publicKey: KeyObject; privateKey: KeyObject }) {
  const now = Date.now(), config: CustomerLocalTrustConfiguration = { schemaVersion: "1.0", tenantId: "cf058TrustTenant", environment: "local", keys: [{ keyId: "cf058_workspace_admin", issuer: "fictional_customer_admin", publicKeyPem: admin.publicKey.export({ type: "spki", format: "pem" }).toString(), notBefore: new Date(now - 60_000).toISOString(), notAfter: new Date(now + 86_400_000).toISOString() }] }, trustStatePath = join(root, "workspace-trust.sqlite"), authorityTrustStatePath = join(root, "authority-trust.sqlite");
  const trustStore = new CustomerLocalTrustStore(trustStatePath, config), authorityTrustStore = new CustomerLocalHttpAuthorityTrustStore({ statePath: authorityTrustStatePath, workspaceId: "cf058_workspace", initialAdminKeyId: "cf058_workspace_admin", trustStore });
  const { workspaceAuthority: _workspaceAuthority, ...base } = draft, authorityConfig = { ...base, workspaceAuthorityTrustStore: authorityTrustStore }, authorityContractDigest = customerLocalHttpAuthorityTrustContractDigest(authorityConfig);
  const activation = signWorkspaceHttpAuthorityActivation({ adminSignerKeyId: "cf058_workspace_admin", workspaceId: "cf058_workspace", authorityContractDigest, privateKey: admin.privateKey, issuedAt: new Date(now - 1_000).toISOString(), expiresAt: new Date(now + 3_600_000).toISOString(), activationNonce: "a".repeat(48) }); authorityTrustStore.importActivation(activation);
  closers.push(() => authorityTrustStore.close(), () => trustStore.close());
  return { trustStore, authorityTrustStore, authorityConfig, authorityContractDigest, activation, config, trustStatePath, authorityTrustStatePath };
}

type BoundPair = ReturnType<typeof compileCf058AuthorityEnforcedReviewedHttpBindings>;
class MutableResolver implements CustomerLocalCredentialResolver { resolverId = "cf058_credential_resolver"; implementationDigest = httpBindingCompilerDigest("cf058 credential resolver v1"); allowedAliases = [CF058_COLD_CHAIN_ACTION_CREDENTIAL_ALIAS, CF058_COLD_CHAIN_OBSERVER_CREDENTIAL_ALIAS]; missing = new Set<string>(); constructor(readonly action: string, readonly observer: string) {} async resolve(alias: string) { if (this.missing.has(alias)) return null; return alias === CF058_COLD_CHAIN_ACTION_CREDENTIAL_ALIAS ? { alias, value: this.action } : alias === CF058_COLD_CHAIN_OBSERVER_CREDENTIAL_ALIAS ? { alias, value: this.observer } : null; } }
const inputFor = (ref: string, quantity = 25, lot = `LOT-${ref}`): Record<string, unknown> => ({ directive_ref: ref, lot_code: lot, hold_quantity: quantity, reason_confirmed: true });
const actionInput = (ref: string, quantity = 25, lot?: string): CompiledHttpActionInput => ({ requestId: `request_${ref.toLowerCase().replace(/[^a-z0-9]/g, "_")}`, parentGoalId: `parent_${ref.toLowerCase().replace(/[^a-z0-9]/g, "_")}`, workItemId: `item_${ref.toLowerCase().replace(/[^a-z0-9]/g, "_")}`, workflowInput: inputFor(ref, quantity, lot), trustedContext: {} });
const exactRequest = (serverUrl: string, declarationDigest: string, ref: string, quantity = 25, lot = `LOT-${ref}`): CompiledHttpRequest => ({ requestId: `request_${ref.toLowerCase().replace(/[^a-z0-9]/g, "_")}`, parentGoalId: `parent_${ref.toLowerCase().replace(/[^a-z0-9]/g, "_")}`, workItemId: `item_${ref.toLowerCase().replace(/[^a-z0-9]/g, "_")}`, driverId: CF058_COLD_CHAIN_ACTION_DRIVER, targetAlias: CF058_COLD_CHAIN_TARGET_ALIAS, serverUrl, operationId: CF058_COLD_CHAIN_ACTION_OPERATION, method: "PUT", path: `/v2/lots/${lot}/quarantine-directives/${ref}`, query: {}, headers: {}, body: { hold_quantity: quantity, reason_confirmed: true }, credentialAlias: CF058_COLD_CHAIN_ACTION_CREDENTIAL_ALIAS, reconciliationKey: ref, declarationDigest });
const observationInput = (ref: string, started: number, quantity = 25, lot?: string): CompiledHttpObservationInput => ({ requestId: `observe_${ref.toLowerCase().replace(/[^a-z0-9]/g, "_")}`, parentGoalId: `parent_${ref.toLowerCase().replace(/[^a-z0-9]/g, "_")}`, workItemId: `item_${ref.toLowerCase().replace(/[^a-z0-9]/g, "_")}`, workflowInput: inputFor(ref, quantity, lot), trustedContext: {}, operationStartedAtEpochMs: started });
function result(caseId: PilotAdapterAcceptanceCase, passed: boolean, writes: number, detail: string): PilotAdapterAcceptanceResult { return { caseId, passed, intendedWrites: writes, incorrectSideEffects: 0, checks: [{ id: `cf058-${caseId}`, passed, detail }], artifactReferences: [`cf058-evidence://${caseId}/${digest(detail)}`], completedAt: new Date().toISOString() }; }

class Cf058Binding implements GenericAcceptanceBinding {
  readonly bindingId = "cf058-hardened-http-binding"; readonly bindingVersion = "1.0.0"; readonly caseIds = REQUIRED_PILOT_ADAPTER_CASES; readonly bindingDigest: string;
  interruptRestart = true;
  constructor(private readonly statePath: string, private readonly resolver: MutableResolver, private pair: BoundPair, private readonly retainedCheck: () => boolean, private readonly reconcileRestart: () => { classification: string; activationReceiptDigest: string; campaignRevision: number; observerImplementationDigest: string; observerDeclarationDigest: string; observerQualificationDigest: string; observerTransportImplementationDigest: string }, private readonly revokeAndRebuild: () => { pair: BoundPair; reactivate: () => BoundPair }, private readonly runRecovery: () => Promise<{ ok: boolean; pair: BoundPair }>) { this.bindingDigest = pair.boundPairDigest; }
  private reset(): World { const world = emptyWorld(); writeWorld(this.statePath, world); this.resolver.missing.clear(); return world; }
  private async executeAndObserve(ref: string, quantity = 25, lot?: string) { const started = Date.now(); await this.pair.compiledPair.action.execute(actionInput(ref, quantity, lot)); return await this.pair.compiledPair.observer.observe(observationInput(ref, started, quantity, lot)); }
  async execute(caseId: PilotAdapterAcceptanceCase, _context: GenericAcceptanceAttemptContext): Promise<PilotAdapterAcceptanceResult> {
    this.reset();
    if (caseId === "read-only-happy-path") { const world = emptyWorld(), now = new Date().toISOString(); world.directives.READ_1 = { directive_ref: "READ_1", lot_code: "LOT-READ_1", hold_quantity: 25, reason_confirmed: true, status: "quarantined", version: 1, updated_at: now }; world.sequence = 1; writeWorld(this.statePath, world); const observed = await this.pair.compiledPair.observer.observe(observationInput("READ_1", Date.now() - 1_000)); return result(caseId, observed.classification === "completed" && readWorld(this.statePath).writes === 0, 0, "Independent read completed without action, lease or write."); }
    if (caseId === "approved-write") { const observed = await this.executeAndObserve("APPROVED_1"); return result(caseId, observed.classification === "completed" && readWorld(this.statePath).writes === 1, 1, "One authority-bound PUT was independently verified."); }
    if (caseId === "fresh-process-reuse") { const retained = this.retainedCheck(), observed = await this.executeAndObserve("REUSE_1"); return result(caseId, retained && observed.classification === "completed" && readWorld(this.statePath).writes === 1, 1, "A fresh process reopened the candidate as retained before one verified write."); }
    if (caseId === "missing-credential") { this.resolver.missing.add(CF058_COLD_CHAIN_ACTION_CREDENTIAL_ALIAS); await expect(this.pair.compiledPair.action.execute(actionInput("NO_CRED_1"))).rejects.toThrow(/credential alias.*unavailable/i); return result(caseId, readWorld(this.statePath).writes === 0, 0, "Missing credential stopped before dispatch."); }
    if (caseId === "missing-permission") { const revoked = this.revokeAndRebuild(); await expect(revoked.pair.compiledPair.action.execute(actionInput("NO_PERMISSION_1"))).rejects.toThrow(/activation|authority|revoked|stale/i); this.pair = revoked.reactivate(); return result(caseId, readWorld(this.statePath).writes === 0, 0, "Revoked exact activation stopped before network write."); }
    if (caseId === "lost-response-reconciliation") { const recovery = await this.runRecovery(); this.pair = recovery.pair; return result(caseId, recovery.ok && readWorld(this.statePath).writes === 2, 2, "Expired unconsumed generation was replaced; signed not-started recovery reissued once; postcommit loss reconciled without replay."); }
    if (caseId === "wrong-or-partial-outcome") { const world = emptyWorld(); world.directives.PARTIAL_1 = { directive_ref: "PARTIAL_1", lot_code: "LOT-PARTIAL_1", status: "partial", version: 1, updated_at: new Date().toISOString() }; world.sequence = 1; writeWorld(this.statePath, world); const observed = await this.pair.compiledPair.observer.observe(observationInput("PARTIAL_1", Date.now() - 1_000)); return result(caseId, observed.classification === "partial" && readWorld(this.statePath).writes === 0, 0, "A pre-existing partial state was quarantined without a CF write."); }
    if (caseId === "sidecar-restart") { await this.executeAndObserve("RESTART_1"); if (this.interruptRestart) { this.interruptRestart = false; throw new Error("CF-058 simulated runner exit after write and before durable campaign receipt."); } throw new Error("CF-058 restart execution must reconcile, never rerun."); }
    if (caseId === "duplicate-submission") { await this.pair.compiledPair.action.execute(actionInput("DUP_1")); try { await this.pair.compiledPair.action.execute(actionInput("DUP_1")); } catch {} const observed = await this.pair.compiledPair.observer.observe(observationInput("DUP_1", Date.now() - 1_000)); return result(caseId, observed.classification === "completed" && readWorld(this.statePath).writes === 1, 1, "Exact duplicate submission produced one external write."); }
    await this.pair.compiledPair.action.execute(actionInput("CONFLICT_1")); await expect(this.pair.compiledPair.action.execute(actionInput("CONFLICT_1", 31))).rejects.toThrow(); return result(caseId, readWorld(this.statePath).writes === 1, 1, "Conflicting stable-identity reuse was rejected before a second write.");
  }
  async reconcileInterrupted(caseId: PilotAdapterAcceptanceCase): Promise<PilotAdapterAcceptanceResult> { if (caseId !== "sidecar-restart") throw new Error(`No CF-058 reconciliation route for ${caseId}.`); const fresh = this.reconcileRestart(), world = readWorld(this.statePath); return result(caseId, fresh.classification === "completed" && world.writes === 1, 1, `A genuine fresh process reopened campaign and workspace-authority state, then independently reconciled the committed result without replay (classification=${fresh.classification}, writes=${world.writes}, revision=${fresh.campaignRevision}).`); }
}

describe("CF-058 causally joined hardened HTTP acceptance", () => {
  it("runs all ten mandatory cases through the exact acquired candidate and distinct pinned providers", async () => {
    const root = mkdtempSync(join(tmpdir(), "cf058-hardened-acceptance-")); roots.push(root); const statePath = join(root, "world.json"); writeWorld(statePath, emptyWorld());
    const actionTls = certificate(root, "action"), observerTls = certificate(root, "observer"), actionToken = "cf058-action-token-value", observerToken = "cf058-observer-token-value";
    const actionProvider = await launch(join(process.cwd(), "test/fixtures/cf058-cold-chain-action-provider-worker.ts"), actionTls, statePath, { CF058_ACTION_TOKEN: actionToken }), observerProvider = await launch(join(process.cwd(), "test/fixtures/cf058-cold-chain-observer-provider-worker.ts"), observerTls, statePath, { CF058_OBSERVER_TOKEN: observerToken });
    const reviewed = cf058ColdChainSplitReviewedSource(actionProvider.serverUrl, observerProvider.serverUrl), sourceRoot = join(root, "source-main"), source = createCf058ColdChainProductionDerivationFixture(sourceRoot, reviewed), registryRoot = join(root, "registry"), workspaceTrustRoot = join(root, "cf053-workspace-trust");
    const derived = deriveCf053ProviderNeutralContract({ board: source.board, coordinator: source.coordinator, reader: source.reader, boardId: source.boardId, tenantId: source.tenantId, trustedDeployment: { tenantId: source.tenantId, targetAlias: CF058_COLD_CHAIN_TARGET_ALIAS, policyVersion: "cf058_cold_chain_policy_v1", workspaceTrustRootDirectory: workspaceTrustRoot } }), registry = new Cf053ContentAddressedCandidateRegistry(registryRoot), candidate = registry.acquire(derived, "2026-08-14T11:40:00.000Z"), bridge = joinCf058OpaqueCausalHttpBridge({ candidate, workPack: source.upstream.workPack, factoryResult: reviewed.factoryResult }); closers.push(() => source.close());
    const resolver = new MutableResolver(actionToken, observerToken), actionConfig: CustomerLocalPinnedHttpsTransportConfig = { driverId: CF058_COLD_CHAIN_ACTION_DRIVER, sourceId: "cf058_action_source", serverUrl: actionProvider.serverUrl, supportedMethods: ["PUT"], independentlyAuthenticated: true, independentFromDriverIds: [], credentialAlias: CF058_COLD_CHAIN_ACTION_CREDENTIAL_ALIAS, reviewedOperations: [{ operationId: CF058_COLD_CHAIN_ACTION_OPERATION, method: "PUT", pathTemplate: CF058_COLD_CHAIN_ACTION_PATH, declarationDigest: reviewed.factoryResult.actionBinding!.declarationDigest }], authorizationScheme: "Bearer", caCertificatePem: actionTls.pem, serverCertificateSha256: actionTls.sha256, timeoutMilliseconds: 1_000, maximumRequestBytes: 65_536, maximumResponseBytes: 65_536, maximumResponseHeaders: 32, maximumRequestsPerMinute: 120 };
    const observerTransport = createCustomerLocalPinnedHttpsTransport({ driverId: CF058_COLD_CHAIN_OBSERVER_DRIVER, sourceId: CF058_COLD_CHAIN_OBSERVER_SOURCE, serverUrl: observerProvider.serverUrl, supportedMethods: ["GET"], independentlyAuthenticated: true, independentFromDriverIds: [CF058_COLD_CHAIN_ACTION_DRIVER], credentialAlias: CF058_COLD_CHAIN_OBSERVER_CREDENTIAL_ALIAS, reviewedOperations: [{ operationId: CF058_COLD_CHAIN_OBSERVER_OPERATION, method: "GET", pathTemplate: CF058_COLD_CHAIN_OBSERVER_PATH, declarationDigest: reviewed.factoryResult.observerBinding!.declarationDigest }], authorizationScheme: "Bearer", caCertificatePem: observerTls.pem, serverCertificateSha256: observerTls.sha256, timeoutMilliseconds: 1_000, maximumRequestBytes: 65_536, maximumResponseBytes: 65_536, maximumResponseHeaders: 32, maximumRequestsPerMinute: 240 });
    const qualifiedAt = new Date().toISOString(), expiresAt = new Date(Date.now() + 3_600_000).toISOString(), preliminaryAction = createCustomerLocalPinnedHttpsTransport(actionConfig), preliminaryQualification = createLocalFixtureBindingQualification({ tenantId: source.tenantId, sessionId: "cf058_preliminary", packageDigest: digest("cf058 preliminary package"), sourceDigest: reviewed.normalization.normalizationReceiptDigest, factoryResult: reviewed.factoryResult, actionTransport: preliminaryAction, observerTransport, credentialResolver: resolver, qualifiedAt, expiresAt }), preliminaryPair = compileReviewedHttpBindings({ factoryResult: reviewed.factoryResult, actionTransport: preliminaryAction, observerTransport, credentialResolver: resolver, primitiveRegistryDigest: digest("cf058 primitives"), verifierRegistryDigest: digest("cf058 verifiers"), qualifiedAt, expiresAt, customerLocalQualification: preliminaryQualification });
    const observerKeys = generateKeyPairSync("ed25519"), recoverySigner = createCustomerLocalHttpNotStartedObserverSigner({ signerKeyId: "cf058_recovery_observer", privateKey: observerKeys.privateKey, publicKey: observerKeys.publicKey, observerImplementationDigest: preliminaryPair.observer.implementationDigest, observerBindingDigest: preliminaryPair.observer.declarationDigest, observerQualificationDigest: preliminaryPair.observer.qualification.qualificationDigest, maximumReceiptMilliseconds: 30_000 });
    const authorityKeys = generateKeyPairSync("ed25519"), adminKeys = generateKeyPairSync("ed25519"), authorityDraft: CustomerLocalHttpWriteAuthorityContractInput = { statePath: join(root, "write-authority.sqlite"), issuerId: "cf058_authority", signerKeyId: "cf058_authority_signer", privateKey: authorityKeys.privateKey, publicKey: authorityKeys.publicKey, authorityCompilation: reviewed.authorityCompilation, actionDeclaration: reviewed.factoryResult.actionBinding!, transportAuthorityBoundaryDigest: pinnedHttpsAuthorityBoundaryDigest(actionConfig), credentialResolverDigest: resolver.implementationDigest, quantityMetric: { kind: "json-body-number", field: "hold_quantity" }, maximumLeaseMilliseconds: 150, maximumRecoveryEvidenceMilliseconds: 30_000, recoveryObserver: { signerKeyId: recoverySigner.signerKeyId, publicKey: observerKeys.publicKey, observerImplementationDigest: recoverySigner.observerImplementationDigest, observerBindingDigest: recoverySigner.observerBindingDigest, observerQualificationDigest: recoverySigner.observerQualificationDigest }, workspaceAuthority: { workspaceId: "cf058_workspace", adminSignerKeyId: "cf058_workspace_admin", adminPublicKey: adminKeys.publicKey } }, trusted = trust(root, authorityDraft, adminKeys); let currentActivationReceiptDigest = trusted.activation.receiptDigest;
    let activeAuthority: { issuer: CustomerLocalHttpWriteAuthorityIssuer; verifier: CustomerLocalHttpWriteAuthorityVerifier; close(): void } | undefined, activeActionTransport: CustomerLocalHttpTransport | undefined;
    const compile = (): BoundPair => { activeAuthority?.close(); const authority = createTestCustomerLocalHttpWriteAuthorityFromTrustStore({ ...trusted.authorityConfig, testOnly: true }); activeAuthority = { ...authority, close: () => { authority.verifier.close(); authority.issuer.close(); } }; const actionTransport = createAuthorityEnforcedCustomerLocalPinnedHttpsTransport({ ...actionConfig, writeAuthorityVerifier: authority.verifier }); activeActionTransport = actionTransport; const qualification = createLocalFixtureBindingQualification({ tenantId: source.tenantId, sessionId: "cf058_final", packageDigest: digest("cf058 final package"), sourceDigest: reviewed.normalization.normalizationReceiptDigest, factoryResult: reviewed.factoryResult, actionTransport, observerTransport, credentialResolver: resolver, qualifiedAt, expiresAt }); return compileCf058AuthorityEnforcedReviewedHttpBindings({ causalBridge: bridge.handle, factoryResult: reviewed.factoryResult, actionTransport, observerTransport, credentialResolver: resolver, primitiveRegistryDigest: digest("cf058 primitives"), verifierRegistryDigest: digest("cf058 verifiers"), qualifiedAt, expiresAt, customerLocalQualification: qualification, writeAuthorityIssuer: authority.issuer, recoveryObserverSigner: recoverySigner }); };
    let pair = compile(); closers.push(() => activeAuthority?.close());
    const retainedCheck = () => { const output = execFileSync(process.execPath, ["--import", join(process.cwd(), "node_modules/tsx/dist/loader.mjs"), join(process.cwd(), "test/fixtures/cf058-retained-candidate-worker.ts"), registryRoot, workspaceTrustRoot, candidate.candidateDigest], { encoding: "utf8", timeout: 10_000 }); const parsed = JSON.parse(output) as { source: string; candidateDigest: string }; return parsed.source === "retained" && parsed.candidateDigest === candidate.candidateDigest; };
    const revokeAndRebuild = () => { const revokedPair = pair, now = Date.now(), revocation = signWorkspaceHttpAuthorityActivationRevocation({ workspaceId: "cf058_workspace", authorityContractDigest: trusted.authorityContractDigest, activationReceiptDigest: trusted.activation.receiptDigest, trustConfigurationDigest: trusted.trustStore.configDigest, revocationSignerKeyId: "cf058_workspace_admin", revocationSignerPublicKeyDigest: createHash("sha256").update(adminKeys.publicKey.export({ type: "spki", format: "der" })).digest("hex"), issuedAt: new Date(now).toISOString(), effectiveAt: new Date(now).toISOString(), reason: "CF-058 missing-permission control revokes the exact activation.", revocationNonce: "b".repeat(48), privateKey: adminKeys.privateKey }); trusted.authorityTrustStore.revokeActivation(revocation); return { pair: revokedPair, reactivate: () => { activeAuthority?.close(); activeAuthority = undefined; const activation = signWorkspaceHttpAuthorityActivation({ adminSignerKeyId: "cf058_workspace_admin", workspaceId: "cf058_workspace", authorityContractDigest: trusted.authorityContractDigest, privateKey: adminKeys.privateKey, issuedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 3_600_000).toISOString(), activationNonce: "c".repeat(48) }); trusted.authorityTrustStore.importActivation(activation); currentActivationReceiptDigest = activation.receiptDigest; pair = compile(); return pair; } }; };
    const runRecovery = async () => { writeWorld(statePath, { ...emptyWorld(), faultByDirective: { RECOVER_PRE: "precommit-drop" } }); const started = Date.now(), request = exactRequest(actionProvider.serverUrl, reviewed.factoryResult.actionBinding!.declarationDigest, "RECOVER_PRE"), oldAuthority = activeAuthority!, oldTransport = activeActionTransport!, prepared = oldTransport.prepareWrite!(request, { alias: CF058_COLD_CHAIN_ACTION_CREDENTIAL_ALIAS, value: actionToken }), generationOne = await oldAuthority.issuer.issueLease({ request, credentialAlias: CF058_COLD_CHAIN_ACTION_CREDENTIAL_ALIAS, transportReservationDigest: prepared.reservationDigest }); oldAuthority.close(); activeAuthority = undefined; await new Promise((resolve) => setTimeout(resolve, 180)); pair = compile(); let interrupted: CompiledHttpActionDispatchUncertainError | undefined; try { await pair.compiledPair.action.execute({ ...actionInput("RECOVER_PRE"), unconsumedReplacement: { priorLease: generationOne, reason: "expired-before-consume" } }); } catch (error) { if (error instanceof CompiledHttpActionDispatchUncertainError) interrupted = error; else throw error; } if (!interrupted || interrupted.consumedAuthorityLease.generation !== 2) return { ok: false, pair }; let stalePreparedRejected = false; try { await prepared.dispatch(generationOne); } catch { stalePreparedRejected = true; } const notStarted = await pair.compiledPair.observer.observe({ ...observationInput("RECOVER_PRE", started), recoveryContext: { priorLease: interrupted.consumedAuthorityLease, actionRequest: interrupted.request } }); await pair.compiledPair.action.execute({ ...actionInput("RECOVER_PRE"), notStartedRecovery: { priorLease: interrupted.consumedAuthorityLease, receipt: notStarted.notStartedRecoveryReceipt!, observation: notStarted } }); const preObserved = await pair.compiledPair.observer.observe(observationInput("RECOVER_PRE", started)); const world = readWorld(statePath); world.faultByDirective.RECOVER_POST = "postcommit-drop"; writeWorld(statePath, world); let postInterrupted = false; try { await pair.compiledPair.action.execute(actionInput("RECOVER_POST")); } catch (error) { postInterrupted = error instanceof CompiledHttpActionDispatchUncertainError; } const postObserved = await pair.compiledPair.observer.observe(observationInput("RECOVER_POST", Date.now() - 1_000)); return { ok: stalePreparedRejected && postInterrupted && preObserved.classification === "completed" && postObserved.classification === "completed" && readWorld(statePath).writes === 2, pair }; };
    const campaignId = "cf058-cold-chain-v3", campaignRoot = join(root, "campaign"), restartInputPath = join(root, "restart-reconciliation-input.json"), executionManifestPath = join(root, "frozen-execution-manifest.json");
    const sourceFileDigest = (path: string) => createHash("sha256").update(readFileSync(path)).digest("hex");
    const executionManifestBody = { schemaVersion: "1.0", campaignId, frozenAt: new Date().toISOString(), replacementPrecommitSha256: sourceFileDigest(join(process.cwd(), "development/cf-058-hardened-http-acceptance-v3/precommit.json")), actionOpenApiSha256: sourceFileDigest(join(process.cwd(), "test/fixtures/cf058-cold-chain/openapi.json")), observerOpenApiSha256: sourceFileDigest(join(process.cwd(), "test/fixtures/cf058-cold-chain/observer-openapi.json")), actionProviderSourceSha256: sourceFileDigest(join(process.cwd(), "test/fixtures/cf058-cold-chain-action-provider-worker.ts")), observerProviderSourceSha256: sourceFileDigest(join(process.cwd(), "test/fixtures/cf058-cold-chain-observer-provider-worker.ts")), retainedWorkerSourceSha256: sourceFileDigest(join(process.cwd(), "test/fixtures/cf058-retained-candidate-worker.ts")), restartWorkerSourceSha256: sourceFileDigest(join(process.cwd(), "test/fixtures/cf058-restart-reconciliation-worker.ts")), candidateDigest: candidate.candidateDigest, candidateSource: candidate.source, cf036WorkPackDigest: source.upstream.workPack.workPackDigest, factoryResultDigest: reviewed.factoryResult.resultDigest, actionNormalizationDigest: reviewed.normalization.normalizationReceiptDigest, observerNormalizationDigest: reviewed.observerNormalization.normalizationReceiptDigest, causalBridgeDigest: bridge.receipt.bridgeDigest, initialBoundPairDigest: pair.boundPairDigest, authorityContractDigest: trusted.authorityContractDigest, activationReceiptDigest: trusted.activation.receiptDigest, actionServerUrl: actionProvider.serverUrl, observerServerUrl: observerProvider.serverUrl, actionLeafCertificateSha256: actionTls.sha256, observerLeafCertificateSha256: observerTls.sha256, orderedCases: REQUIRED_PILOT_ADAPTER_CASES, expectedWrites: 7, credentialValuesPersisted: false, modelCalls: 0, paidSpendUsd: 0 };
    const executionManifest = { ...executionManifestBody, manifestDigest: digest(executionManifestBody) }; writeFileSync(executionManifestPath, `${JSON.stringify(executionManifest, null, 2)}\n`, { flag: "wx", mode: 0o600 }); expect(JSON.parse(readFileSync(executionManifestPath, "utf8"))).toEqual(executionManifest);
    const reconcileRestart = () => { writeFileSync(restartInputPath, JSON.stringify({ campaignRoot, campaignId, tenantId: source.tenantId, actionServerUrl: actionProvider.serverUrl, observerServerUrl: observerProvider.serverUrl, actionCertificatePem: actionTls.pem, actionCertificateSha256: actionTls.sha256, observerCertificatePem: observerTls.pem, observerCertificateSha256: observerTls.sha256, qualifiedAt, expiresAt, trustStatePath: trusted.trustStatePath, authorityTrustStatePath: trusted.authorityTrustStatePath, trustConfiguration: trusted.config, workspaceId: "cf058_workspace", initialAdminKeyId: "cf058_workspace_admin", authorityContractDigest: trusted.authorityContractDigest, observation: observationInput("RESTART_1", Date.now() - 5_000) }), { mode: 0o600 }); const output = execFileSync(process.execPath, ["--import", join(process.cwd(), "node_modules/tsx/dist/loader.mjs"), join(process.cwd(), "test/fixtures/cf058-restart-reconciliation-worker.ts"), restartInputPath], { encoding: "utf8", timeout: 10_000, env: { ...process.env, CF058_ACTION_TOKEN: actionToken, CF058_OBSERVER_TOKEN: observerToken } }), parsed = JSON.parse(output) as { classification: string; activationReceiptDigest: string; campaignRevision: number; observerImplementationDigest: string; observerDeclarationDigest: string; observerQualificationDigest: string; observerTransportImplementationDigest: string }; if (parsed.activationReceiptDigest !== currentActivationReceiptDigest) throw new Error("CF-058 restart worker reopened a different workspace activation."); if (parsed.observerDeclarationDigest !== reviewed.factoryResult.observerBinding!.declarationDigest) throw new Error("CF-058 restart worker rebuilt a different reviewed observer declaration."); if (parsed.observerTransportImplementationDigest !== observerTransport.implementationDigest) throw new Error(`CF-058 restart worker rebuilt a different pinned observer transport (${parsed.observerTransportImplementationDigest} != ${observerTransport.implementationDigest}).`); return parsed; };
    const binding = new Cf058Binding(statePath, resolver, pair, retainedCheck, reconcileRestart, revokeAndRebuild, runRecovery), store = new JsonFileGenericAcceptanceCampaignStore(campaignRoot);
    const first = await runGenericAcceptanceCampaign({ campaignId, declarationDigest: executionManifest.manifestDigest, binding, store });
    expect(first).toMatchObject({ status: "awaiting-reconciliation", passed: false, passedCases: 7 });
    const completed = await runGenericAcceptanceCampaign({ campaignId, declarationDigest: executionManifest.manifestDigest, binding, store });
    expect(completed).toMatchObject({ status: "completed", passed: true, declaredCases: 10, passedCases: 10, reconciledCases: 1, incorrectSideEffects: 0 });
    expect(completed.state.receipts.reduce((sum, receipt) => sum + receipt.result.intendedWrites, 0)).toBe(7);
    expect(readWorld(statePath).writes).toBe(1);
    const authorityDatabase = new DatabaseSync(authorityDraft.statePath, { readOnly: true }), unresolvedLeases = (authorityDatabase.prepare("SELECT COUNT(*) AS count FROM http_authority_leases WHERE status='issued' AND retired_at_epoch_ms IS NULL AND expires_at_epoch_ms > ?").get(Date.now()) as { count: number }).count; authorityDatabase.close(); expect(unresolvedLeases).toBe(0);
    const registryFile = JSON.parse(readFileSync(join(registryRoot, "registry.json"), "utf8")) as { entries: Array<{ buildOrdinal: number }> }; expect(registryFile.entries).toHaveLength(1); expect(registryFile.entries[0]!.buildOrdinal).toBe(1);
    const evidenceDirectory = process.env.CF058_EVIDENCE_DIR;
    if (evidenceDirectory) { mkdirSync(evidenceDirectory, { recursive: true, mode: 0o700 }); writeFileSync(join(evidenceDirectory, "frozen-execution-manifest.json"), `${JSON.stringify(executionManifest, null, 2)}\n`, { mode: 0o600 }); const resultBody = { schemaVersion: "1.0", checkpointId: "CF-058", campaignId, status: completed.status, passed: completed.passed, declaredCases: completed.declaredCases, passedCases: completed.passedCases, reconciledCases: completed.reconciledCases, intendedBusinessWrites: completed.state.receipts.reduce((sum, receipt) => sum + receipt.result.intendedWrites, 0), survivingIncorrectSideEffects: completed.incorrectSideEffects, candidateBuilds: registryFile.entries.length, retainedFreshProcess: completed.state.cases.find((item) => item.caseId === "fresh-process-reuse")?.status === "passed", genuineRestartReconciliation: completed.state.receipts.some((receipt) => receipt.caseId === "sidecar-restart" && receipt.source === "interrupted-reconciliation" && receipt.result.passed), unresolvedAuthorityLeases: unresolvedLeases, observerWrites: 0, blindRetries: 0, modelCalls: 0, paidSpendUsd: 0, finalReceiptHash: completed.latestReceiptHash, evidenceBoundary: "Author-designed fictional local constrained-HTTP campaign; not customer, production, arbitrary-API, independent held-out, public, universal-capability or CF-DAS integration evidence." }, result = { ...resultBody, resultDigest: digest(resultBody) }; writeFileSync(join(evidenceDirectory, "result.json"), `${JSON.stringify(result, null, 2)}\n`, { mode: 0o600 }); }
  }, 60_000);
});
