import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { applyProviderEvidenceReuse, prepareProviderEvidenceReuse } from "../src/product/customer-local-provider-evidence-reuse.js";
import { closeProviderWorkEvidenceCoordinator, createCoordinatedProviderWorkBoard, createProviderWorkEvidenceCoordinator, providerWorkBoardDigest, type ProviderWorkBoardInput, type ProviderWorkJourneyReader } from "../src/product/customer-local-provider-work-board.js";
import { sdkSemanticDigest, type ConfirmedFact, type SdkSemanticContract } from "../src/product/customer-local-sdk-semantic-compiler.js";
import { sdkWorkPackDigest, type SdkImplementationWorkPack } from "../src/product/customer-local-sdk-work-pack.js";
import { httpBindingCompilerDigest } from "../src/product/http-binding-compiler.js";
import type { HttpBindingFactoryResult } from "../src/product/http-binding-factory.js";
import { Cf053ContentAddressedCandidateRegistry, deriveCf053ProviderNeutralContract, reopenCf053DerivedContractFromDurableCandidate } from "../src/product/local-declarative-exact-record-core.js";
import { cf058CausalBridgeDigest, compileCf058AuthorityEnforcedReviewedHttpBindings, joinCf058OpaqueCausalHttpBridge } from "../src/product/cf058-opaque-causal-http-bridge.js";
import { CF053_FIXTURE_NOW, cf053UpstreamSource } from "./fixtures/cf053-author-known-upstream.js";

// Anchored to the fixture's real-clock base: expiry is enforced against real
// time in trust code, so fixed historical dates lapse as wall time passes.
const NOW = CF053_FIXTURE_NOW, EXPIRES = new Date(Date.parse(NOW) + 86_400_000).toISOString();
const TARGET = "cold_chain_quarantine", ACTION_SCOPE = "PUT /v2/lots/{lot_code}/quarantine-directives/{directive_ref}", OBSERVER_SCOPE = "GET /v2/audit/quarantine-directives";
const canonical = (value: unknown): string => { if (value === undefined) return "undefined"; if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (value !== null && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`; return JSON.stringify(value); };
const digest = (value: unknown): string => httpBindingCompilerDigest(value);
const fact = (pointer: string): ConfirmedFact => ({ provenance: "engineer-confirmed", confirmedBy: "cf058Engineer", confirmedAt: NOW, sourcePointer: pointer });

function factoryResult(): HttpBindingFactoryResult {
  const provenance = { normalizedMaterialDigest: digest("cf058-normalized"), normalizationReceiptDigest: digest("cf058-normalization"), authorityCompilationDigest: digest("cf058-authority"), confirmedFactsDigest: digest("cf058-facts"), operationPointer: "#/paths/quarantine" };
  const actionBody = { schemaVersion: "1.0" as const, kind: "constrained-http-action-binding-declaration" as const, state: "proposal-only" as const, executable: false as const, qualified: false as const, activated: false as const, driverId: "coldChainActionDriver", targetAlias: TARGET, serverUrl: "https://cold-chain.invalid", operation: { operationId: "upsertQuarantineDirective", method: "PUT" as const, pathTemplate: "/v2/lots/{lot_code}/quarantine-directives/{directive_ref}" }, credentialAlias: "cred.quarantine.writer", requestMappings: [{ source: { kind: "workflow-input" as const, inputKey: "lot_code", confirmed: true as const }, destination: { location: "path" as const, name: "lot_code" }, transform: "identity" as const, confirmed: true as const }, { source: { kind: "workflow-input" as const, inputKey: "directive_ref", confirmed: true as const }, destination: { location: "path" as const, name: "directive_ref" }, transform: "identity" as const, confirmed: true as const }], reconciliationKeySource: { kind: "workflow-input" as const, inputKey: "directive_ref", confirmed: true as const }, acceptedStatuses: [200, 201], authorityPolicy: "preauthorized" as const, retry: { reconcileBeforeRetry: true as const, blindRetryAllowed: false as const }, provenance };
  const observerBody = { schemaVersion: "1.0" as const, kind: "independent-http-observer-binding-declaration" as const, state: "proposal-only" as const, executable: false as const, qualified: false as const, activated: false as const, driverId: "coldChainObserverDriver", sourceId: "coldChainIndependentAudit", targetAlias: TARGET, serverUrl: "https://cold-chain-audit.invalid", operation: { operationId: "auditQuarantineDirective", method: "GET" as const, pathTemplate: "/v2/audit/quarantine-directives" }, credentialAlias: "cred.quarantine.audit", parameterBindings: [{ name: "directive_ref", location: "query" as const, source: { kind: "workflow-input" as const, inputKey: "directive_ref", confirmed: true as const }, purpose: "stable-identifier" as const, confirmed: true as const }], resultPath: ["matches"], acceptedStatuses: [200], freshness: { kind: "server-timestamp-body" as const, path: ["observedAt"], maximumAgeSeconds: 60, confirmed: true as const, notBeforeBoundary: "trusted-operation-start" as const }, predicates: [{ key: "sameLot", path: ["lot_code"], operator: "equals-input" as const, inputKey: "lot_code", confirmed: true as const }, { key: "sameDirective", path: ["directive_ref"], operator: "equals-input" as const, inputKey: "directive_ref", confirmed: true as const }], notStartedDefinition: [{ key: "none", path: ["matches"], operator: "count-equals" as const, expectedCount: 0, confirmed: true as const }], duplicateCheck: { collectionPath: ["matches"], uniqueKeyPath: ["directive_ref"], expectedCount: 1, confirmed: true as const }, collateralChecks: [{ key: "clean", path: ["collateralClean"], operator: "equals-confirmed" as const, expected: true, confirmed: true as const }], actionResponseEligibleAsProof: false as const, provenance };
  const actionBinding = { ...actionBody, declarationDigest: digest(actionBody) }, observerBinding = { ...observerBody, declarationDigest: digest(observerBody) };
  const body = { schemaVersion: "1.0" as const, status: "review-required" as const, executable: false as const, qualified: false as const, activated: false as const, actionBinding, observerBinding, blockers: [], engineeringWorkRemaining: [], automationMetrics: { humanStudy: false as const, humanActiveMinutes: null, confirmedFactCount: 12, generatedActionDeclarationFields: 12, generatedObserverDeclarationFields: 12, executableCodeLinesGenerated: 0 as const, qualificationControlsRun: 0 as const }, onboardingProjection: { state: "binding-declarations-ready" as const, acceptanceReviewDigestsEligible: false as const, authorityRuntimeBindingDigest: null, observationAdapterBindingDigest: null, exactNextGates: [], evidenceBoundary: "Reviewed declarations only." } };
  return { ...body, resultDigest: digest(body) };
}

function upstream(factory: HttpBindingFactoryResult): { workPack: SdkImplementationWorkPack; contract: SdkSemanticContract } {
  const providerId = "cf058_cold_chain_provider", keys = ["lot_code", "directive_ref"], roleNames = { action: "upsertQuarantineDirective", "no-write-probe": "probeQuarantineService", "reconciliation-readback": "readQuarantineDirective", "independent-observer": "auditQuarantineDirective" } as const;
  const roles = (Object.keys(roleNames) as Array<keyof typeof roleNames>).map((role, index) => { const actionPlane = role === "action" || role === "no-write-probe", method = { module: actionPlane ? "cold_chain_action_sdk" : "cold_chain_audit_sdk", className: actionPlane ? "QuarantineClient" : "QuarantineAuditClient", methodName: roleNames[role], overloadId: "v1", parameters: keys.map((name) => ({ name, type: "string", required: true, sourcePointer: `#/methods/${role}/${name}` })), returnType: "Promise<Record<string, unknown>>", errorTypes: ["SdkError"], authAliasRequirements: [actionPlane ? "cred.quarantine.writer" : "cred.quarantine.audit"], pagination: "none" as const, retryCandidate: role === "action" ? "idempotency-key" as const : "read-only" as const, idempotencyCandidate: role === "action" ? "directive_ref" : null, sourcePointer: `#/methods/${role}` }; return { review: { role, module: method.module, className: method.className, methodName: method.methodName, overloadId: "v1", expectedSourcePointer: method.sourcePointer, reviewerAlias: "cf058Engineer", reviewedAt: NOW, exactOneToOne: true as const }, method, methodDigest: sdkWorkPackDigest(method), provenance: { sourceKind: "reference-json" as const, localReference: "fixture://cf058-cold-chain", sourcePointer: method.sourcePointer, sdkSourceDigest: sdkSemanticDigest({ providerId, source: 1 }) } }; });
  const packBody = { schemaVersion: "1.0" as const, state: "engineer-implementation-required" as const, providerId, pluginId: "cf058_cold_chain_plugin", sdkSourceDigest: sdkSemanticDigest({ providerId, source: 1 }), factoryResultDigest: factory.resultDigest, roles, normalized: { modules: [...new Set(roles.map((item) => item.method.module))], classes: [...new Set(roles.map((item) => item.method.className))], methodCount: 4, parameterCount: 8, returnShapeCount: 1, errorShapeCount: 1, authAliasRequirements: ["cred.quarantine.audit", "cred.quarantine.writer"], paginationCandidates: ["none"], retryCandidates: ["idempotency-key", "read-only"], idempotencyCandidates: ["directive_ref"] }, blockedUnknowns: [], conformanceControls: [{ controlId: "cf058-source-review", state: "not-run" as const }], generatedFiles: [], generatedLines: 0, mappedMethods: 4, mappedFields: 12, explicitReviews: 4, executionAuthorityEffect: "none" as const, activationEffect: "none" as const }, workPack = { ...packBody, workPackDigest: sdkWorkPackDigest(packBody) };
  const expression = (key: string) => ({ source: "workflow-input" as const, key, convert: "string" as const, fact: fact(`#/input/${key}`) });
  const parameterMappings = roles.flatMap((item) => keys.map((key) => ({ role: item.review.role, parameter: key, expression: expression(key), fact: fact(`${item.method.sourcePointer}/${key}`) })));
  const contractBody = { schemaVersion: "1.0" as const, contractId: "cf058_cold_chain_contract", providerId, sdkSourceDigest: workPack.sdkSourceDigest, workPackDigest: workPack.workPackDigest, roles: roles.map((item) => ({ role: item.review.role, methodDigest: item.methodDigest, fact: fact(item.method.sourcePointer) })), parameterMappings, credentials: { action: { alias: "cred.quarantine.writer", exactScope: ACTION_SCOPE, fact: fact("#/credentials/writer") }, observer: { alias: "cred.quarantine.audit", exactScope: OBSERVER_SCOPE, fact: fact("#/credentials/audit") } }, stableIdentity: { expression: expression("directive_ref"), collisionPolicy: "reject-conflict" as const, fact: fact("#/identity") }, idempotency: { expression: expression("directive_ref"), conflictIdentity: [expression("lot_code"), expression("directive_ref")], reconcileBeforeRetry: true as const, blindRetryAllowed: false as const, fact: fact("#/idempotency") }, reconciliation: { role: "reconciliation-readback" as const, notFoundClassification: "not-started" as const, multipleClassification: "duplicate" as const, fact: fact("#/reconciliation") }, observer: { role: "independent-observer" as const, sourceId: "coldChainIndependentAudit", authIndependent: true as const, differentMethodFromAction: true as const, fact: fact("#/observer") }, outcome: { predicates: keys.map((key) => ({ key, path: [key], operator: "equals-input" as const, inputKey: key, fact: fact(`#/outcome/${key}`) })), duplicate: { collectionPath: ["matches"], expectedCount: 1 as const, fact: fact("#/outcome/duplicate") }, collateral: [{ key: "clean", path: ["collateralClean"], operator: "equals-confirmed" as const, expected: true, fact: fact("#/outcome/collateral") }], freshness: { path: ["observedAt"], maximumAgeSeconds: 60, notBefore: "operation-start" as const, fact: fact("#/outcome/freshness") }, fact: fact("#/outcome") }, pagination: { roles: [{ role: "reconciliation-readback" as const, mode: "not-paginated" as const, maximumPages: 1, fact: fact("#/pagination/reconcile") }, { role: "independent-observer" as const, mode: "not-paginated" as const, maximumPages: 1, fact: fact("#/pagination/observe") }], complete: true as const, fact: fact("#/pagination") }, policy: { timeoutMilliseconds: 5000, maximumRequestsPerMinute: 60, maximumAttempts: 2 as const, retryableErrors: ["TimeoutBeforeCommit"], terminalErrors: ["Unauthorized"], fact: fact("#/policy") }, sourceDigest: sdkSemanticDigest({ providerId, contract: 1 }), expiresAt: EXPIRES, executionAuthorityEffect: "none" as const, activationEffect: "none" as const };
  return { workPack, contract: { ...contractBody, contractDigest: sdkSemanticDigest(contractBody) } };
}

function productionCandidate(root: string, source: ReturnType<typeof upstream>) {
  mkdirSync(root, { recursive: true });
  const tenantId = "cf058Tenant", journeyId = "cf058Journey", boardId = "cf058Board", material = cf053UpstreamSource(source.workPack, source.contract, tenantId, journeyId), reader: ProviderWorkJourneyReader = { read: () => structuredClone(material.snapshot), events: () => structuredClone(material.events) }, statePath = join(root, "provider.sqlite"), coordinator = createProviderWorkEvidenceCoordinator(statePath), board = createCoordinatedProviderWorkBoard({ statePath, sources: reader, coordinator, now: () => NOW });
  const start: ProviderWorkBoardInput = { schemaVersion: "1.2", boardId, tenantId, providerId: source.workPack.providerId, journeyId, originMode: "cf041-progressive", importedStage: "cf041-semantic-review", importedSourceEventHeadDigest: material.snapshot.eventHeadDigest!, expectedJourneyDigest: material.snapshot.journeyDigest, expectedSourceIdentityDigest: material.snapshot.sourceIdentityDigest, expectedSourceEventStateDigest: providerWorkBoardDigest({ eventCount: material.snapshot.eventCount, eventHeadDigest: material.snapshot.eventHeadDigest! }), createdAt: NOW };
  const started = board.start(start), reuse = prepareProviderEvidenceReuse({ reader, board: started, now: NOW }); applyProviderEvidenceReuse({ board, reader, coordinator, plan: reuse, now: NOW });
  const workspaceTrustRoot = join(root, "workspace-trust"), registryRoot = join(root, "registry"), derived = deriveCf053ProviderNeutralContract({ board, coordinator, reader, boardId, tenantId, trustedDeployment: { tenantId, targetAlias: TARGET, policyVersion: "cf058_policy_v1", workspaceTrustRootDirectory: workspaceTrustRoot } }), registry = new Cf053ContentAddressedCandidateRegistry(registryRoot), candidate = registry.acquire(derived, NOW);
  return { candidate, coordinator, registryRoot, workspaceTrustRoot };
}

describe("CF-058 opaque causal HTTP bridge", () => {
  it("joins the exact production CF-053, CF-036 and reviewed HTTP lineage into one opaque digest", () => {
    const root = mkdtempSync(join(tmpdir(), "cf058-causal-bridge-"));
    try {
      const factory = factoryResult(), source = upstream(factory), production = productionCandidate(root, source), joined = joinCf058OpaqueCausalHttpBridge({ candidate: production.candidate, workPack: source.workPack, factoryResult: factory });
      expect(joined.receipt).toMatchObject({ state: "causal-lineage-joined-nonactivating", candidateDigest: production.candidate.candidateDigest, cf036WorkPackDigest: source.workPack.workPackDigest, factoryResultDigest: factory.resultDigest, actionScope: ACTION_SCOPE, observerScope: OBSERVER_SCOPE, executionAuthorityEffect: "none", activationEffect: "none" });
      const { bridgeDigest, ...body } = joined.receipt; expect(bridgeDigest).toBe(cf058CausalBridgeDigest(body)); expect(joined.handle).toEqual({ bridgeDigest }); expect(Object.isFrozen(joined.handle)).toBe(true);
      expect(joined.receipt.reviewedMethodIdentities.map((item) => item.role).sort()).toEqual(["action", "independent-observer", "no-write-probe", "reconciliation-readback"]);
      expect(() => joinCf058OpaqueCausalHttpBridge({ candidate: { ...production.candidate }, workPack: source.workPack, factoryResult: factory })).toThrow(/opaque production-derived candidate/i);
      expect(() => compileCf058AuthorityEnforcedReviewedHttpBindings({ factoryResult: factory, causalBridge: { ...joined.handle } } as never)).toThrow(/exact opaque causal bridge/i);
      expect(() => compileCf058AuthorityEnforcedReviewedHttpBindings({ factoryResult: factory, causalBridge: joined.handle } as never)).toThrow(/authority-enforced HTTP compilation requires/i);
      closeProviderWorkEvidenceCoordinator(production.coordinator);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it("fails closed on cross-factory lineage and credential-boundary substitution", () => {
    const root = mkdtempSync(join(tmpdir(), "cf058-causal-attacks-"));
    try {
      const factory = factoryResult(), source = upstream(factory), production = productionCandidate(root, source);
      const wrongPack = structuredClone(source.workPack); wrongPack.factoryResultDigest = digest("other-factory"); const { workPackDigest: _old, ...wrongBody } = wrongPack; wrongPack.workPackDigest = sdkWorkPackDigest(wrongBody);
      expect(() => joinCf058OpaqueCausalHttpBridge({ candidate: production.candidate, workPack: wrongPack, factoryResult: factory })).toThrow(/CF-036|factory-result|lineage/i);
      const conflated = structuredClone(factory); conflated.observerBinding!.credentialAlias = conflated.actionBinding!.credentialAlias; const { declarationDigest: _declaration, ...observerBody } = conflated.observerBinding!; conflated.observerBinding!.declarationDigest = digest(observerBody); const { resultDigest: _result, ...resultBody } = conflated; conflated.resultDigest = digest(resultBody);
      const conflatedSource = upstream(conflated), conflatedProduction = productionCandidate(join(root, "conflated"), conflatedSource);
      expect(() => joinCf058OpaqueCausalHttpBridge({ candidate: conflatedProduction.candidate, workPack: conflatedSource.workPack, factoryResult: conflated })).toThrow(/credential boundaries are conflated/i);
      closeProviderWorkEvidenceCoordinator(conflatedProduction.coordinator);
      closeProviderWorkEvidenceCoordinator(production.coordinator);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });

  it("reopens one exact retained production candidate after restart and rejects durable identity tamper", () => {
    const root = mkdtempSync(join(tmpdir(), "cf058-durable-reopen-"));
    try {
      const factory = factoryResult(), source = upstream(factory), production = productionCandidate(root, source);
      const reopened = reopenCf053DerivedContractFromDurableCandidate({ registryRootDirectory: production.registryRoot, candidateDigest: production.candidate.candidateDigest, workspaceTrustRootDirectory: production.workspaceTrustRoot });
      const retained = new Cf053ContentAddressedCandidateRegistry(production.registryRoot).acquire(reopened, NOW);
      expect(retained).toMatchObject({ candidateDigest: production.candidate.candidateDigest, source: "retained" });
      expect(() => reopenCf053DerivedContractFromDurableCandidate({ registryRootDirectory: production.registryRoot, candidateDigest: "0".repeat(64), workspaceTrustRootDirectory: production.workspaceTrustRoot })).toThrow(/exactly one retained candidate/i);

      const rootPath = join(production.workspaceTrustRoot, "cf053-workspace-trust-root.json"), originalRoot = readFileSync(rootPath, "utf8"), mutatedRoot = JSON.parse(originalRoot) as Record<string, unknown>;
      mutatedRoot.authorityContextDigest = "1".repeat(64); writeFileSync(rootPath, JSON.stringify(mutatedRoot));
      expect(() => reopenCf053DerivedContractFromDurableCandidate({ registryRootDirectory: production.registryRoot, candidateDigest: production.candidate.candidateDigest, workspaceTrustRootDirectory: production.workspaceTrustRoot })).toThrow(/workspace issuer/i);
      writeFileSync(rootPath, originalRoot);

      const contractPath = join(production.registryRoot, production.candidate.candidateDigest, "contract.json"), originalContract = readFileSync(contractPath, "utf8"), mutatedContract = JSON.parse(originalContract) as Record<string, unknown>;
      mutatedContract.targetAlias = "substituted_target"; writeFileSync(contractPath, JSON.stringify(mutatedContract));
      expect(() => reopenCf053DerivedContractFromDurableCandidate({ registryRootDirectory: production.registryRoot, candidateDigest: production.candidate.candidateDigest, workspaceTrustRootDirectory: production.workspaceTrustRoot })).toThrow(/bytes or contract were tampered/i);
      writeFileSync(contractPath, originalContract);
      closeProviderWorkEvidenceCoordinator(production.coordinator);
    } finally { rmSync(root, { recursive: true, force: true }); }
  });
});
