import{describe,expect,it}from"vitest";
import{performance}from"node:perf_hooks";
import{CUSTOMER_LOCAL_RESOURCE_LIMITS,assertBoundedString,assertBoundedValue,assertUniqueBoundedStrings,redactResourceError}from"../src/product/customer-local-resource-bounds.js";
import{providerWorkBoardDigest}from"../src/product/customer-local-provider-work-board.js";
import{onboardingJourneyDigest}from"../src/product/customer-local-onboarding-journey.js";

function nested(depth:number){let value:unknown="leaf";for(let index=0;index<depth;index++)value={value};return value;}
function rejection(operation:()=>unknown){const start=performance.now();expect(operation).toThrow();return performance.now()-start;}

describe("CF-049 customer-local hostile-input bounds",()=>{
 it("uses exact serialized UTF-8 bytes, including JSON escaping and punctuation",()=>{const value={escaped:"\\\"\n".repeat(50)};expect(()=>assertBoundedValue(value,"escaped",{maxBytes:JSON.stringify(value).length-1,maxDepth:8,maxNodes:128,maxStringBytes:10_000,maxArrayItems:128,maxObjectProperties:128})).toThrow(/serialized UTF-8 byte/i);expect(assertBoundedValue(value,"escaped",{maxBytes:Buffer.byteLength(JSON.stringify(value)),maxDepth:8,maxNodes:128,maxStringBytes:10_000,maxArrayItems:128,maxObjectProperties:128})).toBe(value);});
 it("rejects deep nesting, array/property bombs, huge strings, malformed Unicode and duplicate identities quickly",()=>{const latencies=[rejection(()=>assertBoundedValue(nested(40),"deep")),rejection(()=>assertBoundedValue(new Array(CUSTOMER_LOCAL_RESOURCE_LIMITS.maxArrayItems+1).fill(0),"array")),rejection(()=>assertBoundedValue(Object.fromEntries(Array.from({length:CUSTOMER_LOCAL_RESOURCE_LIMITS.maxObjectProperties+1},(_,i)=>[`x${i}`,i])),"object")),rejection(()=>assertBoundedString("x".repeat(CUSTOMER_LOCAL_RESOURCE_LIMITS.maxStringBytes+1),"string")),rejection(()=>assertBoundedString("\ud800","encoding")),rejection(()=>assertUniqueBoundedStrings(["same","same"],"identities",10))];expect(Math.max(...latencies)).toBeLessThan(500);});
 it("guards onboarding and provider-work canonicalization before recursive stack exhaustion",()=>{expect(()=>onboardingJourneyDigest(nested(1_000))).toThrow(/nesting-depth/i);expect(()=>providerWorkBoardDigest({items:new Array(3_000).fill("x")})).toThrow(/array-item/i);});
 it("rejects cycles, proxies and accessors without invoking hostile accessors, while allowing shared acyclic values",()=>{const cyclic:{self?:unknown}={};cyclic.self=cyclic;expect(()=>assertBoundedValue(cyclic,"cycle")).toThrow(/cyclic/i);const shared={safe:true};expect(assertBoundedValue({left:shared,right:shared},"shared")).toMatchObject({left:{safe:true},right:{safe:true}});expect(()=>assertBoundedValue(new Proxy({safe:true},{}),"proxy")).toThrow(/proxy/i);let invoked=false;const accessor={};Object.defineProperty(accessor,"secret",{enumerable:true,get(){invoked=true;for(;;){/* unreachable if fail-closed */}}});expect(()=>assertBoundedValue(accessor,"accessor")).toThrow(/accessor/i);expect(invoked).toBe(false);});
 it("inspects every own array descriptor before JSON serialization and never invokes hostile toJSON accessors",()=>{let invoked=false;const value:unknown[]=["safe"];Object.defineProperty(value,"toJSON",{enumerable:false,get(){invoked=true;for(;;){/* unreachable if descriptor validation is complete */}}});expect(()=>assertBoundedValue(value,"array accessor")).toThrow(/accessor/i);expect(invoked).toBe(false);const extra:unknown[]=[];Object.defineProperty(extra,"metadata",{value:"hidden",enumerable:false});expect(()=>assertBoundedValue(extra,"array property")).toThrow(/non-index array property/i);});
 it("redacts secret-shaped input from bounded errors",()=>{expect(redactResourceError(new Error("token=CF_CANARY_PRIVATE_VALUE rejected"))).not.toContain("CF_CANARY_PRIVATE_VALUE");});
});
