import{cpSync,mkdtempSync,readFileSync,rmSync,writeFileSync}from"node:fs";
import{tmpdir}from"node:os";
import{join}from"node:path";
import{fileURLToPath}from"node:url";
import{afterEach,describe,expect,it}from"vitest";
import{runMixedFamilyGoal}from"../src/product/mixed-family-goal-execution.js";
const validation=fileURLToPath(new URL("../validation/cf-033-mixed-family-goal-v1/",import.meta.url)),cf031=fileURLToPath(new URL("../validation/cf-031-family-routing-benchmark-v1/",import.meta.url)),cf032=fileURLToPath(new URL("../validation/cf-032-runtime-family-conformance-v1/",import.meta.url));const roots:string[]=[];afterEach(()=>{for(const r of roots.splice(0))rmSync(r,{recursive:true,force:true})});
async function run(){const root=mkdtempSync(join(tmpdir(),"cf033-"));roots.push(root);return runMixedFamilyGoal({directory:validation,workRoot:root,cf031Directory:cf031,cf032Directory:cf032})}
describe("CF-033 sealed mixed-family broad goal",()=>{
  it("executes document, message and database through native isolated evidence then resumes parent once",async()=>{const r=await run();expect(r).toMatchObject({status:"completed",effects:{proposals:3,manifests:3,writes:3,retries:0,recoveries:3,resumptions:3,reuse:3,quarantines:0,parentResumptions:1},faults:{attempted:12,blocked:12},fixedBaseline:{routeMatches:3,routeCount:3},executionBoundary:"one-fictional-sealed-goal",modelCalls:0,paidSpendUsd:0});expect(r.items.map(x=>x.familyId)).toEqual(["pinned-document","signed-message","scoped-database"]);expect(r.items.every(x=>x.claimsIsolated)).toBe(true);expect(r.lineage).toHaveLength(3)});
  it("uses constructible, trusted-existing and retained routes without treating conformance as outcome proof",async()=>{const r=await run();expect(r.routes.map(x=>[x.familyId,x.source])).toEqual([["pinned-document","constructible"],["signed-message","trusted-existing"],["scoped-database","retained"]]);for(const item of r.items){const route=r.routes.find(x=>x.familyId===item.familyId)!;expect(item.observationDigest).not.toBe(route.conformanceReceiptDigest);expect(item.recoveryDigest).not.toBe(route.conformanceReceiptDigest)}});
  it("binds the credential continuation to the unchanged plan and reconciles lost response after restart",async()=>{const r=await run();expect(r.credentialStop).toMatchObject({workItemId:"message-item",resumedWithoutReplan:true});expect(r.credentialStop.stopDigest).not.toBe(r.credentialStop.continuationDigest);expect(r.items.find(x=>x.familyId==="pinned-document")?.reconciledLostResponse).toBe(true);expect(r.planDigest).toBe("3830fac5f132df8f6f9ebb5f59f9a5c10adadb319ae6457ce0389c41f9fbb869")});
  it("is deterministic across fresh isolated executions",async()=>{const a=await run(),b=await run();expect(b.receiptDigest).toBe(a.receiptDigest);expect(b.aggregateEvidenceDigest).toBe(a.aggregateEvidenceDigest)});
  it("fails closed if the frozen ordinary goal changes",async()=>{const root=mkdtempSync(join(tmpdir(),"cf033-seal-"));roots.push(root);cpSync(validation,root,{recursive:true});const p=join(root,"goal.json"),g=JSON.parse(readFileSync(p,"utf8"));g.ordinaryGoal="changed";writeFileSync(p,JSON.stringify(g));await expect(runMixedFamilyGoal({directory:root,workRoot:join(root,"work"),cf031Directory:cf031,cf032Directory:cf032})).rejects.toThrow(/drifted/)});
});
