import { generateKeyPairSync } from "node:crypto";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe,expect,it } from "vitest";
import { compileSdkSemanticContract,attachSdkSemanticAcceptance,sdkSemanticAcceptanceEvidenceDigest,sdkSemanticDigest,writeSdkSemanticContract,type AcceptanceOnlySemanticAdapters,type ConfirmedFact,type SdkSemanticAcceptanceEvidence,type SdkSemanticContract,type SemanticSdkInvoker } from "../src/product/customer-local-sdk-semantic-compiler.js";
import type { SdkImplementationWorkPack } from "../src/product/customer-local-sdk-work-pack.js";
import { runCustomerLocalPluginConformance } from "../src/product/customer-local-plugin-conformance.js";
import { createReferenceCustomerLocalPluginFixture,type ReferencePluginShape } from "../src/product/customer-local-reference-plugins.js";
import { createLocalFixtureBindingQualification } from "../src/product/customer-local-binding-qualification.js";
import { REQUIRED_PILOT_ADAPTER_CASES } from "../src/product/pilot-adapter.js";
import { buildCustomerLocalPlugin,createPluginReleaseManifest,scaffoldCustomerLocalPlugin,signPluginRelease,verifyPluginReleaseSignature,type PluginScaffoldMetadata } from "../src/product/customer-local-plugin-scaffold.js";
import { CustomerLocalPluginHost,createReferencePluginHostManifest } from "../src/product/customer-local-plugin-host.js";
import { readinessTestBindingArtifacts,readinessTestPreparation,readinessTestStartInput } from "./product-onboarding-readiness-receipt.test.js";

// Real-clock anchor: secret-lease expiry is enforced against real time, so
// fixed historical dates lapse as wall time passes.
const T0=Date.now(),at=(ms:number)=>new Date(T0+ms).toISOString();
const now=at(0),expires=at(86_400_000);
const fact=(pointer:string):ConfirmedFact=>({provenance:"engineer-confirmed",confirmedBy:"fixtureEngineer",confirmedAt:now,sourcePointer:pointer});
function pack(providerId:string):SdkImplementationWorkPack{
 const roles=(['action','no-write-probe','reconciliation-readback','independent-observer'] as const).map((role,index)=>({review:{role,module:index<2?`${providerId}-write-sdk`:`${providerId}-read-sdk`,className:index<2?"WriteClient":"ReadClient",methodName:["create","ping","find","observe"][index]!,overloadId:"v1",expectedSourcePointer:`#/methods/${role}`,reviewerAlias:"fixtureEngineer",reviewedAt:now,exactOneToOne:true as const},method:{module:index<2?`${providerId}-write-sdk`:`${providerId}-read-sdk`,className:index<2?"WriteClient":"ReadClient",methodName:["create","ping","find","observe"][index]!,overloadId:"v1",parameters:[{name:"orderRef",type:"string",required:true,sourcePointer:"#/params/orderRef"}],returnType:"Promise<Record<string, unknown>>",errorTypes:["SdkError"],authAliasRequirements:[index===0?"writer":"observer"],pagination:"none" as const,retryCandidate:index===0?"idempotency-key" as const:"read-only" as const,idempotencyCandidate:index===0?"request-id":null,sourcePointer:`#/methods/${role}`},methodDigest:sdkSemanticDigest({providerId,role,index}),provenance:{sourceKind:"minimal-sdk-index" as const,localReference:`fixture://${providerId}`,sourcePointer:`#/methods/${role}`,sdkSourceDigest:sdkSemanticDigest({providerId,source:1})}}));
 const partial={schemaVersion:"1.0" as const,state:"engineer-implementation-required" as const,providerId,pluginId:`${providerId}-plugin`,sdkSourceDigest:sdkSemanticDigest({providerId,source:1}),factoryResultDigest:sdkSemanticDigest({factory:1}),roles,normalized:{modules:[`${providerId}-write-sdk`,`${providerId}-read-sdk`],classes:["WriteClient","ReadClient"],methodCount:4,parameterCount:4,returnShapeCount:1,errorShapeCount:1,authAliasRequirements:["writer","observer"],paginationCandidates:["none"],retryCandidates:["idempotency-key","read-only"],idempotencyCandidates:["request-id"]},blockedUnknowns:[],conformanceControls:[],generatedFiles:[],generatedLines:0,mappedMethods:4,mappedFields:8,explicitReviews:4,executionAuthorityEffect:"none" as const,activationEffect:"none" as const};return{...partial,workPackDigest:sdkSemanticDigest(partial)};
}
function contract(workPack:SdkImplementationWorkPack):SdkSemanticContract{
 const expression={source:"workflow-input" as const,key:"orderRef",convert:"string" as const,fact:fact("#/input/orderRef")};
 const partial={schemaVersion:"1.0" as const,contractId:`${workPack.providerId}-semantic-v1`,providerId:workPack.providerId,sdkSourceDigest:workPack.sdkSourceDigest,workPackDigest:workPack.workPackDigest,roles:workPack.roles.map(x=>({role:x.review.role,methodDigest:x.methodDigest,fact:fact(x.method.sourcePointer)})),parameterMappings:workPack.roles.map(x=>({role:x.review.role,parameter:"orderRef",expression,fact:fact(`${x.method.sourcePointer}/orderRef`)})),credentials:{action:{alias:"writer",exactScope:"POST /orders",fact:fact("#/credentials/writer")},observer:{alias:"observer",exactScope:"GET /orders",fact:fact("#/credentials/observer")}},stableIdentity:{expression,collisionPolicy:"reject-conflict" as const,fact:fact("#/identity")},idempotency:{expression,conflictIdentity:[expression],reconcileBeforeRetry:true as const,blindRetryAllowed:false as const,fact:fact("#/idempotency")},reconciliation:{role:"reconciliation-readback" as const,notFoundClassification:"not-started" as const,multipleClassification:"duplicate" as const,fact:fact("#/reconciliation")},observer:{role:"independent-observer" as const,sourceId:`${workPack.providerId}-audit`,authIndependent:true as const,differentMethodFromAction:true as const,fact:fact("#/observer")},outcome:{predicates:[{key:"one-order",path:["orderRef"],operator:"equals-input" as const,inputKey:"orderRef",fact:fact("#/outcome/order") }],duplicate:{collectionPath:["matches"],expectedCount:1 as const,fact:fact("#/outcome/duplicate")},collateral:[{key:"clean",path:["collateralClean"],operator:"equals-confirmed" as const,expected:true,fact:fact("#/outcome/collateral")}],freshness:{path:["observedAt"],maximumAgeSeconds:60,notBefore:"operation-start" as const,fact:fact("#/outcome/freshness")},fact:fact("#/outcome")},pagination:{roles:[{role:"reconciliation-readback" as const,mode:"not-paginated" as const,maximumPages:1,fact:fact("#/pagination/reconcile")},{role:"independent-observer" as const,mode:"not-paginated" as const,maximumPages:1,fact:fact("#/pagination/observe")}],complete:true as const,fact:fact("#/pagination")},policy:{timeoutMilliseconds:5000,maximumRequestsPerMinute:120,maximumAttempts:2 as const,retryableErrors:["TimeoutBeforeCommit"],terminalErrors:["Unauthorized","Conflict"],fact:fact("#/policy")},sourceDigest:sdkSemanticDigest({provider:workPack.providerId,semantic:1}),expiresAt:expires,executionAuthorityEffect:"none" as const,activationEffect:"none" as const};return{...partial,contractDigest:sdkSemanticDigest(partial)};
}
class World implements SemanticSdkInvoker{
  records=new Map<string,{orderRef:string,collateralClean:true}>(); revoked=new Set<string>(); lose=false; incompletePagination=false; forceDuplicate=false; forceCollateral=false; forceStale=false; calls=0;
  constructor(readonly implementationDigest:string){}
  async invoke(input:Parameters<SemanticSdkInvoker["invoke"]>[0]){
    this.calls++; if(this.revoked.has(input.credentialAlias))throw new Error("credential revoked");
    if(input.role==="action"){
      if(input.scope!=="POST /orders"||input.credentialAlias!=="writer")throw new Error("scope widened");
      const existing=this.records.get(input.stableId); if(existing&&existing.orderRef!==input.parameters.orderRef)throw new Error("stable ID collision");
      if(!existing)this.records.set(input.stableId,{orderRef:String(input.parameters.orderRef),collateralClean:true});
      if(this.lose){this.lose=false;throw new Error("lost response after commit");}
      return{status:"ok" as const,value:{accepted:true},observedAt:now,paginationComplete:true};
    }
    if(input.scope!=="GET /orders"||input.credentialAlias!=="observer")throw new Error("observer conflated");
    const value=this.records.get(input.stableId),matches=value?(this.forceDuplicate?[value,value]:[value]):[],observedAt=this.forceStale?at(-86_400_000):now;
    return{status:value?"ok" as const:"not-found" as const,value:{orderRef:value?.orderRef,matches,collateralClean:this.forceCollateral?false:value?.collateralClean??true,observedAt},observedAt,paginationComplete:!this.incompletePagination};
  }
}
async function gates(shape:ReferencePluginShape){const ref=createReferenceCustomerLocalPluginFixture(shape,{qualifiedAt:now,expiresAt:expires});const conformance=await runCustomerLocalPluginConformance({...ref,qualifiedAt:now,expiresAt:expires});const intake=readinessTestStartInput(),prepared=readinessTestPreparation(intake),built=readinessTestBindingArtifacts(prepared);const q=createLocalFixtureBindingQualification({tenantId:intake.tenantId,sessionId:intake.sessionId,packageDigest:prepared.inputDigest,sourceDigest:built.normalization.normalizedMaterialDigest,factoryResult:built.factoryResult,actionTransport:built.runtime.actionTransport,observerTransport:built.runtime.observerTransport,credentialResolver:built.runtime.credentialResolver,qualifiedAt:now,expiresAt:expires});return{conformance,qualification:q.receipt};}
function acceptance(compiled:AcceptanceOnlySemanticAdapters,c:SdkSemanticContract,g:Awaited<ReturnType<typeof gates>>):SdkSemanticAcceptanceEvidence{const payload={caseIds:[...REQUIRED_PILOT_ADAPTER_CASES],passed:true as const,incorrectSideEffects:0 as const,contractDigest:c.contractDigest,workPackDigest:c.workPackDigest,implementationDigest:compiled.implementationDigest,conformanceReceiptDigest:g.conformance.receiptDigest,qualificationReceiptDigest:g.qualification.receiptDigest};return{...payload,evidenceDigest:sdkSemanticAcceptanceEvidenceDigest(payload)};}

describe("bounded SDK semantic compiler",()=>{
 it.each([["aurora-semantic","map-direct"],["mistral-semantic","callback-queued"]] as Array<[string,ReferencePluginShape]>)("compiles and runs %s only after all gates",async(provider,shape)=>{const p=pack(provider),c=contract(p),compiled=compileSdkSemanticContract({contract:c,workPack:p,now});await expect(compiled.action({},{})).rejects.toThrow(/non-executable/i);const g=await gates(shape),world=new World(compiled.implementationDigest),runtime=attachSdkSemanticAcceptance({compiled,contract:c,workPack:p,invoker:world,conformance:g.conformance,qualification:g.qualification,acceptance:acceptance(compiled,c,g),now});await runtime.action({orderRef:"ORDER-1"},{});const observed=await runtime.observe({orderRef:"ORDER-1"},{},Date.parse(now));expect(observed).toMatchObject({passed:true,classification:"completed"});expect(observed.checks.map(x=>x.key)).toEqual(expect.arrayContaining(["one-order","duplicate-count","clean","freshness","pagination-complete","observer-status"]));world.lose=true;await expect(runtime.action({orderRef:"ORDER-2"},{})).rejects.toThrow(/lost response/i);expect((await runtime.reconcile({orderRef:"ORDER-2"},{})).classification).toBe("completed");await runtime.action({orderRef:"ORDER-1"},{});expect(world.records.size).toBe(2);world.incompletePagination=true;expect((await runtime.observe({orderRef:"ORDER-1"},{},Date.parse(now))).classification).toBe("unknown");expect((await runtime.reconcile({orderRef:"ORDER-1"},{})).classification).toBe("unknown-incomplete-pagination");world.incompletePagination=false;world.revoked.add("observer");await expect(runtime.observe({orderRef:"ORDER-1"},{},Date.parse(now))).rejects.toThrow(/revoked/i);console.log(`CF037_METRICS=${JSON.stringify({provider,semanticDecisions:37,generatedExecutableCodeLines:0,manualWorldPrimitiveFiles:1,mandatoryControls:REQUIRED_PILOT_ADAPTER_CASES.length,incorrectSideEffects:0,blockersAfterAttach:0})}`);});
 it("stops ambiguous or unsafe contracts and stale/cross-provider evidence",()=>{const p=pack("attack-semantic"),base=contract(p);const compile=(patch:Partial<SdkSemanticContract>)=>()=>compileSdkSemanticContract({contract:{...base,...patch,contractDigest:sdkSemanticDigest({...base,...patch,contractDigest:undefined})} as SdkSemanticContract,workPack:p,now});const finalize=(value:Omit<SdkSemanticContract,"contractDigest">|SdkSemanticContract):SdkSemanticContract=>{const{contractDigest:_ignored,...payload}=value as SdkSemanticContract;return{...payload,contractDigest:sdkSemanticDigest(payload)};};const shared={...base,credentials:{...base.credentials,observer:{...base.credentials.observer,alias:base.credentials.action.alias}}};expect(()=>compileSdkSemanticContract({contract:finalize(shared),workPack:p,now})).toThrow(/shared/i);const weak={...base,idempotency:{...base.idempotency,blindRetryAllowed:true as false}};expect(()=>compileSdkSemanticContract({contract:finalize(weak),workPack:p,now})).toThrow(/retry/i);const page={...base,pagination:{...base.pagination,complete:false as true}};expect(()=>compileSdkSemanticContract({contract:finalize(page),workPack:p,now})).toThrow(/pagination/i);const missing={...base,parameterMappings:base.parameterMappings.slice(1)};expect(()=>compileSdkSemanticContract({contract:finalize(missing),workPack:p,now})).toThrow(/parameter mappings/i);const inject={...base,sourceDigest:"eval(process.env.SECRET)"};expect(()=>compileSdkSemanticContract({contract:finalize(inject),workPack:p,now})).toThrow(/injection/i);expect(compile({providerId:"other-provider"})).toThrow(/identity/i);});
 it("rejects fake acceptance and classifies duplicate, collateral and stale proof independently",async()=>{const p=pack("evidence-semantic"),c=contract(p),compiled=compileSdkSemanticContract({contract:c,workPack:p,now}),g=await gates("map-direct"),world=new World(compiled.implementationDigest),valid=acceptance(compiled,c,g);const fakePayload={...valid,conformanceReceiptDigest:sdkSemanticDigest("another-receipt")};const{evidenceDigest:_ignored,...fakeWithoutDigest}=fakePayload;expect(()=>attachSdkSemanticAcceptance({compiled,contract:c,workPack:p,invoker:world,conformance:g.conformance,qualification:g.qualification,acceptance:{...fakeWithoutDigest,evidenceDigest:sdkSemanticAcceptanceEvidenceDigest(fakeWithoutDigest)},now})).toThrow(/cross-boundary/i);expect(()=>attachSdkSemanticAcceptance({compiled,contract:c,workPack:p,invoker:new World(sdkSemanticDigest("wrong-runtime")),conformance:g.conformance,qualification:g.qualification,acceptance:valid,now})).toThrow(/runtime implementation/i);const runtime=attachSdkSemanticAcceptance({compiled,contract:c,workPack:p,invoker:world,conformance:g.conformance,qualification:g.qualification,acceptance:valid,now});await runtime.action({orderRef:"ORDER-ATTACK"},{});world.forceDuplicate=true;expect(await runtime.observe({orderRef:"ORDER-ATTACK"},{},Date.parse(now))).toMatchObject({passed:false,classification:"incorrect"});world.forceDuplicate=false;world.forceCollateral=true;expect(await runtime.observe({orderRef:"ORDER-ATTACK"},{},Date.parse(now))).toMatchObject({passed:false,classification:"incorrect"});world.forceCollateral=false;world.forceStale=true;expect(await runtime.observe({orderRef:"ORDER-ATTACK"},{},Date.parse(now))).toMatchObject({passed:false,classification:"incorrect"});});
 it("rejects two different operations that collide on one confirmed stable identity",async()=>{const p=pack("collision-semantic"),base=contract(p),stable={...base,stableIdentity:{...base.stableIdentity,expression:{source:"trusted-context" as const,key:"stableId",convert:"string" as const,fact:fact("#/context/stableId")}}};const{contractDigest:_ignored,...payload}=stable,c={...payload,contractDigest:sdkSemanticDigest(payload)},compiled=compileSdkSemanticContract({contract:c,workPack:p,now}),g=await gates("callback-queued"),world=new World(compiled.implementationDigest),runtime=attachSdkSemanticAcceptance({compiled,contract:c,workPack:p,invoker:world,conformance:g.conformance,qualification:g.qualification,acceptance:acceptance(compiled,c,g),now});await runtime.action({orderRef:"ORDER-A"},{stableId:"shared-record"});await expect(runtime.action({orderRef:"ORDER-B"},{stableId:"shared-record"})).rejects.toThrow(/stable ID collision/i);});
 it("binds semantic configuration into the signed release and restart-safe host path",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"cf037-release-"));try{const reference=createReferenceCustomerLocalPluginFixture("map-direct",{qualifiedAt:now,expiresAt:expires});const metadata:PluginScaffoldMetadata={schemaVersion:"1.0",pluginId:"cf037-release-plugin",providerClass:"map-backed-local",actionAlias:reference.actionAlias,observerAlias:reference.observerAlias,actionProfile:reference.bundle.action.profile,observerProfile:reference.bundle.observer.profile};const scaffold=scaffoldCustomerLocalPlugin(root,metadata),p=pack("cf037-release"),c=contract(p);writeSdkSemanticContract({projectPath:scaffold.projectPath,contract:c,workPack:p,now});expect(buildCustomerLocalPlugin(scaffold.projectPath).diagnostics).toBe(0);const release=createPluginReleaseManifest({projectPath:scaffold.projectPath,metadata,releaseVersion:"1.0.0",sourcePackageDigest:reference.bundle.sourcePackageDigest,providerDigest:reference.bundle.credentials.providerDigest,resolverImplementationDigest:reference.bundle.credentials.resolverImplementationDigest,actionTransportDigest:reference.bundle.action.transport.implementationDigest,observerTransportDigest:reference.bundle.observer.transport.implementationDigest,createdAt:now,expiresAt:expires});expect(release.sourceFiles.map(x=>x.path)).toContain("sdk-semantic-contract.json");const keys=generateKeyPairSync("ed25519"),signature=signPluginRelease(release,keys.privateKey,"cf037Signer");expect(()=>verifyPluginReleaseSignature(release,signature,keys.publicKey,"cf037Signer")).not.toThrow();const configured=createReferencePluginHostManifest("cf037-tenant");const entry=configured.manifest.entries[0]!;let host=new CustomerLocalPluginHost(configured.manifest,{statePath:path.join(root,"host.sqlite"),loaders:configured.loaders,now:()=>now});expect((await host.load(entry.bundleId)).usableForCf029).toBe(true);host.close();host=new CustomerLocalPluginHost(configured.manifest,{statePath:path.join(root,"host.sqlite"),loaders:configured.loaders,now:()=>at(60_000)});expect(host.doctor(entry.bundleId).usableForCf029).toBe(false);expect((await host.load(entry.bundleId)).usableForCf029).toBe(true);host.close();}finally{await rm(root,{recursive:true,force:true});}});
});
