import{cpSync,mkdtempSync,readFileSync,rmSync,writeFileSync}from"node:fs";
import{tmpdir}from"node:os";
import{join}from"node:path";
import{fileURLToPath}from"node:url";
import{afterEach,describe,expect,it}from"vitest";
import{ConformanceReceiptStore,conformanceControlIds,evaluateRuntimeFamily,runRuntimeFamilyConformance}from"../src/product/runtime-family-conformance.js";
const directory=fileURLToPath(new URL("../validation/cf-032-runtime-family-conformance-v1/",import.meta.url)),pkg=JSON.parse(readFileSync(join(directory,"families.json"),"utf8"));const roots:string[]=[];afterEach(()=>{for(const r of roots.splice(0))rmSync(r,{recursive:true,force:true})});
describe("CF-032 runtime-family conformance and evidence isolation",()=>{
  it("passes 18 controls independently for CF-007/008/009 and rejects the fake family",()=>{const root=mkdtempSync(join(tmpdir(),"cf032-"));roots.push(root);const r=runRuntimeFamilyConformance(directory,join(root,"receipts.sqlite"));expect(r).toMatchObject({status:"passed",conformantFamilies:3,nonconformantFamilies:1,controlsPerConformantFamily:18,mutationsAttempted:27,mutationsBlocked:27,restartStable:true,originalAcceptanceReceiptsModified:0,modelCalls:0,paidSpendUsd:0});expect(r.families.slice(0,3).every(x=>x.status==="conformant"&&x.controls.length===18&&x.controls.every(c=>c.passed))).toBe(true);expect(r.families[3]).toMatchObject({familyId:"fake-nonconformant",status:"nonconformant",failedControls:conformanceControlIds})});
  it("does not accept action response, verifier, authority, manifest or family evidence substitution",()=>{const base=structuredClone(pkg.families[0].contract),other=pkg.families[1].contract;for(const mutate of[(x:any)=>{x.execution.actionResponseAcceptedAsProof=true;x.verifier.proofSources=["action-response"]},(x:any)=>{x.verifier.qualifiedFamilyId=other.familyId},(x:any)=>{x.authority=other.authority},(x:any)=>{x.manifestSchema=other.manifestSchema},(x:any)=>{x.provenance.familyEvidenceDigest=other.provenance.familyEvidenceDigest},(x:any)=>{x.verifier.mandatoryControls.pop()}]){const x=structuredClone(base);mutate(x);const r=evaluateRuntimeFamily({familyId:x.familyId,contract:x});expect(r.contractDigest).not.toBe(evaluateRuntimeFamily({familyId:base.familyId,contract:base}).contractDigest);if(x.execution.actionResponseAcceptedAsProof||x.verifier.qualifiedFamilyId!==x.familyId||x.verifier.mandatoryControls.length<11)expect(r.status).toBe("nonconformant")}});
  it("rebuilds route metadata from the isolated family receipt and rejects drift",()=>{const base=structuredClone(pkg.families[2].contract);expect(evaluateRuntimeFamily({familyId:base.familyId,contract:base}).controls.find(x=>x.controlId==="route-affordance-rebuild")?.passed).toBe(true);base.routeAffordance.outputArtifact="message-order";expect(evaluateRuntimeFamily({familyId:base.familyId,contract:base}).controls.find(x=>x.controlId==="route-affordance-rebuild")?.passed).toBe(false)});
  it("persists idempotently across restart and rejects conflicting family receipt replay",()=>{const root=mkdtempSync(join(tmpdir(),"cf032-store-"));roots.push(root);const path=join(root,"receipts.sqlite"),receipt=evaluateRuntimeFamily({familyId:pkg.families[0].contract.familyId,contract:pkg.families[0].contract});let store=new ConformanceReceiptStore(path);store.save(receipt);store.close();store=new ConformanceReceiptStore(path);expect(store.read(receipt.familyId)?.receiptDigest).toBe(receipt.receiptDigest);expect(()=>store.save({...receipt,receiptDigest:"f".repeat(64)})).toThrow(/Conflicting/);store.close()});
  it("fails closed on frozen package drift without touching original family receipts",()=>{const root=mkdtempSync(join(tmpdir(),"cf032-seal-"));roots.push(root);cpSync(directory,root,{recursive:true});const x=JSON.parse(readFileSync(join(root,"families.json"),"utf8"));x.frozenAt="changed";writeFileSync(join(root,"families.json"),JSON.stringify(x));expect(()=>runRuntimeFamilyConformance(root,join(root,"r.sqlite"))).toThrow(/drifted/);for(const prior of["cf-007-pinned-document-clean-family-v1","cf-008-signed-message-clean-family-v1","cf-009-scoped-database-clean-family-v1"])expect(()=>JSON.parse(readFileSync(join(directory,"..",prior,"campaign-seal.json"),"utf8"))).not.toThrow()});
});
