import{mkdtempSync,readFileSync,rmSync}from"node:fs";
import{tmpdir}from"node:os";
import{join}from"node:path";
import{fileURLToPath}from"node:url";
import{afterEach,describe,expect,it}from"vitest";
import{runScopedDatabaseCleanFamily}from"../src/product/scoped-database-clean-family.js";
const roots:string[]=[];const validation=new URL("../validation/cf-009-scoped-database-clean-family-v1/",import.meta.url);const family=JSON.parse(readFileSync(new URL("family.json",validation),"utf8")) as {contracts:Array<{contract:{transaction:{statements:Array<{kind:string}>;isolation:string};connection:{actionIdentity:string;observerIdentity:string}}}>;faults:string[]};
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})});
describe("CF-009 scoped database clean family",()=>{
  it("freezes materially different insert and row-scoped update contracts without callbacks",()=>{expect(family.contracts.map(x=>[x.contract.transaction.statements[0]!.kind,x.contract.transaction.isolation])).toEqual([["insert","serializable"],["update","repeatable-read"]]);expect(family.contracts.every(x=>x.contract.connection.actionIdentity!==x.contract.connection.observerIdentity)).toBe(true);expect(family.faults).toHaveLength(30)});
  it("runs both contracts through acceptance, recovery and lifecycle controls",async()=>{const root=mkdtempSync(join(tmpdir(),"cf009-"));roots.push(root);const r=await runScopedDatabaseCleanFamily(fileURLToPath(validation),root);expect(r).toMatchObject({status:"passed",caseCount:60,acceptanceCasesExecuted:20,extraCasesExecuted:40,effects:{proposals:40,statements:12,writes:12,retriesBlocked:6,recoveries:24,resumptions:12,reuse:12,quarantines:8,incorrectSideEffectsSurviving:0},composition:{handwrittenReusableSourceFiles:2,frozenDeclarativeContracts:2,frozenDeclarativeFaults:30,caseSpecificExecutableFilesAfterFreeze:0},modelCalls:0,paidSpendUsd:0});expect(r.cases.filter(x=>x.acceptanceCase)).toHaveLength(20)});
  it("fails closed for injection, drift, widened scope, mass operations and shared identities",async()=>{const root=mkdtempSync(join(tmpdir(),"cf009-block-"));roots.push(root);const r=await runScopedDatabaseCleanFamily(fileURLToPath(validation),root);const blocked=new Set(["schema-drift","migration-mismatch","query-injection","identifier-injection","parameter-injection","scope-widening","mass-update","mass-delete","shared-identity"]);expect(r.cases.filter(x=>blocked.has(x.fault)).every(x=>x.actualStatus==="blocked"&&x.proposals===0&&x.writes===0)).toBe(true);expect(r.cases.filter(x=>["busy","deadlock","timeout"].includes(x.fault)).every(x=>x.retriesBlocked===1&&x.writes===0)).toBe(true)});
  it("fails closed when frozen material differs from its seal",async()=>{const root=mkdtempSync(join(tmpdir(),"cf009-seal-"));roots.push(root);const copied=join(root,"validation"),work=join(root,"work");const{mkdirSync,writeFileSync}=await import("node:fs");mkdirSync(copied,{recursive:true});writeFileSync(join(copied,"family.json"),JSON.stringify({...family,frozenAt:"changed"}));writeFileSync(join(copied,"campaign-seal.json"),readFileSync(new URL("campaign-seal.json",validation)));await expect(runScopedDatabaseCleanFamily(copied,work)).rejects.toThrow(/seal failed/)})
});
