import{join,normalize,isAbsolute}from"node:path";
import{createOperatorReceipt,replayOperatorReceipt,type OperatorReceipt}from"./claims-isolated-operator-receipt.js";
import{CUSTOMER_LOCAL_RESOURCE_LIMITS,assertBoundedString,assertBoundedValue,assertUniqueBoundedStrings,boundedFileSize,readBoundedFile}from"./customer-local-resource-bounds.js";

type Options=Parameters<typeof createOperatorReceipt>[0];
interface ClaimsConfig{sourceArtifacts:Array<{domain:string;path:string;sha256:string}>;limitations:string[]}
const digest=/^[a-f0-9]{64}$/;

function preflight(options:Options){for(const value of[options.directory,options.repositoryRoot,options.workRoot,options.cf031Directory,options.cf032Directory,options.cf033Directory,options.cf044Directory,options.cf045Directory])assertBoundedString(value,"Claims replay path",1_024);boundedFileSize(join(options.directory,"config.json"),CUSTOMER_LOCAL_RESOURCE_LIMITS.claimsConfigBytes,"Claims replay config");boundedFileSize(join(options.directory,"seal.json"),CUSTOMER_LOCAL_RESOURCE_LIMITS.claimsSealBytes,"Claims replay seal");let config:ClaimsConfig;try{config=JSON.parse(readBoundedFile(join(options.directory,"config.json"),CUSTOMER_LOCAL_RESOURCE_LIMITS.claimsConfigBytes,"Claims replay config").toString("utf8")) as ClaimsConfig;}catch{throw new Error("Claims replay config is malformed or has invalid encoding.");}assertBoundedValue(config,"Claims replay config",{maxBytes:CUSTOMER_LOCAL_RESOURCE_LIMITS.claimsConfigBytes,maxDepth:12,maxNodes:4_096,maxStringBytes:8_192,maxArrayItems:CUSTOMER_LOCAL_RESOURCE_LIMITS.claimsSourceArtifacts,maxObjectProperties:64});if(!Array.isArray(config.sourceArtifacts)||config.sourceArtifacts.length<1||config.sourceArtifacts.length>CUSTOMER_LOCAL_RESOURCE_LIMITS.claimsSourceArtifacts)throw new Error("Claims replay source-artifact count is invalid.");const identities:string[]=[];for(const item of config.sourceArtifacts){assertBoundedString(item.domain,"Claims replay source domain",80);assertBoundedString(item.path,"Claims replay source path",500);if(isAbsolute(item.path)||normalize(item.path).startsWith("..")||!digest.test(item.sha256))throw new Error("Claims replay source artifact is cross-root or malformed.");identities.push(`${item.domain}:${item.path}`);boundedFileSize(join(options.repositoryRoot,item.path),CUSTOMER_LOCAL_RESOURCE_LIMITS.claimsSourceFileBytes,"Claims replay source artifact");}assertUniqueBoundedStrings(identities,"Claims replay source identities",CUSTOMER_LOCAL_RESOURCE_LIMITS.claimsSourceArtifacts,600);if(!Array.isArray(config.limitations)||config.limitations.length>128)throw new Error("Claims replay limitations exceed their count limit.");return config;}

export async function createBoundedOperatorReceipt(options:Options){preflight(options);const receipt=await createOperatorReceipt(options);assertBoundedValue(receipt,"Claims operator receipt",{maxBytes:CUSTOMER_LOCAL_RESOURCE_LIMITS.inputBytes,maxDepth:24,maxNodes:30_000,maxStringBytes:16_384,maxArrayItems:2_048,maxObjectProperties:256});return receipt;}
export async function replayBoundedOperatorReceipt(receipt:OperatorReceipt,options:Options){assertBoundedValue(receipt,"Claims replay receipt",{maxBytes:CUSTOMER_LOCAL_RESOURCE_LIMITS.inputBytes,maxDepth:24,maxNodes:30_000,maxStringBytes:16_384,maxArrayItems:2_048,maxObjectProperties:256});preflight(options);return replayOperatorReceipt(receipt,options);}
