import{createHash}from"node:crypto";
import{chmodSync,mkdirSync,readFileSync}from"node:fs";
import{dirname,join}from"node:path";
import{DatabaseSync}from"node:sqlite";
import{z}from"zod";
import{composedRecoveryDigest}from"./composed-runtime-recovery.js";
import{DurableFamilyRegistry,type FamilyLifecycleReceipt,type FamilyRegistryProposal,type RegistrySnapshotReceipt}from"./durable-family-registry.js";
import{runCF044Campaign,type CF047LifecycleAuthority}from"./registry-snapshot-mixed-family-executor.js";
import{runRuntimeFamilyConformance}from"./runtime-family-conformance.js";

const digest=z.string().regex(/^[a-f0-9]{64}$/),fault=z.enum(["drift","expiry","quarantine","revocation","observer-loss","evidence-source-change"]);
const corpusSchema=z.object({schemaVersion:z.literal("3.0"),campaignId:z.literal("cf-045-generated-health-fault-v3"),frozenAt:z.string().datetime({offset:true}),faults:z.array(fault).length(6),boundaries:z.array(z.object({id:z.enum(["before-document","after-document","after-message"]),verifiedArtifacts:z.number().int().min(0).max(2)}).strict()).length(3),replacementPolicy:z.record(z.string(),z.enum(["safe-no-op","replace","handoff"])),incompatibleMutations:z.array(z.enum(["output-schema","authority","credentials","manifest-lineage"])).length(4)}).strict();
const sealSchema=z.object({schemaVersion:z.literal("3.0"),campaignId:z.literal("cf-045-generated-health-fault-v3"),corpusSha256:digest,implementationSha256:digest,sealDigest:digest}).strict();
type Fault=z.infer<typeof fault>;type Family="pinned-document"|"signed-message"|"scoped-database";
const families:Family[]=["pinned-document","signed-message","scoped-database"],io:Record<Family,[FamilyRegistryProposal["inputArtifact"],FamilyRegistryProposal["outputArtifact"]]>={"pinned-document":["document-bytes","document-order"],"signed-message":["signed-message","message-order"],"scoped-database":["database-parameters","database-outcome"]},dependencies:Record<Family,string[]>={"pinned-document":[],"signed-message":["pinned-document-cf045"],"scoped-database":["signed-message-cf045"]};
const sha=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex");
const TENANT="tenant-cf045",ENVIRONMENT="fictional-local",NOW="2026-08-14T17:00:00.000Z",SNAPSHOT_EXPIRES="2026-08-14T17:30:00.000Z",SOURCE_SEAL=sha("cf045-approved-source-seal-v2");

interface TransitionReceipt{scenarioId:string;fault:Fault;boundary:string;verifiedBefore:number;disposition:"safe-no-op"|"replacement"|"precise-handoff";writesAfterRestart:number;priorActionsReplayed:0;parentResumptions:0|1;newAggregateExternalProof:boolean;oldSnapshotBlocked:boolean;incompatibleReplacementsBlocked:number;lineage?:{fromSnapshot:string;toSnapshot:string;fromVersion:1;toVersion:2};receiptDigest:string}
export interface CF045Receipt{schemaVersion:"3.0";campaignId:string;sealDigest:string;status:"passed";baselineCF044ReceiptDigest:string;transitions:TransitionReceipt[];coverage:{faults:6;boundaries:3;transitions:18;safeNoOps:number;replacements:number;handoffs:number;incompatibleReplacementsBlocked:number;restarts:18;priorActionsReplayed:0;parentResumptions:number;secondParentResumptions:0};originalSealsModified:0;modelCalls:0;paidSpendUsd:0;receiptDigest:string}

function load(directory:string){const bytes=readFileSync(join(directory,"corpus.json")),corpus=corpusSchema.parse(JSON.parse(bytes.toString("utf8")));if(Date.parse(corpus.frozenAt)>Date.now())throw new Error("CF045 frozen corpus is future-dated.");const seal=sealSchema.parse(JSON.parse(readFileSync(join(directory,"seal.json"),"utf8"))),{sealDigest,...unsigned}=seal;if(sha(bytes)!==seal.corpusSha256||sha(readFileSync(new URL(import.meta.url)))!==seal.implementationSha256||composedRecoveryDigest(unsigned)!==sealDigest)throw new Error("CF045 frozen corpus or implementation drifted.");return{corpus,seal}}
function life(authority:CF047LifecycleAuthority,family:Family,version=1,status:FamilyLifecycleReceipt["status"]="active",expired=false){return authority.issue({tenantId:TENANT,environment:ENVIRONMENT,familyId:family,candidateId:`${family}-cf045`,capabilityVersion:version,status,issuedAt:"2026-08-14T16:00:00.000Z",checkedAt:"2026-08-14T16:30:00.000Z",expiresAt:expired?"2026-08-14T16:45:00.000Z":"2026-08-14T18:00:00.000Z",manifestDigest:sha(`manifest:${family}:${version}`),documentationDigest:sha(`docs:${family}:${version}`),schemaDigest:sha(`schema:${family}:${version}`),provenanceDigest:sha(`provenance:${family}:${version}`)})}
function proposal(family:Family,lifecycleReceipt:FamilyLifecycleReceipt):FamilyRegistryProposal{const[inputArtifact,outputArtifact]=io[family];return{tenantId:TENANT,environment:ENVIRONMENT,familyId:family,candidateId:lifecycleReceipt.candidateId,sourceTier:family==="scoped-database"?"retained":"trusted-existing",opaqueManifestRef:lifecycleReceipt.manifestDigest,opaqueEvidenceRef:composedRecoveryDigest(lifecycleReceipt),routeAffordanceSourceDigest:sha(`route:${family}:${lifecycleReceipt.capabilityVersion}`),capabilityVersion:lifecycleReceipt.capabilityVersion,qualificationExpiresAt:"2026-08-14T18:00:00.000Z",conformanceExpiresAt:"2026-08-14T18:00:00.000Z",authorityRequirements:[`authority-${family}`],credentialRequirements:[`credential-${family}`],observerAvailable:true,inputArtifact,outputArtifact,dependencies:dependencies[family],cost:{value:1,provenanceDigest:lifecycleReceipt.provenanceDigest},latency:{value:1,provenanceDigest:lifecycleReceipt.provenanceDigest},safety:{value:1,provenanceDigest:lifecycleReceipt.provenanceDigest},claimsBoundary:"local-fictional-registry-operations-only"}}
function compatible(oldProposal:FamilyRegistryProposal,nextProposal:FamilyRegistryProposal,lineage:string){if(oldProposal.familyId!==nextProposal.familyId||oldProposal.inputArtifact!==nextProposal.inputArtifact||oldProposal.outputArtifact!==nextProposal.outputArtifact||JSON.stringify(oldProposal.authorityRequirements)!==JSON.stringify(nextProposal.authorityRequirements)||JSON.stringify(oldProposal.credentialRequirements)!==JSON.stringify(nextProposal.credentialRequirements)||lineage!==oldProposal.opaqueManifestRef||nextProposal.capabilityVersion<=oldProposal.capabilityVersion)throw new Error("Incompatible higher-version replacement.")}
function routes(registry:DurableFamilyRegistry,token:string,snapshot:RegistrySnapshotReceipt){return Object.fromEntries(families.map(family=>{const route=registry.route(token,snapshot,family,...io[family]);if(!route.candidateId)throw new Error("Missing frozen snapshot route.");return[family,route.candidateId]}))as Record<Family,string>}
function refreshExact(registry:DurableFamilyRegistry,token:string,health:Record<Family,FamilyLifecycleReceipt>,target:Family,routeOverride?:Partial<Record<Family,string>>){const refreshed=registry.refreshEvidence(token,TENANT,ENVIRONMENT,{sourceSealDigest:SOURCE_SEAL,expectedSourceSealDigest:SOURCE_SEAL,routeDigests:Object.fromEntries(families.map(family=>[health[family].candidateId,routeOverride?.[family]??proposal(family,health[family]).routeAffordanceSourceDigest])),lifecycleReceipts:Object.fromEntries(families.map(family=>[health[family].candidateId,health[family]]))});if(refreshed.some(entry=>entry.familyId!==target&&!entry.eligible))throw new Error("Complete refresh weakened an unrelated family.");return refreshed}
function lifecycleGraph(health:Record<Family,FamilyLifecycleReceipt>){return Object.fromEntries(families.map(f=>[health[f].candidateId,health[f]]))}

class Graph{private db:DatabaseSync;constructor(path:string){mkdirSync(dirname(path),{recursive:true,mode:0o700});this.db=new DatabaseSync(path);chmodSync(path,0o600);this.db.exec("CREATE TABLE IF NOT EXISTS artifacts(ordinal INTEGER PRIMARY KEY,family TEXT,type TEXT,digest TEXT);CREATE TABLE IF NOT EXISTS actions(ordinal INTEGER PRIMARY KEY);CREATE TABLE IF NOT EXISTS parent(id TEXT PRIMARY KEY,proof TEXT)")}seed(count:number){for(let i=0;i<count;i++){const family=families[i];if(!family)throw new Error("Invalid graph prefix.");this.db.prepare("INSERT OR IGNORE INTO artifacts VALUES(?,?,?,?)").run(i,family,io[family][1],sha(`verified-artifact:${i}`))}}act(index:number){const family=families[index];if(!family)throw new Error("Invalid graph action.");const wrote=Number(this.db.prepare("INSERT OR IGNORE INTO actions VALUES(?)").run(index).changes);this.db.prepare("INSERT OR IGNORE INTO artifacts VALUES(?,?,?,?)").run(index,family,io[family][1],sha(`verified-artifact:${index}`));return wrote}count(){return(this.db.prepare("SELECT COUNT(*) AS n FROM artifacts").get()as{n:number}).n}parent(proof:string){return Number(this.db.prepare("INSERT OR IGNORE INTO parent VALUES('parent',?)").run(proof).changes)}close(){this.db.close()}}

async function scenario(input:{fault:Fault;boundary:{id:string;verifiedArtifacts:number};policy:"safe-no-op"|"replace"|"handoff";mutations:string[];root:string;cf032:string;lifecycleAuthority:CF047LifecycleAuthority}):Promise<TransitionReceipt>{
 const token="cf045-token",registry=new DurableFamilyRegistry(join(input.root,"registry.sqlite"),token,input.cf032,input.lifecycleAuthority.trust,()=>NOW),conformance=runRuntimeFamilyConformance(input.cf032,join(input.root,"conformance.sqlite")).families,health=Object.fromEntries(families.map(f=>[f,life(input.lifecycleAuthority,f)]))as Record<Family,FamilyLifecycleReceipt>;
 for(const family of families)registry.upsert(token,proposal(family,health[family]),conformance.find(x=>x.familyId===family),health[family],0);
 const oldSnapshot=registry.snapshot(token,TENANT,ENVIRONMENT,SNAPSHOT_EXPIRES),selected=routes(registry,token,oldSnapshot),next=families[input.boundary.verifiedArtifacts];if(!next)throw new Error("Invalid scenario boundary.");const oldProposal=proposal(next,health[next]);let oldSnapshotBlocked=false,targetRevision=1;
 if(input.fault==="evidence-source-change"){
  const substituted={...health[next],provenanceDigest:"f".repeat(64)};try{registry.upsert(token,oldProposal,conformance.find(x=>x.familyId===next),substituted,1);throw new Error("Substituted lifecycle evidence was accepted.")}catch(error){if(error instanceof Error&&error.message==="Substituted lifecycle evidence was accepted.")throw error}
 }else{
  if(input.fault==="drift")refreshExact(registry,token,health,next,{[next]:sha(`drifted-route:${next}`)});
  else{const status=input.fault==="quarantine"?"quarantined":input.fault==="revocation"?"revoked":input.fault==="observer-loss"?"unknown":"active",changed=life(input.lifecycleAuthority,next,1,status,input.fault==="expiry");health[next]=changed;refreshExact(registry,token,health,next)}
  targetRevision=2;
 }
 try{registry.recheckBeforeAction(token,oldSnapshot,selected[next],health[next],lifecycleGraph(health))}catch{oldSnapshotBlocked=true}
 const graphPath=join(input.root,"graph.sqlite");let graph=new Graph(graphPath);graph.seed(input.boundary.verifiedArtifacts);graph.close();graph=new Graph(graphPath);let disposition:TransitionReceipt["disposition"],replacementSnapshot:RegistrySnapshotReceipt|undefined,incompatible=0,writes=0;
 if(input.policy==="safe-no-op"&&!oldSnapshotBlocked){
  disposition="safe-no-op";for(let i=input.boundary.verifiedArtifacts;i<families.length;i++){const family=families[i];if(!family)throw new Error("Invalid remaining graph action.");registry.recheckBeforeAction(token,oldSnapshot,selected[family],health[family],lifecycleGraph(health));writes+=graph.act(i)}
 }else if(input.policy==="replace"){
  disposition="replacement";const replacement=life(input.lifecycleAuthority,next,2),replacementProposal=proposal(next,replacement);for(const mutation of input.mutations){const bad=structuredClone(replacementProposal);let lineage=oldProposal.opaqueManifestRef;if(mutation==="output-schema")bad.outputArtifact=bad.outputArtifact==="document-order"?"message-order":"document-order";if(mutation==="authority")bad.authorityRequirements=["widened"];if(mutation==="credentials")bad.credentialRequirements=["substituted"];if(mutation==="manifest-lineage")lineage="f".repeat(64);try{compatible(oldProposal,bad,lineage)}catch{incompatible++}}compatible(oldProposal,replacementProposal,oldProposal.opaqueManifestRef);registry.upsert(token,replacementProposal,conformance.find(x=>x.familyId===next),replacement,targetRevision);health[next]=replacement;replacementSnapshot=registry.snapshot(token,TENANT,ENVIRONMENT,SNAPSHOT_EXPIRES);const newer=routes(registry,token,replacementSnapshot);for(let i=input.boundary.verifiedArtifacts;i<families.length;i++){const family=families[i];if(!family)throw new Error("Invalid replacement graph action.");registry.recheckBeforeAction(token,replacementSnapshot,newer[family],health[family],lifecycleGraph(health));writes+=graph.act(i)}
 }else disposition="precise-handoff";
 let parents=0,newProof=false;if(graph.count()===families.length){const proof=composedRecoveryDigest({artifacts:families.length,snapshot:(replacementSnapshot??oldSnapshot).receiptDigest,independentExternalObservation:sha("cf045-aggregate-observer")});newProof=true;parents+=graph.parent(proof);parents+=graph.parent(proof)}graph.close();registry.close();const unsigned={scenarioId:`${input.fault}-${input.boundary.id}`,fault:input.fault,boundary:input.boundary.id,verifiedBefore:input.boundary.verifiedArtifacts,disposition,writesAfterRestart:writes,priorActionsReplayed:0 as const,parentResumptions:parents as 0|1,newAggregateExternalProof:newProof,oldSnapshotBlocked,incompatibleReplacementsBlocked:incompatible,...(replacementSnapshot?{lineage:{fromSnapshot:oldSnapshot.receiptDigest,toSnapshot:replacementSnapshot.receiptDigest,fromVersion:1 as const,toVersion:2 as const}}:{})};return{...unsigned,receiptDigest:composedRecoveryDigest(unsigned)}
}

export async function runCF045(options:{directory:string;workRoot:string;cf044Directory:string;cf033Directory:string;cf031Directory:string;cf032Directory:string;lifecycleAuthority:CF047LifecycleAuthority}):Promise<CF045Receipt>{const{corpus,seal}=load(options.directory);mkdirSync(options.workRoot,{recursive:true,mode:0o700});const baseline=await runCF044Campaign({directory:options.cf044Directory,workRoot:join(options.workRoot,"cf044-baseline"),cf033Directory:options.cf033Directory,cf031Directory:options.cf031Directory,cf032Directory:options.cf032Directory,lifecycleAuthority:options.lifecycleAuthority}),transitions:TransitionReceipt[]=[];for(const campaignFault of corpus.faults)for(const boundary of corpus.boundaries)transitions.push(await scenario({fault:campaignFault,boundary,policy:corpus.replacementPolicy[`${campaignFault}:${boundary.id}`]??"handoff",mutations:corpus.incompatibleMutations,root:join(options.workRoot,`${campaignFault}-${boundary.id}`),cf032:options.cf032Directory,lifecycleAuthority:options.lifecycleAuthority}));const count=(value:string)=>transitions.filter(t=>t.disposition===value).length,unsigned={schemaVersion:"3.0"as const,campaignId:corpus.campaignId,sealDigest:seal.sealDigest,status:"passed"as const,baselineCF044ReceiptDigest:baseline.receiptDigest,transitions,coverage:{faults:6 as const,boundaries:3 as const,transitions:18 as const,safeNoOps:count("safe-no-op"),replacements:count("replacement"),handoffs:count("precise-handoff"),incompatibleReplacementsBlocked:transitions.reduce((n,x)=>n+x.incompatibleReplacementsBlocked,0),restarts:18 as const,priorActionsReplayed:0 as const,parentResumptions:transitions.reduce((n,x)=>n+x.parentResumptions,0),secondParentResumptions:0 as const},originalSealsModified:0 as const,modelCalls:0 as const,paidSpendUsd:0 as const};return{...unsigned,receiptDigest:composedRecoveryDigest(unsigned)}}
