import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join, resolve, sep } from "node:path";
import { assertBindingQualificationReceipt, type BindingQualificationReceipt } from "./customer-local-binding-qualification.js";
import { customerLocalPluginDigest, type CustomerLocalPluginConformanceReceipt } from "./customer-local-plugin-conformance.js";
import type { SdkImplementationWorkPack } from "./customer-local-sdk-work-pack.js";
import { REQUIRED_PILOT_ADAPTER_CASES } from "./pilot-adapter.js";

export const CUSTOMER_LOCAL_SDK_SEMANTIC_COMPILER_VERSION = "1.0" as const;
const identifier=/^[a-zA-Z][a-zA-Z0-9_.-]{1,119}$/;
const forbidden=/\b(?:eval|Function|require|import\s*\(|prototype|constructor|__proto__)\b|(?:bearer|password|secret|token|api[_ -]?key)\s*[:=]\s*[^\s,;}]+/i;
const canonical=(value:unknown):string=>{if(value===undefined)return"undefined";if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value!==null&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;return JSON.stringify(value);};
export const sdkSemanticDigest=(value:unknown)=>createHash("sha256").update(canonical(value)).digest("hex");
type Scalar=string|number|boolean|null;
export interface ConfirmedFact { provenance:"engineer-confirmed"|"owner-confirmed"; confirmedBy:string; confirmedAt:string; sourcePointer:string }
export interface ValueExpression { source:"workflow-input"|"trusted-context"; key:string; convert:"identity"|"string"|"number"|"boolean"; fact:ConfirmedFact }
export interface SemanticPredicate { key:string; path:string[]; operator:"exists"|"equals-input"|"equals-confirmed"|"count-equals"; inputKey?:string; expected?:Scalar|number; fact:ConfirmedFact }
export interface SdkSemanticContract {
 schemaVersion:"1.0"; contractId:string; providerId:string; sdkSourceDigest:string; workPackDigest:string;
 roles:Array<{role:"action"|"no-write-probe"|"reconciliation-readback"|"independent-observer";methodDigest:string;fact:ConfirmedFact}>;
 parameterMappings:Array<{role:"action"|"no-write-probe"|"reconciliation-readback"|"independent-observer";parameter:string;expression:ValueExpression;fact:ConfirmedFact}>;
 credentials:{action:{alias:string;exactScope:string;fact:ConfirmedFact};observer:{alias:string;exactScope:string;fact:ConfirmedFact}};
 stableIdentity:{expression:ValueExpression;collisionPolicy:"reject-conflict";fact:ConfirmedFact};
 idempotency:{expression:ValueExpression;conflictIdentity:Array<ValueExpression>;reconcileBeforeRetry:true;blindRetryAllowed:false;fact:ConfirmedFact};
 reconciliation:{role:"reconciliation-readback";notFoundClassification:"not-started";multipleClassification:"duplicate";fact:ConfirmedFact};
 observer:{role:"independent-observer";sourceId:string;authIndependent:true;differentMethodFromAction:true;fact:ConfirmedFact};
 outcome:{predicates:SemanticPredicate[];duplicate:{collectionPath:string[];expectedCount:1;fact:ConfirmedFact};collateral:SemanticPredicate[];freshness:{path:string[];maximumAgeSeconds:number;notBefore:"operation-start";fact:ConfirmedFact};fact:ConfirmedFact};
 pagination:{roles:Array<{role:"reconciliation-readback"|"independent-observer";mode:"not-paginated"|"complete-cursor";maximumPages:number;fact:ConfirmedFact}>;complete:true;fact:ConfirmedFact};
 policy:{timeoutMilliseconds:number;maximumRequestsPerMinute:number;maximumAttempts:1|2|3;retryableErrors:string[];terminalErrors:string[];fact:ConfirmedFact};
 sourceDigest:string; expiresAt:string; executionAuthorityEffect:"none"; activationEffect:"none"; contractDigest:string;
}
export interface SemanticSdkInvocation {role:SdkSemanticContract["roles"][number]["role"];methodDigest:string;parameters:Record<string,Scalar>;credentialAlias:string;scope:string;stableId:string;idempotencyKey:string;timeoutMilliseconds:number}
export interface SemanticSdkInvoker {implementationDigest:string;invoke(input:SemanticSdkInvocation):Promise<{status:"ok"|"not-found"|"error";value:unknown;observedAt:string;paginationComplete:boolean}>}
export interface AcceptanceOnlySemanticAdapters {schemaVersion:"1.0";state:"acceptance-only-non-executable";providerId:string;contractDigest:string;workPackDigest:string;implementationDigest:string;action(input:Record<string,unknown>,context:Record<string,unknown>):Promise<never>;probe(input:Record<string,unknown>,context:Record<string,unknown>):Promise<never>;reconcile(input:Record<string,unknown>,context:Record<string,unknown>):Promise<never>;observe(input:Record<string,unknown>,context:Record<string,unknown>):Promise<never>;executionAuthorityEffect:"none";activationEffect:"none"}
export interface ExecutableAcceptanceSemanticAdapters {state:"acceptance-attached";action(input:Record<string,unknown>,context:Record<string,unknown>):Promise<unknown>;probe(input:Record<string,unknown>,context:Record<string,unknown>):Promise<unknown>;reconcile(input:Record<string,unknown>,context:Record<string,unknown>):Promise<{classification:string;value:unknown}>;observe(input:Record<string,unknown>,context:Record<string,unknown>,operationStartedAt:number):Promise<{passed:boolean;classification:string;checks:Array<{key:string;passed:boolean}>;value:unknown}>}
export interface SdkSemanticAcceptanceEvidence {caseIds:string[];passed:true;incorrectSideEffects:0;contractDigest:string;workPackDigest:string;implementationDigest:string;conformanceReceiptDigest:string;qualificationReceiptDigest:string;evidenceDigest:string}
export const sdkSemanticAcceptanceEvidenceDigest=(input:Omit<SdkSemanticAcceptanceEvidence,"evidenceDigest">)=>sdkSemanticDigest(input);

function assertFact(f:ConfirmedFact){if(!identifier.test(f.confirmedBy)||!f.sourcePointer||Date.parse(f.confirmedAt)<=0)throw new Error("Semantic fact lacks exact confirmation/provenance.");}
function contractPayload(contract:SdkSemanticContract){const{contractDigest:_d,...payload}=contract;return payload;}
function assertContract(contract:SdkSemanticContract,pack:SdkImplementationWorkPack,now:string){
 if(contract.schemaVersion!=="1.0"||contract.providerId!==pack.providerId||contract.sdkSourceDigest!==pack.sdkSourceDigest||contract.workPackDigest!==pack.workPackDigest||contract.contractDigest!==sdkSemanticDigest(contractPayload(contract))||contract.executionAuthorityEffect!=="none"||contract.activationEffect!=="none"||Date.parse(contract.expiresAt)<=Date.parse(now)||forbidden.test(canonical(contract)))throw new Error("Semantic contract failed identity, integrity, expiry or injection validation.");
 const facts:ConfirmedFact[]=[...contract.roles.map(x=>x.fact),...contract.parameterMappings.flatMap(x=>[x.fact,x.expression.fact]),contract.credentials.action.fact,contract.credentials.observer.fact,contract.stableIdentity.fact,contract.stableIdentity.expression.fact,contract.idempotency.fact,...contract.idempotency.conflictIdentity.map(x=>x.fact),contract.reconciliation.fact,contract.observer.fact,contract.outcome.fact,...contract.outcome.predicates.map(x=>x.fact),contract.outcome.duplicate.fact,...contract.outcome.collateral.map(x=>x.fact),contract.outcome.freshness.fact,contract.pagination.fact,...contract.pagination.roles.map(x=>x.fact),contract.policy.fact];facts.forEach(assertFact);
 if(contract.roles.length!==4||new Set(contract.roles.map(x=>x.role)).size!==4)throw new Error("Semantic contract must bind all four exact roles.");for(const role of contract.roles){const found=pack.roles.find(x=>x.review.role===role.role);if(!found||found.methodDigest!==role.methodDigest)throw new Error("Semantic role is stale or cross-provider substituted.");}
 if(contract.credentials.action.alias===contract.credentials.observer.alias||!contract.credentials.action.exactScope||!contract.credentials.observer.exactScope)throw new Error("Credential aliases/scopes are shared or missing.");
 if(!contract.idempotency.reconcileBeforeRetry||contract.idempotency.blindRetryAllowed||contract.idempotency.conflictIdentity.length===0||contract.stableIdentity.collisionPolicy!=="reject-conflict")throw new Error("Idempotency, collision or retry policy is unsafe.");
 const action=contract.roles.find(x=>x.role==="action")!,observer=contract.roles.find(x=>x.role==="independent-observer")!;if(action.methodDigest===observer.methodDigest||!contract.observer.authIndependent||!contract.observer.differentMethodFromAction)throw new Error("Action and observer are conflated.");
 if(!contract.pagination.complete||contract.pagination.roles.length!==2||contract.pagination.roles.some(x=>x.mode==="complete-cursor"&&x.maximumPages<1)||contract.policy.maximumAttempts>3||contract.policy.timeoutMilliseconds<100||contract.policy.timeoutMilliseconds>120000||contract.policy.maximumRequestsPerMinute<1)throw new Error("Pagination or bounded execution policy is incomplete/unsafe.");
 if(contract.outcome.predicates.length===0||contract.outcome.collateral.length===0||contract.outcome.freshness.maximumAgeSeconds<1)throw new Error("Independent outcome proof is incomplete.");
 for(const role of pack.roles){const expected=role.method.parameters.filter(x=>x.required).map(x=>x.name).sort();const mapped=contract.parameterMappings.filter(x=>x.role===role.review.role).map(x=>x.parameter).sort();if(new Set(mapped).size!==mapped.length||canonical(expected)!==canonical(mapped))throw new Error("Parameter mappings must cover each required SDK parameter exactly once.");}
 for(const predicate of [...contract.outcome.predicates,...contract.outcome.collateral]){if(predicate.path.length===0||predicate.operator==="equals-input"&&!predicate.inputKey||predicate.operator==="equals-confirmed"&&predicate.expected===undefined||predicate.operator==="count-equals"&&typeof predicate.expected!=="number")throw new Error("Outcome predicate is ambiguous or incomplete.");}
 if(contract.outcome.duplicate.collectionPath.length===0||contract.outcome.freshness.path.length===0)throw new Error("Duplicate or freshness observation path is missing.");
}
function readPath(value:unknown,path:string[]):unknown{let current=value;for(const key of path){if(current===null||typeof current!=="object"||Array.isArray(current)||!(key in current))return undefined;current=(current as Record<string,unknown>)[key];}return current;}
function evaluate(expr:ValueExpression,input:Record<string,unknown>,context:Record<string,unknown>):Scalar{const raw=(expr.source==="workflow-input"?input:context)[expr.key];if(raw===undefined)throw new Error(`Required semantic input ${expr.key} is missing.`);if(expr.convert==="identity"){if(raw===null||["string","number","boolean"].includes(typeof raw))return raw as Scalar;throw new Error("Identity conversion accepts scalar values only.");}if(expr.convert==="string")return String(raw);if(expr.convert==="number"){const n=Number(raw);if(!Number.isFinite(n))throw new Error("Number conversion failed.");return n;}if(typeof raw==="boolean")return raw;if(raw==="true"||raw===1)return true;if(raw==="false"||raw===0)return false;throw new Error("Boolean conversion failed.");}

export function compileSdkSemanticContract(input:{contract:SdkSemanticContract;workPack:SdkImplementationWorkPack;now:string}):AcceptanceOnlySemanticAdapters{
 assertContract(input.contract,input.workPack,input.now);const fail=async():Promise<never>=>{throw new Error("Semantic adapters remain non-executable until CF-030 conformance, CF-029 qualification and mandatory acceptance are attached.");};const implementationDigest=sdkSemanticDigest({compiler:CUSTOMER_LOCAL_SDK_SEMANTIC_COMPILER_VERSION,contract:input.contract.contractDigest,workPack:input.workPack.workPackDigest});return{schemaVersion:"1.0",state:"acceptance-only-non-executable",providerId:input.contract.providerId,contractDigest:input.contract.contractDigest,workPackDigest:input.workPack.workPackDigest,implementationDigest,action:fail,probe:fail,reconcile:fail,observe:fail,executionAuthorityEffect:"none",activationEffect:"none"};
}
export function writeSdkSemanticContract(input:{projectPath:string;contract:SdkSemanticContract;workPack:SdkImplementationWorkPack;now:string}):{path:string;digest:string}{
 assertContract(input.contract,input.workPack,input.now);const root=resolve(input.projectPath),target=resolve(root,"sdk-semantic-contract.json");if(!target.startsWith(`${root}${sep}`))throw new Error("Semantic contract output escaped the plugin root.");const serialized=`${JSON.stringify(input.contract,null,2)}\n`;writeFileSync(target,serialized,{encoding:"utf8",mode:0o600,flag:"wx"});return{path:join(input.projectPath,"sdk-semantic-contract.json"),digest:sdkSemanticDigest(input.contract)};
}
export function attachSdkSemanticAcceptance(input:{compiled:AcceptanceOnlySemanticAdapters;contract:SdkSemanticContract;workPack:SdkImplementationWorkPack;invoker:SemanticSdkInvoker;conformance:CustomerLocalPluginConformanceReceipt;qualification:BindingQualificationReceipt;acceptance:SdkSemanticAcceptanceEvidence;now:string}):ExecutableAcceptanceSemanticAdapters{
 assertContract(input.contract,input.workPack,input.now);if(input.compiled.contractDigest!==input.contract.contractDigest||input.compiled.workPackDigest!==input.workPack.workPackDigest)throw new Error("Compiled semantic adapters are stale.");if(input.invoker.implementationDigest!==input.compiled.implementationDigest)throw new Error("Runtime implementation does not match the compiled semantic adapter digest.");const{receiptDigest,...conformancePayload}=input.conformance;if(receiptDigest!==customerLocalPluginDigest(conformancePayload)||input.conformance.state!=="passed"||input.conformance.failedChecks!==0||Date.parse(input.conformance.expiresAt)<=Date.parse(input.now)||input.conformance.executionAuthorityEffect!=="none"||input.conformance.activationEffect!=="none")throw new Error("Current exact CF-030 conformance evidence is required.");assertBindingQualificationReceipt(input.qualification);if(Date.parse(input.qualification.expiresAt)<=Date.parse(input.now)||input.qualification.executionAuthorityEffect!=="none"||input.qualification.activationEffect!=="none")throw new Error("Current exact CF-029 qualification evidence is required.");const{evidenceDigest,...evidencePayload}=input.acceptance;if(input.acceptance.caseIds.length!==REQUIRED_PILOT_ADAPTER_CASES.length||new Set(input.acceptance.caseIds).size!==REQUIRED_PILOT_ADAPTER_CASES.length||REQUIRED_PILOT_ADAPTER_CASES.some(x=>!input.acceptance.caseIds.includes(x))||evidenceDigest!==sdkSemanticAcceptanceEvidenceDigest(evidencePayload)||input.acceptance.contractDigest!==input.contract.contractDigest||input.acceptance.workPackDigest!==input.workPack.workPackDigest||input.acceptance.implementationDigest!==input.compiled.implementationDigest||input.acceptance.conformanceReceiptDigest!==input.conformance.receiptDigest||input.acceptance.qualificationReceiptDigest!==input.qualification.receiptDigest)throw new Error("Mandatory acceptance evidence is incomplete, stale or cross-boundary substituted.");
 const invoke=async(role:SemanticSdkInvocation["role"],data:Record<string,unknown>,context:Record<string,unknown>)=>{const method=input.workPack.roles.find(x=>x.review.role===role)!;const mappings=input.contract.parameterMappings.filter(x=>x.role===role);const parameters=Object.fromEntries(mappings.map(x=>[x.parameter,evaluate(x.expression,data,context)]));const stableId=String(evaluate(input.contract.stableIdentity.expression,data,context));const idempotencyKey=String(evaluate(input.contract.idempotency.expression,data,context));const credential=role==="action"?input.contract.credentials.action:input.contract.credentials.observer;return input.invoker.invoke({role,methodDigest:method.methodDigest,parameters,credentialAlias:credential.alias,scope:credential.exactScope,stableId,idempotencyKey,timeoutMilliseconds:input.contract.policy.timeoutMilliseconds});};
 const predicateCheck=(p:SemanticPredicate,value:unknown,data:Record<string,unknown>)=>{const actual=readPath(value,p.path);const passed=p.operator==="exists"?actual!==undefined:p.operator==="equals-input"?actual===data[p.inputKey!]:p.operator==="equals-confirmed"?actual===p.expected:Array.isArray(actual)&&actual.length===p.expected;return{key:p.key,passed};};
 return{state:"acceptance-attached",action:async(d,c)=>{const result=await invoke("action",d,c);if(result.status!=="ok")throw new Error("SDK action did not return a bounded success status.");return result.value;},probe:async(d,c)=>{const result=await invoke("no-write-probe",d,c);if(result.status!=="ok")throw new Error("SDK no-write probe did not pass.");return result.value;},reconcile:async(d,c)=>{const r=await invoke("reconciliation-readback",d,c);if(!r.paginationComplete)return{classification:"unknown-incomplete-pagination",value:r.value};if(r.status==="error")return{classification:"unknown",value:r.value};const matches=readPath(r.value,input.contract.outcome.duplicate.collectionPath);if(Array.isArray(matches)&&matches.length>input.contract.outcome.duplicate.expectedCount)return{classification:"duplicate",value:r.value};return{classification:r.status==="not-found"?"not-started":"completed",value:r.value};},observe:async(d,c,start)=>{const r=await invoke("independent-observer",d,c);const checks=[...input.contract.outcome.predicates.map(p=>predicateCheck(p,r.value,d)),{key:"duplicate-count",passed:Array.isArray(readPath(r.value,input.contract.outcome.duplicate.collectionPath))&&((readPath(r.value,input.contract.outcome.duplicate.collectionPath) as unknown[]).length===input.contract.outcome.duplicate.expectedCount)},...input.contract.outcome.collateral.map(p=>predicateCheck(p,r.value,d))];const observedValue=readPath(r.value,input.contract.outcome.freshness.path);const observed=typeof observedValue==="string"?Date.parse(observedValue):NaN;const fresh=Number.isFinite(observed)&&observed>=start&&observed-start<=input.contract.outcome.freshness.maximumAgeSeconds*1000;checks.push({key:"freshness",passed:fresh},{key:"pagination-complete",passed:r.paginationComplete},{key:"observer-status",passed:r.status==="ok"});const passed=checks.every(x=>x.passed);return{passed,classification:passed?"completed":r.status==="error"||!r.paginationComplete||!Number.isFinite(observed)?"unknown":"incorrect",checks,value:r.value};}};
}
