import { chmodSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { DatabaseSync } from "node:sqlite";
import FastifyBase, { type FastifyInstance, type FastifyReply, type FastifyRequest } from "fastify";
import { createHash, timingSafeEqual, type KeyObject } from "node:crypto";
import { cleanPackageAuthoringDigest, type CleanPackageAuthoringSnapshot } from "./onboarding-clean-package-authoring.js";
import type { OnboardingCleanPackageDerivation } from "./onboarding-clean-package.js";
import type { CleanPackageImportConfirmationArtifact } from "./onboarding-productization-sidecar.js";
import { sdkWorkPackDigest, type SdkImplementationWorkPack } from "./customer-local-sdk-work-pack.js";
import { sdkSemanticDraftDigest, type SdkSemanticDraftSnapshot } from "./customer-local-sdk-semantic-drafting.js";
import type { AcceptanceOnlySemanticAdapters } from "./customer-local-sdk-semantic-compiler.js";
import { customerLocalPluginDigest, CUSTOMER_LOCAL_PLUGIN_CONFORMANCE_CONTROL_IDS, type CustomerLocalPluginConformanceReceipt } from "./customer-local-plugin-conformance.js";
import { assertBindingQualificationReceipt, type BindingQualificationReceipt } from "./customer-local-binding-qualification.js";
import { pluginScaffoldDigest, verifyPluginReleaseSignature, type DetachedPluginReleaseSignature, type PluginReleaseManifest } from "./customer-local-plugin-scaffold.js";
import { customerLocalPluginHostDigest, type PluginHostDoctorReport } from "./customer-local-plugin-host.js";
import {CUSTOMER_LOCAL_RESOURCE_LIMITS,assertBoundedValue,assertHistoryCapacity,assertUniqueBoundedStrings,redactResourceError} from "./customer-local-resource-bounds.js";

const Fastify:typeof FastifyBase=((options:Record<string,unknown>)=>FastifyBase({...options,bodyLimit:CUSTOMER_LOCAL_RESOURCE_LIMITS.inputBytes}))as typeof FastifyBase;

export const CUSTOMER_LOCAL_ONBOARDING_JOURNEY_VERSION="1.2" as const;
export const ONBOARDING_JOURNEY_STAGES=["cf027-authoring","cf026-package-import","cf036-sdk-work-pack","cf041-semantic-review","cf037-acceptance-only-compile","cf030-plugin-conformance","cf029-binding-qualification","cf035-signed-release","cf034-host-doctor","readiness-evidence"] as const;
export type OnboardingJourneyStage=typeof ONBOARDING_JOURNEY_STAGES[number];
export type OnboardingJourneyOwner="customer"|"engineer"|"independent-proof";
const owners:Record<OnboardingJourneyStage,OnboardingJourneyOwner>={"cf027-authoring":"customer","cf026-package-import":"customer","cf036-sdk-work-pack":"engineer","cf041-semantic-review":"engineer","cf037-acceptance-only-compile":"engineer","cf030-plugin-conformance":"independent-proof","cf029-binding-qualification":"independent-proof","cf035-signed-release":"engineer","cf034-host-doctor":"independent-proof","readiness-evidence":"independent-proof"};
const identifier=/^[a-zA-Z][a-zA-Z0-9_.-]{1,179}$/;const digest=/^[a-f0-9]{64}$/;const secret=/(?:bearer|password|secret|token|api[_ -]?key)\s*[:=]\s*[^\s,;}]+|CF_CANARY_[A-Z0-9_-]+/i;
const canonical=(value:unknown):string=>{if(value===undefined)return"undefined";if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value!==null&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;return JSON.stringify(value);};
export const onboardingJourneyDigest=(value:unknown)=>{assertBoundedValue(value,"Onboarding digest material");return createHash("sha256").update(canonical(value)).digest("hex");};

export interface Cf026PackageImportEvidence {schemaVersion:"1.0";state:"confirmed-compiled-acceptance-only";packageDigest:string;decisionDigest:string;confirmedDecisions:21;confirmation:"CONFIRM ALL 21 CONSEQUENTIAL DECISIONS";authoringSnapshotDigest:string;executionAuthorityEffect:"none";activationEffect:"none";receiptDigest:string}
export interface Cf037CompilationEvidence {schemaVersion:"1.0";state:"acceptance-only-non-executable";providerId:string;contractDigest:string;workPackDigest:string;implementationDigest:string;callableMethods:["action","probe","reconcile","observe"];allMethodsFailClosedBeforeAcceptance:true;executionAuthorityEffect:"none";activationEffect:"none";receiptDigest:string}
export interface TrustedReleaseSignerConfiguration {signerKeyId:string;publicKey:KeyObject}
export interface TrustedReleaseSignerIdentity {signerKeyId:string;publicKeyDigest:string}
export interface Cf035SignedReleaseEvidence {schemaVersion:"1.1";manifest:PluginReleaseManifest;signature:DetachedPluginReleaseSignature;signerKeyId:string;trustedPublicKeyDigest:string;signatureDigest:string;executionAuthorityEffect:"none";activationEffect:"none"}
export interface JourneyFailure {controlId:string;detail:string;resolved:false}
export interface JourneyFailureRecord {failureId:string;stage:OnboardingJourneyStage;originatingArtifactDigest:string;controlId:string;detail:string;disclosedAt:string}
export interface JourneyFailureResolutionReceipt {schemaVersion:"1.0";journeyId:string;tenantId:string;sourceIdentityDigest:string;originatingStage:OnboardingJourneyStage;originatingArtifactDigest:string;controlId:string;resolverIdentity:string;evidenceLinks:string[];resolutionDetail:string;resolvedAt:string;executionAuthorityEffect:"none";activationEffect:"none";receiptDigest:string}
export interface JourneyLineage {schemaVersion:"1.0";tenantId:string;journeyId:string;sourceIdentityDigest:string;previousLineageDigest:string|null;packageSessionId?:string;packageDigest?:string;factoryResultDigest?:string;providerId?:string;pluginId?:string;workPackDigest?:string;contractDigest?:string;implementationDigest?:string;bundleId?:string;sourcePackageDigest?:string;providerDigest?:string;resolverImplementationDigest?:string;actionTransportDigest?:string;observerTransportDigest?:string;actionProfileDigest?:string;observerProfileDigest?:string;conformanceReceiptDigest?:string;bindingReceiptDigest?:string;releaseManifestDigest?:string;releaseSignerKeyId?:string;releaseSignerPublicKeyDigest?:string;doctorConformanceReceiptDigest?:string;doctorReportDigest?:string;readinessReceiptDigest?:string;lineageDigest:string}
export interface ReadinessEvidence {schemaVersion:"1.1";state:"preparation-chain-complete";requiredStageDigests:Record<OnboardingJourneyStage,string>;failureLedgerDigest:string;historicalFailureCount:number;resolvedFailureCount:number;failedControls:number;omittedFailures:number;issuedAt:string;expiresAt:string;customerProductionEvidence:false;executionAuthorityEffect:"none";activationEffect:"none";receiptDigest:string}
export type JourneyStagePayload=CleanPackageAuthoringSnapshot|Cf026PackageImportEvidence|SdkImplementationWorkPack|SdkSemanticDraftSnapshot|Cf037CompilationEvidence|CustomerLocalPluginConformanceReceipt|BindingQualificationReceipt|Cf035SignedReleaseEvidence|PluginHostDoctorReport|ReadinessEvidence;
export interface JourneyArtifact {schemaVersion:"1.1";journeyId:string;tenantId:string;stage:OnboardingJourneyStage;owner:OnboardingJourneyOwner;payload:JourneyStagePayload;payloadDigest:string;upstreamArtifactDigest:string|null;sourceDigest:string;lineage:JourneyLineage;evidenceLinks:string[];failures:JourneyFailure[];recordedBy:string;recordedAt:string;executionAuthorityEffect:"none";activationEffect:"none";artifactDigest:string}
export interface JourneyArtifactInput {stage:OnboardingJourneyStage;payload:JourneyStagePayload;sourceDigest:string;evidenceLinks:string[];failures:JourneyFailure[];failureResolutions?:JourneyFailureResolutionReceipt[];recordedBy:string;recordedAt:string;expectedJourneyDigest:string;expectedRevision:number;upstreamArtifactDigest:string|null;replaceExisting?:boolean}
export interface JourneySnapshot {schemaVersion:"1.2";journeyId:string;tenantId:string;sourceIdentity:string;sourceIdentityDigest:string;trustedReleaseSigner:TrustedReleaseSignerIdentity|null;revision:number;state:"preparing"|"quarantined"|"preparation-complete";currentStage:OnboardingJourneyStage|null;artifacts:Partial<Record<OnboardingJourneyStage,JourneyArtifact>>;failureLedger:JourneyFailureRecord[];failureResolutions:JourneyFailureResolutionReceipt[];invalidatedArtifacts:Array<{stage:OnboardingJourneyStage;artifactDigest:string;reason:string;invalidatedAt:string}>;dependencyGraph:Array<{stage:OnboardingJourneyStage;dependsOn:OnboardingJourneyStage|null;owner:OnboardingJourneyOwner}>;availableNextActions:string[];blockers:Array<{stage:OnboardingJourneyStage;owner:OnboardingJourneyOwner;detail:string}>;metrics:{commands:number;uniqueConfirmations:number;reusedConfirmations:number;explicitDecisions:number;manualCodeFiles:number;manualConfigObjects:number;restarts:number;stageTransitions:number;duplicateReviews:0};eventCount:number;eventHeadDigest:string|null;executionAuthorityEffect:"none";activationEffect:"none";createdAt:string;updatedAt:string;journeyDigest:string}
export interface JourneyEvent {sequence:number;journeyId:string;eventType:"journey-started"|"artifact-attached"|"downstream-invalidated"|"journey-rolled-back"|"restart-observed";revision:number;statePayloadDigest:string;previousEventDigest:string|null;detail:string;occurredAt:string;eventDigest:string}

/**
 * Produces the serializable CF-026 journey receipt from the exact outputs of
 * CF-027 and CF-026. It is intentionally impossible to supply digests by hand.
 */
export function createCf026PackageImportEvidence(input:{authoring:CleanPackageAuthoringSnapshot;derivation:OnboardingCleanPackageDerivation;confirmation:CleanPackageImportConfirmationArtifact}):Cf026PackageImportEvidence{
 if(input.authoring.status!=="package-draft-ready"||!input.authoring.packageDraft||input.authoring.packageDraft.sessionId!==input.derivation.package.sessionId||input.authoring.packageDraft.tenantId!==input.derivation.package.tenantId)throw new Error("CF-026 receipt requires the exact completed CF-027 package draft.");
 if(input.confirmation.packageDigest!==input.derivation.packageDigest||input.confirmation.decisionDigest!==input.derivation.decisionDigest||input.confirmation.confirmation!=="CONFIRM ALL 21 CONSEQUENTIAL DECISIONS")throw new Error("CF-026 receipt requires exact confirmation of the current 21-decision derivation.");
 const body={schemaVersion:"1.0" as const,state:"confirmed-compiled-acceptance-only" as const,packageDigest:input.derivation.packageDigest,decisionDigest:input.derivation.decisionDigest,confirmedDecisions:21 as const,confirmation:input.confirmation.confirmation,authoringSnapshotDigest:input.authoring.snapshotDigest,executionAuthorityEffect:"none" as const,activationEffect:"none" as const};return{...body,receiptDigest:onboardingJourneyDigest(body)};
}

/** Serializes the exact non-executable CF-037 compiler result for the journey. */
export function createCf037CompilationEvidence(compiled:AcceptanceOnlySemanticAdapters):Cf037CompilationEvidence{
 if(compiled.state!=="acceptance-only-non-executable"||compiled.executionAuthorityEffect!=="none"||compiled.activationEffect!=="none")throw new Error("CF-037 compilation result is not acceptance-only.");
 const body={schemaVersion:"1.0" as const,state:compiled.state,providerId:compiled.providerId,contractDigest:compiled.contractDigest,workPackDigest:compiled.workPackDigest,implementationDigest:compiled.implementationDigest,callableMethods:["action","probe","reconcile","observe"] as ["action","probe","reconcile","observe"],allMethodsFailClosedBeforeAcceptance:true as const,executionAuthorityEffect:"none" as const,activationEffect:"none" as const};return{...body,receiptDigest:onboardingJourneyDigest(body)};
}

export function trustedReleasePublicKeyDigest(publicKey:KeyObject):string{
 if(publicKey.type!=="public"||publicKey.asymmetricKeyType!=="ed25519")throw new Error("Trusted release signer must be an Ed25519 public key.");
 return createHash("sha256").update(publicKey.export({type:"spki",format:"der"})).digest("hex");
}
export function onboardingJourneySourceDigest(input:{journeyId:string;tenantId:string;sourceIdentity:string}):string{return onboardingJourneyDigest({schemaVersion:"1.0",boundary:"customer-local-onboarding-source",...input});}

/** Retains and verifies the actual detached signature material; no boolean attestation is accepted. */
export function createCf035SignedReleaseEvidence(input:{manifest:PluginReleaseManifest;signature:DetachedPluginReleaseSignature;publicKey:KeyObject;requiredSignerKeyId:string}):Cf035SignedReleaseEvidence{
 verifyPluginReleaseSignature(input.manifest,input.signature,input.publicKey,input.requiredSignerKeyId);
 return{schemaVersion:"1.1",manifest:structuredClone(input.manifest),signature:structuredClone(input.signature),signerKeyId:input.requiredSignerKeyId,trustedPublicKeyDigest:trustedReleasePublicKeyDigest(input.publicKey),signatureDigest:pluginScaffoldDigest(input.signature),executionAuthorityEffect:"none",activationEffect:"none"};
}

export function createJourneyFailureResolutionReceipt(input:Omit<JourneyFailureResolutionReceipt,"schemaVersion"|"executionAuthorityEffect"|"activationEffect"|"receiptDigest">):JourneyFailureResolutionReceipt{
 const body={schemaVersion:"1.0" as const,...structuredClone(input),executionAuthorityEffect:"none" as const,activationEffect:"none" as const};return{...body,receiptDigest:onboardingJourneyDigest(body)};
}

function failureState(snapshot:JourneySnapshot){
 const resolved=new Set(snapshot.failureResolutions.map(item=>`${item.originatingArtifactDigest}:${item.controlId}`));
 const unresolved=snapshot.failureLedger.filter(item=>!resolved.has(`${item.originatingArtifactDigest}:${item.controlId}`));
 const current=new Set(Object.values(snapshot.artifacts).flatMap(item=>(item?.failures??[]).map(f=>`${item!.artifactDigest}:${f.controlId}`)));
 const omitted=unresolved.filter(item=>!current.has(`${item.originatingArtifactDigest}:${item.controlId}`));
 return{resolvedCount:snapshot.failureLedger.length-unresolved.length,unresolved,omitted,ledgerDigest:onboardingJourneyDigest({failures:snapshot.failureLedger,resolutions:snapshot.failureResolutions})};
}

function epoch(value:string,label:string){const parsed=Date.parse(value);if(!Number.isFinite(parsed)||parsed<=0)throw new Error(`${label} timestamp is invalid.`);return parsed;}
function assertCurrentWindow(issuedAt:string,expiresAt:string,now:string,label:string){const issued=epoch(issuedAt,`${label} issued`),expires=epoch(expiresAt,`${label} expiry`),current=epoch(now,"Current");if(issued>current)throw new Error(`${label} evidence is future-issued.`);if(expires<=issued)throw new Error(`${label} chronology is invalid.`);if(expires<=current)throw new Error(`${label} evidence is expired.`);}
function currentExpiry(snapshot:JourneySnapshot){const conformance=snapshot.artifacts["cf030-plugin-conformance"]!.payload as CustomerLocalPluginConformanceReceipt,qualification=snapshot.artifacts["cf029-binding-qualification"]!.payload as BindingQualificationReceipt,release=snapshot.artifacts["cf035-signed-release"]!.payload as Cf035SignedReleaseEvidence,doctor=snapshot.artifacts["cf034-host-doctor"]!.payload as PluginHostDoctorReport;return new Date(Math.min(epoch(conformance.expiresAt,"CF-030 expiry"),epoch(qualification.expiresAt,"CF-029 expiry"),epoch(release.manifest.expiresAt,"CF-035 expiry"),epoch(doctor.conformance.expiresAt!,"CF-034 expiry"))).toISOString();}

/** Builds final readiness from the exact persisted chain and its append-only failure history. */
export function createOnboardingJourneyReadinessEvidence(snapshot:JourneySnapshot,now:string):ReadinessEvidence{
 if(snapshot.state==="quarantined"||snapshot.currentStage!=="cf034-host-doctor")throw new Error("Readiness requires the complete unquarantined preparation chain through CF-034.");
 const requiredStageDigests={} as Record<OnboardingJourneyStage,string>;for(const stage of ONBOARDING_JOURNEY_STAGES.slice(0,-1)){const item=snapshot.artifacts[stage];if(!item)throw new Error(`Readiness is missing exact ${stage} evidence.`);requiredStageDigests[stage]=item.artifactDigest;}
 const failures=failureState(snapshot),expiresAt=currentExpiry(snapshot);assertCurrentWindow(now,expiresAt,now,"Readiness");
 const body={schemaVersion:"1.1" as const,state:"preparation-chain-complete" as const,requiredStageDigests,failureLedgerDigest:failures.ledgerDigest,historicalFailureCount:snapshot.failureLedger.length,resolvedFailureCount:failures.resolvedCount,failedControls:failures.unresolved.length,omittedFailures:failures.omitted.length,issuedAt:now,expiresAt,customerProductionEvidence:false as const,executionAuthorityEffect:"none" as const,activationEffect:"none" as const};
 if(body.failedControls||body.omittedFailures)throw new Error("Readiness cannot omit or carry unresolved historical failures.");return{...body,receiptDigest:onboardingJourneyDigest(body)};
}

function payloadWithout<T extends Record<string,unknown>>(value:T,key:string){const copy={...value};delete copy[key];return copy;}
function assertBase(input:JourneyArtifactInput,stage:OnboardingJourneyStage,snapshot:JourneySnapshot,now:string){assertBoundedValue(input,"Onboarding artifact submission");assertUniqueBoundedStrings(input.evidenceLinks,"Onboarding evidence links",CUSTOMER_LOCAL_RESOURCE_LIMITS.evidenceLinks,2_048);if(input.failures.length>CUSTOMER_LOCAL_RESOURCE_LIMITS.failuresPerArtifact||(input.failureResolutions?.length??0)>CUSTOMER_LOCAL_RESOURCE_LIMITS.failureResolutionsPerArtifact)throw new Error("Onboarding failure evidence exceeds its per-artifact count limit.");const recorded=epoch(input.recordedAt,`${stage} recorded`);if(input.stage!==stage||!identifier.test(input.recordedBy)||recorded>epoch(now,"Current")||recorded<epoch(snapshot.updatedAt,"Prior journey update")||input.sourceDigest!==snapshot.sourceIdentityDigest||secret.test(canonical(input)))throw new Error(`${stage} artifact contains invalid identity, derived provenance, non-monotonic timestamp or secret-shaped content.`);if(input.evidenceLinks.length===0||input.evidenceLinks.some(x=>!/^artifact:\/\/[a-zA-Z0-9_.:/-]+$/.test(x)))throw new Error(`${stage} requires explicit customer-local evidence links.`);if(input.failures.some(x=>!identifier.test(x.controlId)||!x.detail||x.resolved!==false)||new Set(input.failures.map(x=>x.controlId)).size!==input.failures.length)throw new Error("Artifact failures must be unique explicit unresolved append-only records.");}
function artifactPayloadDigest(payload:JourneyStagePayload){return onboardingJourneyDigest(payload);}
function sameIdentity(actual:string|undefined,expected:string|undefined,label:string){if(!actual||!expected||actual!==expected)throw new Error(`${label} lineage changed or belongs to another preparation chain.`);}
function assertTrustedSigner(snapshot:JourneySnapshot,configuration:TrustedReleaseSignerConfiguration|undefined){if(!snapshot.trustedReleaseSigner||!configuration||snapshot.trustedReleaseSigner.signerKeyId!==configuration.signerKeyId||snapshot.trustedReleaseSigner.publicKeyDigest!==trustedReleasePublicKeyDigest(configuration.publicKey))throw new Error("Customer-local trusted release signer configuration is missing or changed.");}
function assertStagePayload(stage:OnboardingJourneyStage,payload:JourneyStagePayload,snapshot:JourneySnapshot,now:string,configuration:TrustedReleaseSignerConfiguration|undefined){const prior=snapshot.artifacts,lineage=stage==="cf027-authoring"?undefined:prior[ONBOARDING_JOURNEY_STAGES[ONBOARDING_JOURNEY_STAGES.indexOf(stage)-1]!]!.lineage;
 if(stage==="cf027-authoring"){const item=payload as CleanPackageAuthoringSnapshot;if(item.status!=="package-draft-ready"||!item.packageDraft||item.tenantId!==snapshot.tenantId||item.packageSessionId!==item.packageDraft.sessionId||item.executionAuthorityEffect!=="none"||item.activationEffect!=="none"||item.snapshotDigest!==cleanPackageAuthoringDigest(payloadWithout(item as unknown as Record<string,unknown>,"snapshotDigest")))throw new Error("CF-027 authoring evidence is incomplete, cross-tenant, forged or non-final.");}
 else if(stage==="cf026-package-import"){const item=payload as Cf026PackageImportEvidence;const{receiptDigest,...body}=item;if(item.state!=="confirmed-compiled-acceptance-only"||item.confirmedDecisions!==21||item.confirmation!=="CONFIRM ALL 21 CONSEQUENTIAL DECISIONS"||item.authoringSnapshotDigest!==(prior["cf027-authoring"]!.payload as CleanPackageAuthoringSnapshot).snapshotDigest||receiptDigest!==onboardingJourneyDigest(body))throw new Error("CF-026 exact import confirmation is missing or forged.");}
 else if(stage==="cf036-sdk-work-pack"){const item=payload as SdkImplementationWorkPack;const{workPackDigest,...body}=item;if(item.state!=="engineer-implementation-required"||workPackDigest!==sdkWorkPackDigest(body)||item.executionAuthorityEffect!=="none"||item.activationEffect!=="none")throw new Error("CF-036 work pack failed integrity or trust boundary validation.");}
 else if(stage==="cf041-semantic-review"){const item=payload as SdkSemanticDraftSnapshot;if(item.state!=="reviewed-contract-ready"||!item.reviewedContract||item.providerId!==lineage!.providerId||item.workPackDigest!==lineage!.workPackDigest||item.factoryResultDigest!==lineage!.factoryResultDigest||item.reviewedContract.providerId!==lineage!.providerId||item.reviewedContract.workPackDigest!==lineage!.workPackDigest||item.snapshotDigest!==sdkSemanticDraftDigest(payloadWithout(item as unknown as Record<string,unknown>,"snapshotDigest")))throw new Error("CF-041 reviewed semantic contract is missing, stale, cross-provider or forged.");}
 else if(stage==="cf037-acceptance-only-compile"){const item=payload as Cf037CompilationEvidence,contract=(prior["cf041-semantic-review"]!.payload as SdkSemanticDraftSnapshot).reviewedContract!,{receiptDigest,...body}=item;if(receiptDigest!==onboardingJourneyDigest(body)||item.state!=="acceptance-only-non-executable"||item.providerId!==lineage!.providerId||item.contractDigest!==contract.contractDigest||item.workPackDigest!==contract.workPackDigest||canonical(item.callableMethods)!==canonical(["action","probe","reconcile","observe"])||item.allMethodsFailClosedBeforeAcceptance!==true||item.executionAuthorityEffect!=="none"||item.activationEffect!=="none")throw new Error("CF-037 output is not the exact same-provider acceptance-only compile result.");}
 else if(stage==="cf030-plugin-conformance"){const item=payload as CustomerLocalPluginConformanceReceipt;const{receiptDigest,...body}=item;assertCurrentWindow(item.qualifiedAt,item.expiresAt,now,"CF-030 conformance");if(receiptDigest!==customerLocalPluginDigest(body)||item.state!=="passed"||item.sourcePackageDigest!==lineage!.packageDigest||item.failedChecks!==0||item.checks.length!==CUSTOMER_LOCAL_PLUGIN_CONFORMANCE_CONTROL_IDS.length||CUSTOMER_LOCAL_PLUGIN_CONFORMANCE_CONTROL_IDS.some(id=>!item.checks.some(x=>x.checkId===id&&x.passed))||item.executionAuthorityEffect!=="none"||item.activationEffect!=="none")throw new Error("CF-030 conformance evidence is incomplete, stale, cross-package, forged or selectively omits failures.");}
 else if(stage==="cf029-binding-qualification"){const item=payload as BindingQualificationReceipt;assertBindingQualificationReceipt(item);assertCurrentWindow(item.qualifiedAt,item.expiresAt,now,"CF-029 qualification");assertCurrentWindow(item.credentials.action.qualifiedAt,item.credentials.action.expiresAt,now,"CF-029 action credential");assertCurrentWindow(item.credentials.observer.qualifiedAt,item.credentials.observer.expiresAt,now,"CF-029 observer credential");assertCurrentWindow(item.transports.action.reviewedAt,item.transports.action.expiresAt,now,"CF-029 action transport");assertCurrentWindow(item.transports.observer.reviewedAt,item.transports.observer.expiresAt,now,"CF-029 observer transport");if(item.state!=="qualified-for-acceptance-compilation"||item.tenantId!==snapshot.tenantId||item.sessionId!==lineage!.packageSessionId||item.packageDigest!==lineage!.packageDigest||item.factoryResultDigest!==lineage!.factoryResultDigest||item.credentials.action.providerDigest!==lineage!.providerDigest||item.credentials.observer.providerDigest!==lineage!.providerDigest||item.credentials.action.resolverImplementationDigest!==lineage!.resolverImplementationDigest||item.credentials.observer.resolverImplementationDigest!==lineage!.resolverImplementationDigest||item.transports.action.implementationDigest!==lineage!.actionTransportDigest||item.transports.observer.implementationDigest!==lineage!.observerTransportDigest||customerLocalPluginDigest(item.transports.action)!==lineage!.actionProfileDigest||customerLocalPluginDigest(item.transports.observer)!==lineage!.observerProfileDigest||item.executionAuthorityEffect!=="none"||item.activationEffect!=="none")throw new Error("CF-029 qualification evidence is stale, cross-tenant, cross-package, cross-provider, cross-profile or inexact.");}
 else if(stage==="cf035-signed-release"){const item=payload as Cf035SignedReleaseEvidence,binding=prior["cf029-binding-qualification"]!.payload as BindingQualificationReceipt;assertTrustedSigner(snapshot,configuration);const{manifestDigest,...body}=item.manifest,{reviewedAt:_actionReviewed,expiresAt:_actionExpires,...actionProfile}=binding.transports.action,{reviewedAt:_observerReviewed,expiresAt:_observerExpires,...observerProfile}=binding.transports.observer;assertCurrentWindow(item.manifest.createdAt,item.manifest.expiresAt,now,"CF-035 release");if(item.schemaVersion!=="1.1"||manifestDigest!==pluginScaffoldDigest(body)||item.signerKeyId!==snapshot.trustedReleaseSigner!.signerKeyId||item.trustedPublicKeyDigest!==snapshot.trustedReleaseSigner!.publicKeyDigest||item.signature.signerKeyId!==item.signerKeyId||item.signatureDigest!==pluginScaffoldDigest(item.signature)||item.executionAuthorityEffect!=="none"||item.activationEffect!=="none")throw new Error("CF-035 detached signature envelope is missing, drifted or unverified.");sameIdentity(item.manifest.pluginId,lineage!.pluginId,"CF-035 plugin");sameIdentity(item.manifest.sourcePackageDigest,lineage!.sourcePackageDigest,"CF-035 package");sameIdentity(item.manifest.providerDigest,lineage!.providerDigest,"CF-035 provider");sameIdentity(item.manifest.resolverImplementationDigest,lineage!.resolverImplementationDigest,"CF-035 resolver");sameIdentity(item.manifest.actionTransportDigest,lineage!.actionTransportDigest,"CF-035 action transport");sameIdentity(item.manifest.observerTransportDigest,lineage!.observerTransportDigest,"CF-035 observer transport");sameIdentity(item.manifest.actionProfileDigest,customerLocalPluginHostDigest(actionProfile),"CF-035 action profile");sameIdentity(item.manifest.observerProfileDigest,customerLocalPluginHostDigest(observerProfile),"CF-035 observer profile");verifyPluginReleaseSignature(item.manifest,item.signature,configuration!.publicKey,configuration!.signerKeyId);}
 else if(stage==="cf034-host-doctor"){const item=payload as PluginHostDoctorReport,conformance=prior["cf030-plugin-conformance"]!.payload as CustomerLocalPluginConformanceReceipt;const{reportDigest,...body}=item;const checked=epoch(item.checkedAt,"CF-034 checked"),current=epoch(now,"Current");if(checked>current||!item.conformance.expiresAt)throw new Error("CF-034 host doctor is future-issued or has no expiry.");assertCurrentWindow(item.checkedAt,item.conformance.expiresAt,now,"CF-034 host doctor");if(reportDigest!==customerLocalPluginHostDigest(body)||item.state!=="conformant"||!item.usableForCf029||item.blockers.length>0||item.controls.length===0||item.controls.some(x=>!x.passed)||item.executionAuthorityEffect!=="none"||item.activationEffect!=="none")throw new Error("CF-034 host doctor is stale, forged or quarantined.");if(!item.conformance.receiptDigest)throw new Error("CF-034 omitted its fresh conformance receipt identity.");if(item.conformance.passedControls!==conformance.passedChecks||item.conformance.failedControls!==0)throw new Error("CF-034 conformance control totals differ from CF-030.");sameIdentity(item.tenantId,snapshot.tenantId,"CF-034 tenant");sameIdentity(item.bundleId,lineage!.bundleId,"CF-034 bundle");sameIdentity(item.packageIdentity.sourcePackageDigest,lineage!.sourcePackageDigest,"CF-034 source package");sameIdentity(item.packageIdentity.providerDigest,lineage!.providerDigest,"CF-034 provider");sameIdentity(item.packageIdentity.resolverImplementationDigest,lineage!.resolverImplementationDigest,"CF-034 resolver");sameIdentity(item.packageIdentity.actionTransportDigest,lineage!.actionTransportDigest,"CF-034 action transport");sameIdentity(item.packageIdentity.observerTransportDigest,lineage!.observerTransportDigest,"CF-034 observer transport");}
 else {assertPreparationCurrent(snapshot,now,configuration);const item=payload as ReadinessEvidence,{receiptDigest,...body}=item,failures=failureState(snapshot);assertCurrentWindow(item.issuedAt,item.expiresAt,now,"Readiness");if(receiptDigest!==onboardingJourneyDigest(body)||item.schemaVersion!=="1.1"||item.state!=="preparation-chain-complete"||item.failureLedgerDigest!==failures.ledgerDigest||item.historicalFailureCount!==snapshot.failureLedger.length||item.resolvedFailureCount!==failures.resolvedCount||item.failedControls!==failures.unresolved.length||item.omittedFailures!==failures.omitted.length||item.failedControls!==0||item.omittedFailures!==0||item.expiresAt!==currentExpiry(snapshot)||item.customerProductionEvidence!==false||ONBOARDING_JOURNEY_STAGES.slice(0,-1).some(s=>item.requiredStageDigests[s]!==prior[s]!.artifactDigest))throw new Error("Readiness evidence is forged, expired, incomplete or trust-laundered.");}
}
function assertPreparationCurrent(snapshot:JourneySnapshot,now:string,configuration:TrustedReleaseSignerConfiguration|undefined){for(const stage of ["cf030-plugin-conformance","cf029-binding-qualification","cf035-signed-release","cf034-host-doctor"] as const)if(snapshot.artifacts[stage])assertStagePayload(stage,snapshot.artifacts[stage]!.payload,{...snapshot,artifacts:Object.fromEntries(Object.entries(snapshot.artifacts).filter(([candidate])=>ONBOARDING_JOURNEY_STAGES.indexOf(candidate as OnboardingJourneyStage)<ONBOARDING_JOURNEY_STAGES.indexOf(stage)))},now,configuration);}
function lineagePayload(value:JourneyLineage){const{lineageDigest:_digest,...body}=value;return body;}
function deriveLineage(snapshot:JourneySnapshot,stage:OnboardingJourneyStage,payload:JourneyStagePayload):JourneyLineage{
 const index=ONBOARDING_JOURNEY_STAGES.indexOf(stage),previous=index===0?undefined:snapshot.artifacts[ONBOARDING_JOURNEY_STAGES[index-1]!]!.lineage;
 const base={schemaVersion:"1.0" as const,tenantId:snapshot.tenantId,journeyId:snapshot.journeyId,sourceIdentityDigest:snapshot.sourceIdentityDigest,previousLineageDigest:previous?.lineageDigest??null,...(previous?payloadWithout(previous as unknown as Record<string,unknown>,"lineageDigest"): {})} as Omit<JourneyLineage,"lineageDigest">;
 base.previousLineageDigest=previous?.lineageDigest??null;
 if(stage==="cf027-authoring"){const item=payload as CleanPackageAuthoringSnapshot;base.packageSessionId=item.packageSessionId;}
 else if(stage==="cf026-package-import"){base.packageDigest=(payload as Cf026PackageImportEvidence).packageDigest;}
 else if(stage==="cf036-sdk-work-pack"){const item=payload as SdkImplementationWorkPack;base.providerId=item.providerId;base.pluginId=item.pluginId;base.factoryResultDigest=item.factoryResultDigest;base.workPackDigest=item.workPackDigest;}
 else if(stage==="cf041-semantic-review"){const item=payload as SdkSemanticDraftSnapshot;base.contractDigest=item.reviewedContract!.contractDigest;}
 else if(stage==="cf037-acceptance-only-compile"){base.implementationDigest=(payload as Cf037CompilationEvidence).implementationDigest;}
 else if(stage==="cf030-plugin-conformance"){const item=payload as CustomerLocalPluginConformanceReceipt;base.bundleId=item.bundleId;base.sourcePackageDigest=item.sourcePackageDigest;base.providerDigest=item.providerDigest;base.resolverImplementationDigest=item.resolverImplementationDigest;base.actionTransportDigest=item.actionTransportDigest;base.observerTransportDigest=item.observerTransportDigest;base.actionProfileDigest=item.actionProfileDigest;base.observerProfileDigest=item.observerProfileDigest;base.conformanceReceiptDigest=item.receiptDigest;}
 else if(stage==="cf029-binding-qualification")base.bindingReceiptDigest=(payload as BindingQualificationReceipt).receiptDigest;
 else if(stage==="cf035-signed-release"){const item=payload as Cf035SignedReleaseEvidence;base.releaseManifestDigest=item.manifest.manifestDigest;base.releaseSignerKeyId=item.signerKeyId;base.releaseSignerPublicKeyDigest=item.trustedPublicKeyDigest;}
 else if(stage==="cf034-host-doctor"){const item=payload as PluginHostDoctorReport;base.doctorConformanceReceiptDigest=item.conformance.receiptDigest!;base.doctorReportDigest=item.reportDigest;}
 else base.readinessReceiptDigest=(payload as ReadinessEvidence).receiptDigest;
 return{...base,lineageDigest:onboardingJourneyDigest(base)};
}
function dependencyGraph(){return ONBOARDING_JOURNEY_STAGES.map((stage,index)=>({stage,dependsOn:index===0?null:ONBOARDING_JOURNEY_STAGES[index-1]!,owner:owners[stage]}));}
function journeyPayload(snapshot:JourneySnapshot){const{journeyDigest,...body}=snapshot;return body;}
function journeyStatePayload(snapshot:JourneySnapshot){const{journeyDigest:_journey,eventCount:_count,eventHeadDigest:_head,...body}=snapshot;return body;}
function finalize(snapshot:Omit<JourneySnapshot,"journeyDigest">):JourneySnapshot{return{...snapshot,journeyDigest:onboardingJourneyDigest(snapshot)};}
function currentStage(artifacts:JourneySnapshot["artifacts"]){for(let i=ONBOARDING_JOURNEY_STAGES.length-1;i>=0;i--){const stage=ONBOARDING_JOURNEY_STAGES[i]!;if(artifacts[stage])return stage;}return null;}
function projection(base:Omit<JourneySnapshot,"availableNextActions"|"blockers"|"currentStage"|"state"|"journeyDigest">):JourneySnapshot{const stage=currentStage(base.artifacts),index=stage?ONBOARDING_JOURNEY_STAGES.indexOf(stage):-1,next=ONBOARDING_JOURNEY_STAGES[index+1],failureStatus=failureState({...base,state:"preparing",currentStage:stage,availableNextActions:[],blockers:[],journeyDigest:""}),unresolved=failureStatus.unresolved,state:JourneySnapshot["state"]=unresolved.length?"quarantined":stage==="readiness-evidence"?"preparation-complete":"preparing";const blockers=unresolved.map(f=>({stage:f.stage,owner:owners[f.stage],detail:`${f.controlId}: ${f.detail}`}));if(next)blockers.push({stage:next,owner:owners[next],detail:`Attach exact ${next} evidence after its independent gate completes.`});return finalize({...base,state,currentStage:stage,availableNextActions:state==="quarantined"?["attach explicit failure-resolution receipt and replace originating artifact"]:next?[`attach:${next}`]:["export:redacted-preparation-evidence"],blockers});}

export class DurableCustomerLocalOnboardingJourney{
 private db:DatabaseSync;private now:()=>string;private trustedReleaseSigner?:TrustedReleaseSignerConfiguration;
 constructor(statePath=":memory:",options:{now?:()=>string;trustedReleaseSigner?:TrustedReleaseSignerConfiguration}={}){if(statePath!==":memory:")mkdirSync(dirname(statePath),{recursive:true,mode:0o700});this.db=new DatabaseSync(statePath);if(statePath!==":memory:")chmodSync(statePath,0o600);this.now=options.now??(()=>new Date().toISOString());if(options.trustedReleaseSigner){if(!identifier.test(options.trustedReleaseSigner.signerKeyId))throw new Error("Trusted release signer identity is invalid.");trustedReleasePublicKeyDigest(options.trustedReleaseSigner.publicKey);this.trustedReleaseSigner=options.trustedReleaseSigner;}this.db.exec(`CREATE TABLE IF NOT EXISTS onboarding_journeys(journey_id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,source_identity TEXT NOT NULL,snapshot_json TEXT NOT NULL,journey_digest TEXT NOT NULL);CREATE TABLE IF NOT EXISTS onboarding_journey_revisions(journey_id TEXT NOT NULL,revision INTEGER NOT NULL,snapshot_json TEXT NOT NULL,journey_digest TEXT NOT NULL,PRIMARY KEY(journey_id,revision));CREATE TABLE IF NOT EXISTS onboarding_journey_events(sequence INTEGER PRIMARY KEY AUTOINCREMENT,journey_id TEXT NOT NULL,event_type TEXT NOT NULL,revision INTEGER NOT NULL,journey_digest TEXT NOT NULL,previous_event_digest TEXT,detail TEXT NOT NULL,occurred_at TEXT NOT NULL,event_digest TEXT NOT NULL);`);}
 start(input:{journeyId:string;tenantId:string;sourceIdentity:string;recordedAt:string}){for(const id of [input.journeyId,input.tenantId,input.sourceIdentity])if(!identifier.test(id))throw new Error("Journey identity is invalid.");if(epoch(input.recordedAt,"Journey")>epoch(this.now(),"Current"))throw new Error("Journey timestamp is invalid or future-issued.");const existing=this.db.prepare("SELECT tenant_id,source_identity FROM onboarding_journeys WHERE journey_id=?").get(input.journeyId) as {tenant_id:string;source_identity:string}|undefined;if(existing){if(existing.tenant_id!==input.tenantId||existing.source_identity!==input.sourceIdentity)throw new Error("Journey replay conflicts with tenant or source identity.");const replay=this.read(input.journeyId,input.tenantId);if(canonical(replay.trustedReleaseSigner)!==canonical(this.signerIdentity()))throw new Error("Journey replay conflicts with its customer-local trusted signer.");return replay;}const sourceIdentityDigest=onboardingJourneySourceDigest({journeyId:input.journeyId,tenantId:input.tenantId,sourceIdentity:input.sourceIdentity}),snapshot=projection({schemaVersion:"1.2",journeyId:input.journeyId,tenantId:input.tenantId,sourceIdentity:input.sourceIdentity,sourceIdentityDigest,trustedReleaseSigner:this.signerIdentity(),revision:1,artifacts:{},failureLedger:[],failureResolutions:[],invalidatedArtifacts:[],dependencyGraph:dependencyGraph(),metrics:{commands:1,uniqueConfirmations:0,reusedConfirmations:0,explicitDecisions:0,manualCodeFiles:0,manualConfigObjects:0,restarts:0,stageTransitions:0,duplicateReviews:0},eventCount:0,eventHeadDigest:null,executionAuthorityEffect:"none",activationEffect:"none",createdAt:input.recordedAt,updatedAt:input.recordedAt});return structuredClone(this.insert(snapshot,"journey-started","Journey identity and trusted signer posture created."));}
 attach(journeyId:string,tenantId:string,input:JourneyArtifactInput){const current=this.read(journeyId,tenantId),now=this.now();if(input.expectedJourneyDigest!==current.journeyDigest||input.expectedRevision!==current.revision)throw new Error("Journey artifact submission is stale.");assertBase(input,input.stage,current,now);if(input.evidenceLinks.some(link=>!link.startsWith(`artifact://${journeyId}/`)))throw new Error("Cross-journey evidence links are forbidden.");const index=ONBOARDING_JOURNEY_STAGES.indexOf(input.stage),expectedPrevious=index===0?null:current.artifacts[ONBOARDING_JOURNEY_STAGES[index-1]!]??null;if(input.upstreamArtifactDigest!==(expectedPrevious?.artifactDigest??null))throw new Error("Journey artifact references missing, stale or cross-journey upstream evidence.");const existing=current.artifacts[input.stage];if(!existing&&current.state==="quarantined")throw new Error("Journey is quarantined by an unresolved recorded failure; later stages cannot bypass it.");if(!existing&&currentStage(current.artifacts)!==(index===0?null:ONBOARDING_JOURNEY_STAGES[index-1]))throw new Error("Journey stage skipping is forbidden.");assertStagePayload(input.stage,input.payload,current,now,this.trustedReleaseSigner);const lineage=deriveLineage(current,input.stage,input.payload),artifact=this.artifact(journeyId,tenantId,input,input.upstreamArtifactDigest,lineage);if(existing&&!input.replaceExisting){if(artifact.artifactDigest===existing.artifactDigest)return current;throw new Error("Journey stage already has a different review; replacement must be explicit.");}
  const resolutions=this.assertFailureResolutions(current,input,existing,now),artifacts={...current.artifacts,[input.stage]:artifact},invalidated=[...current.invalidatedArtifacts];if(existing){for(const stage of ONBOARDING_JOURNEY_STAGES.slice(index)){const old=current.artifacts[stage];if(old&&old.artifactDigest!==artifact.artifactDigest)invalidated.push({stage,artifactDigest:old.artifactDigest,reason:`Upstream ${input.stage} changed; downstream evidence cannot survive.`,invalidatedAt:input.recordedAt});if(stage!==input.stage)delete artifacts[stage];}}
  const newFailures=input.failures.map(f=>{const body={stage:input.stage,originatingArtifactDigest:artifact.artifactDigest,controlId:f.controlId,detail:f.detail,disclosedAt:input.recordedAt};return{...body,failureId:onboardingJourneyDigest(body)};}),failureIds=new Set(current.failureLedger.map(f=>f.failureId));if(newFailures.some(f=>failureIds.has(f.failureId)))throw new Error("Duplicate historical failure disclosure is forbidden.");
  const reused=this.reused(current,input),metrics={...current.metrics,commands:current.metrics.commands+1,uniqueConfirmations:current.metrics.uniqueConfirmations+Math.max(0,this.decisions(input)-reused),reusedConfirmations:current.metrics.reusedConfirmations+reused,explicitDecisions:current.metrics.explicitDecisions+this.decisions(input),manualCodeFiles:current.metrics.manualCodeFiles+(input.stage==="cf036-sdk-work-pack"?0:0),manualConfigObjects:current.metrics.manualConfigObjects+1,stageTransitions:current.metrics.stageTransitions+1};const{journeyDigest:_d,currentStage:_c,state:_s,availableNextActions:_a,blockers:_b,...rest}=current,updated=projection({...rest,revision:current.revision+1,artifacts,failureLedger:[...current.failureLedger,...newFailures],failureResolutions:[...current.failureResolutions,...resolutions],invalidatedArtifacts:invalidated,metrics,updatedAt:input.recordedAt});return structuredClone(this.update(current,updated,existing?"downstream-invalidated":"artifact-attached",`${input.stage} ${existing?"replaced with explicit historical-failure handling; downstream invalidated":"attached"}.`));}
 observeRestart(journeyId:string,tenantId:string){const current=this.read(journeyId,tenantId),timestamp=this.now(),{journeyDigest:_d,currentStage:_c,state:_s,availableNextActions:_a,blockers:_b,...rest}=current,updated=projection({...rest,revision:current.revision+1,metrics:{...current.metrics,commands:current.metrics.commands+1,restarts:current.metrics.restarts+1},updatedAt:timestamp});return structuredClone(this.update(current,updated,"restart-observed","Durable journey reloaded after process restart."));}
 rollback(journeyId:string,tenantId:string,input:{targetRevision:number;expectedJourneyDigest:string;expectedRevision:number;recordedAt:string}){const current=this.read(journeyId,tenantId);if(current.journeyDigest!==input.expectedJourneyDigest||current.revision!==input.expectedRevision||input.targetRevision>=current.revision)throw new Error("Rollback request is stale or does not target an earlier revision.");const row=this.db.prepare("SELECT snapshot_json FROM onboarding_journey_revisions WHERE journey_id=? AND revision=?").get(journeyId,input.targetRevision) as {snapshot_json:string}|undefined;if(!row)throw new Error("Rollback revision does not exist.");const target=JSON.parse(row.snapshot_json) as JourneySnapshot;if(target.tenantId!==tenantId)throw new Error("Rollback target belongs to another tenant.");const keepThrough=Math.min(ONBOARDING_JOURNEY_STAGES.indexOf("cf041-semantic-review"),target.currentStage?ONBOARDING_JOURNEY_STAGES.indexOf(target.currentStage):-1),artifacts:JourneySnapshot["artifacts"]={},invalidated=[...current.invalidatedArtifacts];for(const [stage,item] of Object.entries(current.artifacts) as Array<[OnboardingJourneyStage,JourneyArtifact]>){if(ONBOARDING_JOURNEY_STAGES.indexOf(stage)<=keepThrough&&target.artifacts[stage]?.artifactDigest===item.artifactDigest)artifacts[stage]=item;else invalidated.push({stage,artifactDigest:item.artifactDigest,reason:`Rollback to revision ${input.targetRevision} did not revive prior downstream evidence.`,invalidatedAt:input.recordedAt});}const{journeyDigest:_d,currentStage:_c,state:_s,availableNextActions:_a,blockers:_b,...rest}=current,updated=projection({...rest,revision:current.revision+1,artifacts,invalidatedArtifacts:invalidated,metrics:{...current.metrics,commands:current.metrics.commands+1},updatedAt:input.recordedAt});return structuredClone(this.update(current,updated,"journey-rolled-back",`Rolled back preparation facts toward revision ${input.targetRevision}; downstream proof invalidated.`));}
 read(journeyId:string,tenantId:string){const row=this.db.prepare("SELECT tenant_id,snapshot_json,journey_digest FROM onboarding_journeys WHERE journey_id=?").get(journeyId) as {tenant_id:string;snapshot_json:string;journey_digest:string}|undefined;if(!row||row.tenant_id!==tenantId)throw new Error("Journey does not exist or belongs to another tenant.");const snapshot=JSON.parse(row.snapshot_json) as JourneySnapshot;if(snapshot.schemaVersion!=="1.2"||canonical(snapshot.trustedReleaseSigner)!==canonical(this.signerIdentity())||!Number.isInteger(snapshot.eventCount)||snapshot.eventCount<1||(snapshot.eventHeadDigest!==null&&!digest.test(snapshot.eventHeadDigest))||snapshot.sourceIdentityDigest!==onboardingJourneySourceDigest({journeyId:snapshot.journeyId,tenantId:snapshot.tenantId,sourceIdentity:snapshot.sourceIdentity})||snapshot.journeyDigest!==onboardingJourneyDigest(journeyPayload(snapshot))||snapshot.journeyDigest!==row.journey_digest)throw new Error("Journey snapshot failed version, signer configuration, source-identity, event-state or integrity validation.");for(const item of Object.values(snapshot.artifacts)){const{lineageDigest,...lineageBody}=item!.lineage;if(lineageDigest!==onboardingJourneyDigest(lineageBody)||item!.sourceDigest!==snapshot.sourceIdentityDigest)throw new Error("Journey artifact lineage failed integrity validation.");}this.validateEventHistory(snapshot);if(snapshot.artifacts["readiness-evidence"])assertStagePayload("readiness-evidence",snapshot.artifacts["readiness-evidence"]!.payload,{...snapshot,artifacts:Object.fromEntries(Object.entries(snapshot.artifacts).filter(([stage])=>stage!=="readiness-evidence"))},this.now(),this.trustedReleaseSigner);return structuredClone(snapshot);}
 events(journeyId:string,tenantId:string){const snapshot=this.read(journeyId,tenantId);return this.validateEventHistory(snapshot);}
 exportRedacted(journeyId:string,tenantId:string){const snapshot=this.read(journeyId,tenantId),events=this.events(journeyId,tenantId);const artifacts=Object.fromEntries(Object.entries(snapshot.artifacts).map(([stage,item])=>[stage,{owner:item!.owner,payloadDigest:item!.payloadDigest,artifactDigest:item!.artifactDigest,upstreamArtifactDigest:item!.upstreamArtifactDigest,sourceDigest:item!.sourceDigest,lineageDigest:item!.lineage.lineageDigest,evidenceLinks:item!.evidenceLinks,failures:item!.failures,recordedBy:item!.recordedBy,recordedAt:item!.recordedAt}]));const body={schemaVersion:"1.1",journeyId,tenantId,sourceIdentityDigest:snapshot.sourceIdentityDigest,trustedReleaseSigner:snapshot.trustedReleaseSigner,state:snapshot.state,revision:snapshot.revision,currentStage:snapshot.currentStage,journeyDigest:snapshot.journeyDigest,artifacts,failureLedger:snapshot.failureLedger,failureResolutions:snapshot.failureResolutions,invalidatedArtifacts:snapshot.invalidatedArtifacts,events,metrics:snapshot.metrics,blockers:snapshot.blockers,executionAuthorityEffect:"none" as const,activationEffect:"none" as const,exportedAt:this.now()};return{...body,exportDigest:onboardingJourneyDigest(body)};}
 close(){this.db.close();}
 private artifact(journeyId:string,tenantId:string,input:JourneyArtifactInput,upstream:string|null,lineage:JourneyLineage){const body={schemaVersion:"1.1" as const,journeyId,tenantId,stage:input.stage,owner:owners[input.stage],payload:structuredClone(input.payload),payloadDigest:artifactPayloadDigest(input.payload),upstreamArtifactDigest:upstream,sourceDigest:input.sourceDigest,lineage:structuredClone(lineage),evidenceLinks:[...input.evidenceLinks],failures:structuredClone(input.failures),recordedBy:input.recordedBy,recordedAt:input.recordedAt,executionAuthorityEffect:"none" as const,activationEffect:"none" as const};return{...body,artifactDigest:onboardingJourneyDigest(body)};}
 private signerIdentity():TrustedReleaseSignerIdentity|null{return this.trustedReleaseSigner?{signerKeyId:this.trustedReleaseSigner.signerKeyId,publicKeyDigest:trustedReleasePublicKeyDigest(this.trustedReleaseSigner.publicKey)}:null;}
 private assertFailureResolutions(current:JourneySnapshot,input:JourneyArtifactInput,existing:JourneyArtifact|undefined,now:string){const receipts=input.failureResolutions??[];if(receipts.length&&!input.replaceExisting)throw new Error("Failure resolutions require explicit replacement of an originating stage.");const existingKeys=new Set(current.failureResolutions.map(r=>`${r.originatingArtifactDigest}:${r.controlId}`)),seen=new Set<string>();for(const receipt of receipts){const{receiptDigest,...body}=receipt,key=`${receipt.originatingArtifactDigest}:${receipt.controlId}`,historical=current.failureLedger.find(f=>f.originatingArtifactDigest===receipt.originatingArtifactDigest&&f.controlId===receipt.controlId&&f.stage===receipt.originatingStage);if(receiptDigest!==onboardingJourneyDigest(body)||receipt.schemaVersion!=="1.0"||receipt.journeyId!==current.journeyId||receipt.tenantId!==current.tenantId||receipt.sourceIdentityDigest!==current.sourceIdentityDigest||receipt.originatingStage!==input.stage||!identifier.test(receipt.resolverIdentity)||!receipt.resolutionDetail||receipt.evidenceLinks.length===0||receipt.evidenceLinks.some(link=>!link.startsWith(`artifact://${current.journeyId}/`))||receipt.executionAuthorityEffect!=="none"||receipt.activationEffect!=="none"||epoch(receipt.resolvedAt,"Failure resolution")>epoch(now,"Current")||secret.test(canonical(receipt)))throw new Error("Failure resolution receipt is forged, cross-journey, future-issued or malformed.");if(!historical)throw new Error("Failure resolution does not bind an exact historical failure.");if(epoch(receipt.resolvedAt,"Failure resolution")<epoch(historical.disclosedAt,"Failure disclosure"))throw new Error("Failure resolution predates its originating failure.");if(existingKeys.has(key)||seen.has(key))throw new Error("Historical failure has a duplicate resolution.");seen.add(key);}if(existing){const unresolved=failureState(current).unresolved.filter(f=>f.originatingArtifactDigest===existing.artifactDigest);for(const failure of unresolved)if(!seen.has(`${failure.originatingArtifactDigest}:${failure.controlId}`))throw new Error("Replacing an artifact cannot erase an unresolved historical failure without an exact resolution receipt.");}return structuredClone(receipts);}
 private decisions(input:JourneyArtifactInput){if(input.stage==="cf027-authoring")return(input.payload as CleanPackageAuthoringSnapshot).metrics.explicitDecisionCount;if(input.stage==="cf026-package-import")return 21;if(input.stage==="cf041-semantic-review")return(input.payload as SdkSemanticDraftSnapshot).metrics.explicitDecisions;return 0;}
 private reused(current:JourneySnapshot,input:JourneyArtifactInput){if(input.stage==="cf026-package-import")return Math.min(21,(current.artifacts["cf027-authoring"]?.payload as CleanPackageAuthoringSnapshot|undefined)?.metrics.explicitDecisionCount??0);if(input.stage==="cf041-semantic-review")return Math.min((input.payload as SdkSemanticDraftSnapshot).metrics.explicitDecisions,(current.artifacts["cf036-sdk-work-pack"]?.payload as SdkImplementationWorkPack|undefined)?.explicitReviews??0);return 0;}
 private insert(snapshot:JourneySnapshot,eventType:JourneyEvent["eventType"],detail:string){this.db.exec("BEGIN IMMEDIATE");try{const committed=this.bindEvent(snapshot,eventType,detail);this.db.prepare("INSERT INTO onboarding_journeys VALUES(?,?,?,?,?)").run(committed.journeyId,committed.tenantId,committed.sourceIdentity,JSON.stringify(committed),committed.journeyDigest);this.db.prepare("INSERT INTO onboarding_journey_revisions VALUES(?,?,?,?)").run(committed.journeyId,committed.revision,JSON.stringify(committed),committed.journeyDigest);this.insertEvent(committed,eventType,detail);this.db.exec("COMMIT");return committed;}catch(error){this.db.exec("ROLLBACK");throw error;}}
 private update(current:JourneySnapshot,updated:JourneySnapshot,eventType:JourneyEvent["eventType"],detail:string){this.db.exec("BEGIN IMMEDIATE");try{this.validateEventHistory(current);const committed=this.bindEvent(updated,eventType,detail);const result=this.db.prepare("UPDATE onboarding_journeys SET snapshot_json=?,journey_digest=? WHERE journey_id=? AND journey_digest=?").run(JSON.stringify(committed),committed.journeyDigest,current.journeyId,current.journeyDigest);if(Number(result.changes)!==1)throw new Error("Journey changed concurrently.");this.db.prepare("INSERT INTO onboarding_journey_revisions VALUES(?,?,?,?)").run(committed.journeyId,committed.revision,JSON.stringify(committed),committed.journeyDigest);this.insertEvent(committed,eventType,detail);this.db.exec("COMMIT");return committed;}catch(error){this.db.exec("ROLLBACK");throw error;}}
 private eventBody(snapshot:JourneySnapshot,eventType:JourneyEvent["eventType"],detail:string,sequence:number):Omit<JourneyEvent,"eventDigest">{return{sequence,journeyId:snapshot.journeyId,eventType,revision:snapshot.revision,statePayloadDigest:onboardingJourneyDigest(journeyStatePayload(snapshot)),previousEventDigest:snapshot.eventHeadDigest,detail,occurredAt:snapshot.updatedAt};}
 private bindEvent(snapshot:JourneySnapshot,eventType:JourneyEvent["eventType"],detail:string){assertHistoryCapacity(snapshot.eventCount,CUSTOMER_LOCAL_RESOURCE_LIMITS.journeyEvents,"Onboarding journey");const sequence=(this.db.prepare("SELECT COALESCE(MAX(sequence),0)+1 AS n FROM onboarding_journey_events").get() as {n:number}).n,body=this.eventBody(snapshot,eventType,detail,sequence),eventDigest=onboardingJourneyDigest(body);return finalize({...journeyPayload(snapshot),eventCount:snapshot.eventCount+1,eventHeadDigest:eventDigest});}
 private insertEvent(snapshot:JourneySnapshot,eventType:JourneyEvent["eventType"],detail:string){const sequence=(this.db.prepare("SELECT COALESCE(MAX(sequence),0)+1 AS n FROM onboarding_journey_events").get() as {n:number}).n,preEventSnapshot=finalize({...journeyPayload(snapshot),eventCount:snapshot.eventCount-1,eventHeadDigest:(this.db.prepare("SELECT event_digest FROM onboarding_journey_events WHERE journey_id=? ORDER BY sequence DESC LIMIT 1").get(snapshot.journeyId) as {event_digest:string}|undefined)?.event_digest??null}),body=this.eventBody(preEventSnapshot,eventType,detail,sequence),eventDigest=onboardingJourneyDigest(body);if(eventDigest!==snapshot.eventHeadDigest)throw new Error("Journey event binding is inconsistent with committed state.");this.db.prepare("INSERT INTO onboarding_journey_events(journey_id,event_type,revision,journey_digest,previous_event_digest,detail,occurred_at,event_digest) VALUES(?,?,?,?,?,?,?,?)").run(snapshot.journeyId,eventType,snapshot.revision,body.statePayloadDigest,body.previousEventDigest,detail,snapshot.updatedAt,eventDigest);}
 private validateEventHistory(snapshot:JourneySnapshot){const rows=this.db.prepare("SELECT * FROM onboarding_journey_events WHERE journey_id=? ORDER BY sequence").all(snapshot.journeyId) as Array<{sequence:number;journey_id:string;event_type:JourneyEvent["eventType"];revision:number;journey_digest:string;previous_event_digest:string|null;detail:string;occurred_at:string;event_digest:string}>;let previous:string|null=null;const events=rows.map(row=>{const body={sequence:row.sequence,journeyId:row.journey_id,eventType:row.event_type,revision:row.revision,statePayloadDigest:row.journey_digest,previousEventDigest:row.previous_event_digest,detail:row.detail,occurredAt:row.occurred_at};if(row.journey_id!==snapshot.journeyId||row.previous_event_digest!==previous||row.event_digest!==onboardingJourneyDigest(body))throw new Error("Journey event chain failed integrity validation.");previous=row.event_digest;return{...body,eventDigest:row.event_digest};});if(events.length!==snapshot.eventCount||previous!==snapshot.eventHeadDigest)throw new Error("Journey event history is truncated, inserted, reordered or inconsistent with current state.");const head=events.at(-1);if(!head||head.revision!==snapshot.revision||head.statePayloadDigest!==onboardingJourneyDigest(journeyStatePayload(snapshot)))throw new Error("Journey event head does not bind the current snapshot state.");return events;}
}

export function validateOnboardingJourneyDatabase(path:string,tenantId:string){
 const db=new DatabaseSync(path,{readOnly:true});
 try{
  const currentRows=db.prepare("SELECT journey_id,tenant_id,source_identity,snapshot_json,journey_digest FROM onboarding_journeys ORDER BY journey_id").all() as Array<{journey_id:string;tenant_id:string;source_identity:string;snapshot_json:string;journey_digest:string}>;
  const validateSnapshot=(snapshot:JourneySnapshot,rowDigest:string)=>{const{journeyDigest,...body}=snapshot;if(snapshot.schemaVersion!=="1.2"||snapshot.tenantId!==tenantId||snapshot.journeyId.length===0||snapshot.sourceIdentityDigest!==onboardingJourneySourceDigest({journeyId:snapshot.journeyId,tenantId:snapshot.tenantId,sourceIdentity:snapshot.sourceIdentity})||journeyDigest!==rowDigest||journeyDigest!==onboardingJourneyDigest(body))throw new Error("Onboarding stored snapshot failed full digest or scope validation.");for(const artifact of Object.values(snapshot.artifacts)){if(!artifact)continue;const{artifactDigest,...artifactBody}=artifact,{lineageDigest,...lineageBody}=artifact.lineage;if(artifact.tenantId!==tenantId||artifact.journeyId!==snapshot.journeyId||artifact.sourceDigest!==snapshot.sourceIdentityDigest||artifact.payloadDigest!==artifactPayloadDigest(artifact.payload)||artifactDigest!==onboardingJourneyDigest(artifactBody)||lineageDigest!==onboardingJourneyDigest(lineageBody))throw new Error("Onboarding stored artifact or lineage failed full integrity validation.");}return snapshot;};
  for(const row of currentRows){if(row.tenant_id!==tenantId)throw new Error("Onboarding database contains a cross-tenant row.");const current=validateSnapshot(JSON.parse(row.snapshot_json) as JourneySnapshot,row.journey_digest);if(current.journeyId!==row.journey_id||current.sourceIdentity!==row.source_identity)throw new Error("Onboarding current-row identity is inconsistent.");const revisions=db.prepare("SELECT revision,snapshot_json,journey_digest FROM onboarding_journey_revisions WHERE journey_id=? ORDER BY revision").all(row.journey_id) as Array<{revision:number;snapshot_json:string;journey_digest:string}>,byRevision=new Map<number,JourneySnapshot>();if(revisions.length!==current.revision)throw new Error("Onboarding revision history is truncated or inserted.");for(const [index,revision] of revisions.entries()){if(revision.revision!==index+1)throw new Error("Onboarding revision sequence is non-contiguous.");const snapshot=validateSnapshot(JSON.parse(revision.snapshot_json) as JourneySnapshot,revision.journey_digest);if(snapshot.journeyId!==row.journey_id||snapshot.revision!==revision.revision)throw new Error("Onboarding revision identity is inconsistent.");byRevision.set(revision.revision,snapshot);}if(canonical(byRevision.get(current.revision))!==canonical(current))throw new Error("Onboarding current snapshot does not equal its latest immutable revision.");const events=db.prepare("SELECT * FROM onboarding_journey_events WHERE journey_id=? ORDER BY sequence").all(row.journey_id) as Array<{sequence:number;journey_id:string;event_type:JourneyEvent["eventType"];revision:number;journey_digest:string;previous_event_digest:string|null;detail:string;occurred_at:string;event_digest:string}>;let previous:string|null=null;for(const [index,event] of events.entries()){const revision=byRevision.get(event.revision),body={sequence:event.sequence,journeyId:event.journey_id,eventType:event.event_type,revision:event.revision,statePayloadDigest:event.journey_digest,previousEventDigest:event.previous_event_digest,detail:event.detail,occurredAt:event.occurred_at};if(!revision||event.journey_id!==row.journey_id||event.previous_event_digest!==previous||event.event_digest!==onboardingJourneyDigest(body)||event.journey_digest!==onboardingJourneyDigest(journeyStatePayload(revision))||event.sequence<1||(index>0&&event.sequence<=events[index-1]!.sequence))throw new Error("Onboarding event chain or revision binding failed full integrity validation.");previous=event.event_digest;}if(events.length!==current.eventCount||previous!==current.eventHeadDigest||events.at(-1)?.revision!==current.revision)throw new Error("Onboarding current event head is inconsistent with the current snapshot.");}
  const orphanRevisions=(db.prepare("SELECT COUNT(*) n FROM onboarding_journey_revisions r LEFT JOIN onboarding_journeys j ON j.journey_id=r.journey_id WHERE j.journey_id IS NULL").get() as {n:number}).n,orphanEvents=(db.prepare("SELECT COUNT(*) n FROM onboarding_journey_events e LEFT JOIN onboarding_journeys j ON j.journey_id=e.journey_id WHERE j.journey_id IS NULL").get() as {n:number}).n;if(orphanRevisions||orphanEvents)throw new Error("Onboarding database contains orphaned history.");return{journeys:currentRows.length,valid:true as const};
 }finally{db.close();}
}

function same(left:string|undefined,right:string){if(!left)return false;return timingSafeEqual(createHash("sha256").update(left).digest(),createHash("sha256").update(right).digest());}
function error(reply:FastifyReply,value:unknown){reply.code(400);return{error:redactResourceError(value,"Journey operation failed.")};}
export function createCustomerLocalOnboardingJourneySidecar(input:{journey:DurableCustomerLocalOnboardingJourney;tenantId:string;accessToken:string}):FastifyInstance{if(input.accessToken.length<16||!identifier.test(input.tenantId))throw new Error("Journey sidecar configuration is invalid.");const app=Fastify({logger:false,bodyLimit:10_000_000}),auth=async(request:FastifyRequest,reply:FastifyReply)=>{if(!same(typeof request.headers["x-capability-sidecar-token"]==="string"?request.headers["x-capability-sidecar-token"]:undefined,input.accessToken))await reply.code(401).send({error:"Unauthorized"});},id=(request:FastifyRequest)=>{const value=(request.params as {journeyId?:unknown}).journeyId;if(typeof value!=="string"||!identifier.test(value))throw new Error("Journey ID is invalid.");return value;};app.get("/health",async()=>({status:"ok",boundary:"customer-local-onboarding-journey"}));app.post("/v1/journeys",{preHandler:auth},async(request,reply)=>{try{return input.journey.start({...request.body as {journeyId:string;sourceIdentity:string;recordedAt:string},tenantId:input.tenantId});}catch(e){return error(reply,e);}});app.get("/v1/journeys/:journeyId",{preHandler:auth},async(request,reply)=>{try{return input.journey.read(id(request),input.tenantId);}catch(e){return error(reply,e);}});app.post("/v1/journeys/:journeyId/artifacts",{preHandler:auth},async(request,reply)=>{try{return input.journey.attach(id(request),input.tenantId,request.body as JourneyArtifactInput);}catch(e){return error(reply,e);}});app.post("/v1/journeys/:journeyId/restart",{preHandler:auth},async(request,reply)=>{try{return input.journey.observeRestart(id(request),input.tenantId);}catch(e){return error(reply,e);}});app.post("/v1/journeys/:journeyId/rollback",{preHandler:auth},async(request,reply)=>{try{return input.journey.rollback(id(request),input.tenantId,request.body as Parameters<DurableCustomerLocalOnboardingJourney["rollback"]>[2]);}catch(e){return error(reply,e);}});app.get("/v1/journeys/:journeyId/events",{preHandler:auth},async(request,reply)=>{try{return{events:input.journey.events(id(request),input.tenantId)};}catch(e){return error(reply,e);}});app.get("/v1/journeys/:journeyId/export",{preHandler:auth},async(request,reply)=>{try{return input.journey.exportRedacted(id(request),input.tenantId);}catch(e){return error(reply,e);}});return app;}
