import { chmodSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { assertHttpBindingFactoryResultIntegrity, type HttpBindingFactoryResult } from "./http-binding-factory.js";
import { sdkWorkPackDigest, type SdkImplementationWorkPack } from "./customer-local-sdk-work-pack.js";
import { sdkSemanticDigest, type ConfirmedFact, type SdkSemanticContract, type SemanticPredicate, type ValueExpression } from "./customer-local-sdk-semantic-compiler.js";

export const CUSTOMER_LOCAL_SDK_SEMANTIC_DRAFTING_VERSION = "1.0" as const;
export const SDK_SEMANTIC_QUESTION_ORDER = ["parameter-mapping", "credentials-and-scopes", "stable-identity", "idempotency-and-conflict", "retry-and-reconciliation", "observer-independence", "outcome-proof", "pagination-completeness", "error-rate-policy"] as const;
export type SdkSemanticQuestionId = typeof SDK_SEMANTIC_QUESTION_ORDER[number];
const identifier=/^[a-zA-Z][a-zA-Z0-9_.-]{1,119}$/;
const digest=/^[a-f0-9]{64}$/;
const forbidden=/\b(?:eval|Function|require|import\s*\(|prototype|constructor|__proto__|child_process|exec|spawn)\b|(?:bearer|password|secret|token|api[_ -]?key)\s*[:=]\s*[^\s,;}]+/i;
const canonical=(value:unknown):string=>{if(value===undefined)return"undefined";if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value!==null&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;return JSON.stringify(value);};
export const sdkSemanticDraftDigest=(value:unknown)=>sdkSemanticDigest(value);
const clone=<T>(value:T):T=>structuredClone(value);

export interface ReviewedSdkWorkflowOutcome {
  schemaVersion:"1.0"; workflowId:string; summary:string; requiredOutcome:string; sourceDigest:string;
  inputFields:Array<{name:string;type:"string"|"number"|"boolean";sourcePointer:string}>;
  reviewedBy:string; reviewedAt:string; summarySourcePointer:string; outcomeSourcePointer:string;
}
export interface SdkSemanticDraftStartInput {schemaVersion:"1.0";sessionId:string;providerId:string;workPack:SdkImplementationWorkPack;factoryResult:HttpBindingFactoryResult;workflow:ReviewedSdkWorkflowOutcome}
export interface ExtractedSemanticFact {factId:string;semanticClass:SdkSemanticQuestionId;value:unknown;status:"extracted-source-fact";sourcePointer:string;sourceDigest:string;providerId:string}
export interface SdkSemanticDraftQuestion {questionId:SdkSemanticQuestionId;dependsOn:SdkSemanticQuestionId[];prompt:string;why:string;requiredAnswerShape:string;status:"blocked-by-dependency"|"answer-required"|"answered";sourceHints:ExtractedSemanticFact[]}
export interface ConfirmedSemanticAnswer {questionId:SdkSemanticQuestionId;value:unknown;status:"explicitly-confirmed";sourcePointer:string;reviewerAlias:string;reviewedAt:string;sourceDigest:string;answerDigest:string}
export interface SdkSemanticDraftSnapshot {
  schemaVersion:"1.0";sessionId:string;providerId:string;inputDigest:string;workPackDigest:string;factoryResultDigest:string;workflowSourceDigest:string;
  state:"questions-open"|"review-ready"|"reviewed-contract-ready";revision:number;extractedFacts:ExtractedSemanticFact[];questions:SdkSemanticDraftQuestion[];answers:ConfirmedSemanticAnswer[];
  partialContract:Partial<SdkSemanticContract>;blockers:Array<{semanticClass:SdkSemanticQuestionId;detail:string;exactRequiredWork:string}>;dependencyDepth:number;
  metrics:{extractedFacts:number;questions:number;explicitDecisions:number;blockers:number;generatedConfigObjects:number;generatedExecutableCodeLines:0;manualExecutableCodeFiles:0;interventionPoints:number};
  reviewedContract?:SdkSemanticContract;executionAuthorityEffect:"none";activationEffect:"none";createdAt:string;updatedAt:string;snapshotDigest:string;
}
export interface SdkSemanticDraftAnswerInput {sessionId:string;expectedInputDigest:string;expectedSnapshotDigest:string;questionId:SdkSemanticQuestionId;value:unknown;sourcePointer:string;reviewerAlias:string;reviewedAt:string;sourceDigest:string;dryRun?:boolean}
export interface SdkSemanticDraftReviewInput {sessionId:string;expectedInputDigest:string;expectedSnapshotDigest:string;reviewerAlias:string;reviewedAt:string;expiresAt:string;dryRun?:boolean}
export interface SdkSemanticDraftEvent {sequence:number;sessionId:string;eventType:"draft-started"|"answer-confirmed"|"contract-reviewed";snapshotDigest:string;occurredAt:string}

function assertText(value:string,label:string,max=2_000){if(!value.trim()||value.length>max||forbidden.test(value))throw new Error(`${label} is empty, oversized or injection-shaped.`);}
function assertId(value:string,label:string){if(!identifier.test(value))throw new Error(`${label} is invalid.`);}
function payload<T extends {snapshotDigest:string}>(value:T){const{snapshotDigest:_ignored,...rest}=value;return rest;}
function finalSnapshot(value:Omit<SdkSemanticDraftSnapshot,"snapshotDigest">):SdkSemanticDraftSnapshot{return{...value,snapshotDigest:sdkSemanticDraftDigest(value)};}
function assertSnapshot(value:SdkSemanticDraftSnapshot){if(value.snapshotDigest!==sdkSemanticDraftDigest(payload(value)))throw new Error("SDK semantic draft snapshot failed integrity validation.");}
function assertSource(input:SdkSemanticDraftStartInput){
 assertHttpBindingFactoryResultIntegrity(input.factoryResult);if(input.schemaVersion!=="1.0"||input.workflow.schemaVersion!=="1.0"||input.providerId!==input.workPack.providerId||input.workPack.factoryResultDigest!==input.factoryResult.resultDigest||input.workPack.workPackDigest!==sdkWorkPackDigest((({workPackDigest:_d,...rest})=>rest)(input.workPack))||input.factoryResult.status!=="review-required"||!input.factoryResult.actionBinding||!input.factoryResult.observerBinding)throw new Error("SDK semantic drafting source is stale, blocked or cross-provider substituted.");
 for(const value of [input.sessionId,input.providerId,input.workflow.workflowId,input.workflow.reviewedBy])assertId(value,"SDK semantic drafting identifier");for(const value of [input.workflow.sourceDigest,input.workPack.sdkSourceDigest,input.factoryResult.resultDigest])if(!digest.test(value))throw new Error("SDK semantic drafting source digest is invalid.");
 assertText(input.workflow.summary,"Workflow summary");assertText(input.workflow.requiredOutcome,"Required outcome");assertText(input.workflow.summarySourcePointer,"Workflow summary source pointer",500);assertText(input.workflow.outcomeSourcePointer,"Workflow outcome source pointer",500);if(Date.parse(input.workflow.reviewedAt)<=0||input.workflow.inputFields.length===0)throw new Error("Workflow review or input fields are missing.");
 const names=new Set<string>();for(const field of input.workflow.inputFields){assertId(field.name,"Workflow input field");assertText(field.sourcePointer,"Workflow input source pointer",500);if(names.has(field.name))throw new Error("Workflow input fields are ambiguous.");names.add(field.name);}
 if(forbidden.test(canonical(input)))throw new Error("SDK semantic drafting source contains injection or credential-shaped content.");
}
function extracted(input:SdkSemanticDraftStartInput):ExtractedSemanticFact[]{const facts:ExtractedSemanticFact[]=[];const add=(factId:string,semanticClass:SdkSemanticQuestionId,value:unknown,sourcePointer:string,sourceDigest:string)=>facts.push({factId,semanticClass,value:clone(value),status:"extracted-source-fact",sourcePointer,sourceDigest,providerId:input.providerId});
 for(const role of input.workPack.roles){const base=`sdk:${role.review.role}`;add(`${base}:method`,`parameter-mapping`,{role:role.review.role,module:role.method.module,className:role.method.className,methodName:role.method.methodName,overloadId:role.method.overloadId,methodDigest:role.methodDigest},role.method.sourcePointer,input.workPack.sdkSourceDigest);add(`${base}:parameters`,`parameter-mapping`,role.method.parameters,`${role.method.sourcePointer}/parameters`,input.workPack.sdkSourceDigest);add(`${base}:auth`,`credentials-and-scopes`,role.method.authAliasRequirements,`${role.method.sourcePointer}/auth`,input.workPack.sdkSourceDigest);add(`${base}:retry`,`retry-and-reconciliation`,{retryCandidate:role.method.retryCandidate,idempotencyCandidate:role.method.idempotencyCandidate,errorTypes:role.method.errorTypes},role.method.sourcePointer,input.workPack.sdkSourceDigest);add(`${base}:pagination`,`pagination-completeness`,role.method.pagination,`${role.method.sourcePointer}/pagination`,input.workPack.sdkSourceDigest);add(`${base}:return`,`outcome-proof`,role.method.returnType,`${role.method.sourcePointer}/return`,input.workPack.sdkSourceDigest);}
 const action=input.factoryResult.actionBinding!,observer=input.factoryResult.observerBinding!;add("cf:action-declaration","credentials-and-scopes",{operation:action.operation,credentialAlias:action.credentialAlias,targetAlias:action.targetAlias,retry:action.retry,authorityPolicy:action.authorityPolicy},action.provenance.operationPointer,input.factoryResult.resultDigest);add("cf:observer-declaration","observer-independence",{operation:observer.operation,credentialAlias:observer.credentialAlias,sourceId:observer.sourceId,driverId:observer.driverId,actionResponseEligibleAsProof:observer.actionResponseEligibleAsProof},observer.provenance.operationPointer,input.factoryResult.resultDigest);add("cf:outcome-declaration","outcome-proof",{predicates:observer.predicates,duplicateCheck:observer.duplicateCheck,collateralChecks:observer.collateralChecks,freshness:observer.freshness},`${observer.provenance.operationPointer}/outcome`,input.factoryResult.resultDigest);add("workflow:inputs","parameter-mapping",input.workflow.inputFields,input.workflow.summarySourcePointer,input.workflow.sourceDigest);add("workflow:outcome","outcome-proof",input.workflow.requiredOutcome,input.workflow.outcomeSourcePointer,input.workflow.sourceDigest);return facts;}
const dependencies:Record<SdkSemanticQuestionId,SdkSemanticQuestionId[]>={"parameter-mapping":[],"credentials-and-scopes":[],"stable-identity":["parameter-mapping"],"idempotency-and-conflict":["stable-identity"],"retry-and-reconciliation":["idempotency-and-conflict"],"observer-independence":["credentials-and-scopes"],"outcome-proof":["stable-identity","observer-independence"],"pagination-completeness":["outcome-proof"],"error-rate-policy":["retry-and-reconciliation","pagination-completeness"]};
const wording:Record<SdkSemanticQuestionId,[string,string,string]>={
 "parameter-mapping":["For every required parameter of each reviewed SDK method, which confirmed workflow input or trusted-context key supplies it, and which bounded scalar conversion applies?","Names and types can be extracted, but their business meaning cannot.","{mappings:[{role,parameter,source,key,convert}]} with exact one-to-one coverage"],
 "credentials-and-scopes":["Confirm separate action and observer credential aliases and the exact least-privilege scope string for each.","An SDK alias candidate or prior HTTP declaration cannot silently authorize an SDK operation.","{action:{alias,exactScope},observer:{alias,exactScope}}"],
 "stable-identity":["Which already-known workflow input or trusted-context value is the stable external identity, and how must collisions be handled?","CF must reconcile the same real object without guessing identity.","{source,key,convert,collisionPolicy:'reject-conflict'}"],
 "idempotency-and-conflict":["Which confirmed value is the idempotency key, and which confirmed values define whether reuse is a conflict?","A provider hint is not proof that retries cannot duplicate or overwrite work.","{key:{source,key,convert},conflictIdentity:[...],reconcileBeforeRetry:true,blindRetryAllowed:false}"],
 "retry-and-reconciliation":["Confirm the readback role and exact not-found/multiple-result classifications before any retry.","Lost responses must be reconciled externally rather than retried blindly.","{role:'reconciliation-readback',notFoundClassification:'not-started',multipleClassification:'duplicate'}"],
 "observer-independence":["Confirm the independent observation source, separate authentication, and different action/observer method binding.","The action response cannot prove its own external effect.","{role:'independent-observer',sourceId,authIndependent:true,differentMethodFromAction:true}"],
 "outcome-proof":["Define exact success predicates, exactly-one duplicate check, collateral-state predicates, and a trusted freshness signal.","A business outcome is not executable proof until every observable condition is explicit.","{predicates:[...],duplicate:{collectionPath,expectedCount:1},collateral:[...],freshness:{path,maximumAgeSeconds,notBefore:'operation-start'}}"],
 "pagination-completeness":["For reconciliation and observation, confirm whether results are unpaginated or how all cursors are exhausted within a bounded maximum.","A partial page can falsely hide duplicates or failures.","{roles:[{role,mode,maximumPages},...],complete:true}"],
 "error-rate-policy":["Confirm bounded timeout, request rate, maximum attempts, retryable errors and terminal errors for this exact provider version.","SDK exception names and retry hints do not establish safe operational policy.","{timeoutMilliseconds,maximumRequestsPerMinute,maximumAttempts,retryableErrors,terminalErrors}"],
};
function questionList(facts:ExtractedSemanticFact[],answers:ConfirmedSemanticAnswer[]):SdkSemanticDraftQuestion[]{const answered=new Set(answers.map(x=>x.questionId));return SDK_SEMANTIC_QUESTION_ORDER.map(questionId=>{const [prompt,why,shape]=wording[questionId],deps=dependencies[questionId];return{questionId,dependsOn:[...deps],prompt,why,requiredAnswerShape:shape,status:answered.has(questionId)?"answered":deps.every(x=>answered.has(x))?"answer-required":"blocked-by-dependency",sourceHints:facts.filter(x=>x.semanticClass===questionId)};});}
const expression=(value:unknown,fact:ConfirmedFact):ValueExpression=>{const item=value as Record<string,unknown>;if(!item||!(["workflow-input","trusted-context"] as unknown[]).includes(item.source)||typeof item.key!=="string"||!identifier.test(item.key)||!(["identity","string","number","boolean"] as unknown[]).includes(item.convert))throw new Error("Expression answer is incomplete or unsupported.");return{source:item.source as ValueExpression["source"],key:item.key,convert:item.convert as ValueExpression["convert"],fact};};
function answerFact(answer:ConfirmedSemanticAnswer):ConfirmedFact{return{provenance:"engineer-confirmed",confirmedBy:answer.reviewerAlias,confirmedAt:answer.reviewedAt,sourcePointer:answer.sourcePointer};}
function record(value:unknown,label:string):Record<string,unknown>{if(!value||typeof value!=="object"||Array.isArray(value)||forbidden.test(canonical(value)))throw new Error(`${label} answer is low-information, malformed or injection-shaped.`);return value as Record<string,unknown>;}
function array(value:unknown,label:string):unknown[]{if(!Array.isArray(value)||value.length===0)throw new Error(`${label} answer requires a non-empty list.`);return value;}
function string(value:unknown,label:string):string{if(typeof value!=="string"||!value.trim()||value.length>500||forbidden.test(value))throw new Error(`${label} answer is missing or unsafe.`);return value;}
function validateAnswer(questionId:SdkSemanticQuestionId,value:unknown,source:SdkSemanticDraftStartInput):void{const v=record(value,questionId),roles=new Map(source.workPack.roles.map(x=>[x.review.role,x]));
 if(questionId==="parameter-mapping"){const mappings=array(v.mappings,"Parameter mappings").map(x=>record(x,"Parameter mapping"));const expected=source.workPack.roles.flatMap(role=>role.method.parameters.filter(p=>p.required).map(p=>`${role.review.role}:${p.name}`)).sort(),actual=mappings.map(x=>`${string(x.role,"Mapping role")}:${string(x.parameter,"Mapping parameter")}`).sort();if(canonical(expected)!==canonical(actual)||new Set(actual).size!==actual.length)throw new Error("Parameter answer must cover each required reviewed SDK parameter exactly once.");for(const item of mappings){const role=roles.get(item.role as SdkImplementationWorkPack["roles"][number]["review"]["role"]);if(!role||!role.method.parameters.some(p=>p.name===item.parameter))throw new Error("Parameter answer references a stale or cross-provider method.");const e=expression(item,{provenance:"engineer-confirmed",confirmedBy:"validationOnly",confirmedAt:"2026-01-01T00:00:00Z",sourcePointer:"validation"});if(e.source==="workflow-input"&&!source.workflow.inputFields.some(field=>field.name===e.key))throw new Error("Parameter mapping cites an unreviewed workflow input.");}}
 else if(questionId==="credentials-and-scopes"){const action=record(v.action,"Action credential"),observer=record(v.observer,"Observer credential"),aa=string(action.alias,"Action alias"),oa=string(observer.alias,"Observer alias"),as=string(action.exactScope,"Action scope"),os=string(observer.exactScope,"Observer scope");if(aa===oa||!identifier.test(aa)||!identifier.test(oa)||as===os||[as,os].some(scope=>scope.includes("*")||/\b(?:admin|all)\b/i.test(scope)))throw new Error("Credential aliases and exact scopes must be explicit, separate and non-widening.");}
 else if(questionId==="stable-identity"){const e=expression(v,{provenance:"engineer-confirmed",confirmedBy:"validationOnly",confirmedAt:"2026-01-01T00:00:00Z",sourcePointer:"validation"});if(e.source==="workflow-input"&&!source.workflow.inputFields.some(field=>field.name===e.key))throw new Error("Stable identity is not an existing reviewed workflow input.");if(v.collisionPolicy!=="reject-conflict")throw new Error("Stable identity must reject conflicts.");}
 else if(questionId==="idempotency-and-conflict"){expression(record(v.key,"Idempotency key"),{provenance:"engineer-confirmed",confirmedBy:"validationOnly",confirmedAt:"2026-01-01T00:00:00Z",sourcePointer:"validation"});array(v.conflictIdentity,"Conflict identity").forEach(x=>expression(x,{provenance:"engineer-confirmed",confirmedBy:"validationOnly",confirmedAt:"2026-01-01T00:00:00Z",sourcePointer:"validation"}));if(v.reconcileBeforeRetry!==true||v.blindRetryAllowed!==false)throw new Error("Unsafe retry weakening is forbidden.");}
 else if(questionId==="retry-and-reconciliation"){if(v.role!=="reconciliation-readback"||v.notFoundClassification!=="not-started"||v.multipleClassification!=="duplicate")throw new Error("Reconciliation classifications are incomplete or unsafe.");}
 else if(questionId==="observer-independence"){const sourceId=string(v.sourceId,"Observer source");if(v.role!=="independent-observer"||v.authIndependent!==true||v.differentMethodFromAction!==true||!identifier.test(sourceId)||sourceId===source.factoryResult.actionBinding!.driverId)throw new Error("Independent observer proof is incomplete or fake.");}
 else if(questionId==="outcome-proof"){for(const key of ["predicates","collateral"] as const)for(const item of array(v[key],key)){const p=record(item,"Outcome predicate");string(p.key,"Predicate key");if(!Array.isArray(p.path)||p.path.length===0||!(["exists","equals-input","equals-confirmed","count-equals"] as unknown[]).includes(p.operator))throw new Error("Outcome predicate is incomplete.");}const duplicate=record(v.duplicate,"Duplicate check"),fresh=record(v.freshness,"Freshness");if(!Array.isArray(duplicate.collectionPath)||duplicate.collectionPath.length===0||duplicate.expectedCount!==1||!Array.isArray(fresh.path)||fresh.path.length===0||typeof fresh.maximumAgeSeconds!=="number"||fresh.maximumAgeSeconds<1||fresh.notBefore!=="operation-start")throw new Error("Duplicate or freshness proof is incomplete.");}
 else if(questionId==="pagination-completeness"){const entries=array(v.roles,"Pagination roles").map(x=>record(x,"Pagination role"));if(v.complete!==true||entries.length!==2||new Set(entries.map(x=>x.role)).size!==2||!entries.every(x=>(x.role==="reconciliation-readback"||x.role==="independent-observer")&&(x.mode==="not-paginated"||x.mode==="complete-cursor")&&Number.isInteger(x.maximumPages)&&Number(x.maximumPages)>=1))throw new Error("Pagination completeness is omitted or ambiguous.");}
 else {if(typeof v.timeoutMilliseconds!=="number"||v.timeoutMilliseconds<100||v.timeoutMilliseconds>120_000||typeof v.maximumRequestsPerMinute!=="number"||v.maximumRequestsPerMinute<1||![1,2,3].includes(v.maximumAttempts as number)||!Array.isArray(v.retryableErrors)||!Array.isArray(v.terminalErrors)||v.terminalErrors.length===0)throw new Error("Error/rate policy is incomplete or unbounded.");for(const item of [...v.retryableErrors as unknown[],...v.terminalErrors as unknown[]])string(item,"Error name");}
}
function partialContract(source:SdkSemanticDraftStartInput,answers:ConfirmedSemanticAnswer[]):Partial<SdkSemanticContract>{const by=new Map(answers.map(x=>[x.questionId,x])),partial:Partial<SdkSemanticContract>={schemaVersion:"1.0",contractId:`${source.providerId}-semantic-draft`,providerId:source.providerId,sdkSourceDigest:source.workPack.sdkSourceDigest,workPackDigest:source.workPack.workPackDigest,roles:source.workPack.roles.map(x=>({role:x.review.role,methodDigest:x.methodDigest,fact:{provenance:"engineer-confirmed",confirmedBy:x.review.reviewerAlias,confirmedAt:x.review.reviewedAt,sourcePointer:x.method.sourcePointer}})),sourceDigest:sdkSemanticDraftDigest({workflow:source.workflow.sourceDigest,factory:source.factoryResult.resultDigest,workPack:source.workPack.workPackDigest}),executionAuthorityEffect:"none",activationEffect:"none"};
 const a=(id:SdkSemanticQuestionId)=>by.get(id);let answer=a("parameter-mapping");if(answer){const v=answer.value as {mappings:Array<Record<string,unknown>>},fact=answerFact(answer);partial.parameterMappings=v.mappings.map(x=>({role:x.role as SdkSemanticContract["parameterMappings"][number]["role"],parameter:x.parameter as string,expression:expression(x,fact),fact}));}answer=a("credentials-and-scopes");if(answer){const v=answer.value as {action:{alias:string;exactScope:string};observer:{alias:string;exactScope:string}},fact=answerFact(answer);partial.credentials={action:{...v.action,fact},observer:{...v.observer,fact}};}answer=a("stable-identity");if(answer){const fact=answerFact(answer);partial.stableIdentity={expression:expression(answer.value,fact),collisionPolicy:"reject-conflict",fact};}answer=a("idempotency-and-conflict");if(answer){const v=answer.value as {key:unknown;conflictIdentity:unknown[]},fact=answerFact(answer);partial.idempotency={expression:expression(v.key,fact),conflictIdentity:v.conflictIdentity.map(x=>expression(x,fact)),reconcileBeforeRetry:true,blindRetryAllowed:false,fact};}answer=a("retry-and-reconciliation");if(answer)partial.reconciliation={...(answer.value as Omit<SdkSemanticContract["reconciliation"],"fact">),fact:answerFact(answer)};answer=a("observer-independence");if(answer)partial.observer={...(answer.value as Omit<SdkSemanticContract["observer"],"fact">),fact:answerFact(answer)};answer=a("outcome-proof");if(answer){const v=answer.value as Record<string,unknown>,fact=answerFact(answer),predicate=(x:unknown):SemanticPredicate=>({...x as Omit<SemanticPredicate,"fact">,fact});partial.outcome={predicates:(v.predicates as unknown[]).map(predicate),duplicate:{...v.duplicate as Omit<SdkSemanticContract["outcome"]["duplicate"],"fact">,fact},collateral:(v.collateral as unknown[]).map(predicate),freshness:{...v.freshness as Omit<SdkSemanticContract["outcome"]["freshness"],"fact">,fact},fact};}answer=a("pagination-completeness");if(answer){const v=answer.value as Omit<SdkSemanticContract["pagination"],"fact"|"roles"> & {roles:Array<Omit<SdkSemanticContract["pagination"]["roles"][number],"fact">>},fact=answerFact(answer);partial.pagination={...v,roles:v.roles.map(x=>({...x,fact})),fact};}answer=a("error-rate-policy");if(answer)partial.policy={...(answer.value as Omit<SdkSemanticContract["policy"],"fact">),fact:answerFact(answer)};return partial;}
function blockers(answers:ConfirmedSemanticAnswer[]){const found=new Set(answers.map(x=>x.questionId));return SDK_SEMANTIC_QUESTION_ORDER.filter(x=>!found.has(x)).map(semanticClass=>({semanticClass,detail:`${semanticClass} has not been explicitly confirmed.`,exactRequiredWork:wording[semanticClass][0]}));}
function makeSnapshot(source:SdkSemanticDraftStartInput,inputDigest:string,facts:ExtractedSemanticFact[],answers:ConfirmedSemanticAnswer[],revision:number,createdAt:string,updatedAt:string,reviewedContract?:SdkSemanticContract):SdkSemanticDraftSnapshot{const remaining=blockers(answers),state:SdkSemanticDraftSnapshot["state"]=reviewedContract?"reviewed-contract-ready":remaining.length===0?"review-ready":"questions-open",questions=questionList(facts,answers);const base:Omit<SdkSemanticDraftSnapshot,"snapshotDigest">={schemaVersion:"1.0",sessionId:source.sessionId,providerId:source.providerId,inputDigest,workPackDigest:source.workPack.workPackDigest,factoryResultDigest:source.factoryResult.resultDigest,workflowSourceDigest:source.workflow.sourceDigest,state,revision,extractedFacts:facts,questions,answers,partialContract:partialContract(source,answers),blockers:remaining,dependencyDepth:5,metrics:{extractedFacts:facts.length,questions:questions.length,explicitDecisions:answers.length,blockers:remaining.length,generatedConfigObjects:1,generatedExecutableCodeLines:0,manualExecutableCodeFiles:0,interventionPoints:questions.length},...(reviewedContract?{reviewedContract}:{}),executionAuthorityEffect:"none",activationEffect:"none",createdAt,updatedAt};return finalSnapshot(base);}

export class DurableSdkSemanticDraftWorkflow{
 private readonly database:DatabaseSync;private readonly now:()=>string;
 constructor(databasePath=":memory:",options:{now?:()=>string}={}){if(databasePath!==":memory:")mkdirSync(dirname(databasePath),{recursive:true,mode:0o700});this.database=new DatabaseSync(databasePath);if(databasePath!==":memory:")chmodSync(databasePath,0o600);this.now=options.now??(()=>new Date().toISOString());this.database.exec(`CREATE TABLE IF NOT EXISTS sdk_semantic_drafts(session_id TEXT PRIMARY KEY,input_digest TEXT NOT NULL,source_json TEXT NOT NULL,snapshot_json TEXT NOT NULL,snapshot_digest TEXT NOT NULL);CREATE TABLE IF NOT EXISTS sdk_semantic_draft_events(sequence INTEGER PRIMARY KEY AUTOINCREMENT,session_id TEXT NOT NULL,event_type TEXT NOT NULL,snapshot_digest TEXT NOT NULL,occurred_at TEXT NOT NULL);`);}
 start(source:SdkSemanticDraftStartInput){assertSource(source);const inputDigest=sdkSemanticDraftDigest(source),existing=this.database.prepare("SELECT input_digest FROM sdk_semantic_drafts WHERE session_id=?").get(source.sessionId) as {input_digest:string}|undefined;if(existing){if(existing.input_digest!==inputDigest)throw new Error("Semantic draft session is already bound to different or stale source.");return this.read(source.sessionId);}const timestamp=this.now(),snapshot=makeSnapshot(source,inputDigest,extracted(source),[],1,timestamp,timestamp);this.database.exec("BEGIN IMMEDIATE");try{this.database.prepare("INSERT INTO sdk_semantic_drafts VALUES(?,?,?,?,?)").run(source.sessionId,inputDigest,JSON.stringify(source),JSON.stringify(snapshot),snapshot.snapshotDigest);this.event(source.sessionId,"draft-started",snapshot.snapshotDigest,timestamp);this.database.exec("COMMIT");}catch(error){this.database.exec("ROLLBACK");throw error;}return clone(snapshot);}
 answer(input:SdkSemanticDraftAnswerInput){assertId(input.sessionId,"Draft session");assertId(input.reviewerAlias,"Answer reviewer");assertText(input.sourcePointer,"Answer source pointer",500);if(!digest.test(input.sourceDigest)||Date.parse(input.reviewedAt)<=0)throw new Error("Answer provenance is incomplete.");const current=this.read(input.sessionId);if(current.inputDigest!==input.expectedInputDigest)throw new Error("Semantic answer belongs to a different source input.");if(current.reviewedContract)throw new Error("Reviewed semantic contract is immutable.");const source=this.source(input.sessionId);const expectedSource=new Set([source.workflow.sourceDigest,source.factoryResult.resultDigest,source.workPack.sdkSourceDigest,source.workPack.workPackDigest]);if(!expectedSource.has(input.sourceDigest))throw new Error("Semantic answer cites a stale, unknown or cross-provider source digest.");validateAnswer(input.questionId,input.value,source);const answerPayload={questionId:input.questionId,value:clone(input.value),status:"explicitly-confirmed" as const,sourcePointer:input.sourcePointer,reviewerAlias:input.reviewerAlias,reviewedAt:input.reviewedAt,sourceDigest:input.sourceDigest},answer={...answerPayload,answerDigest:sdkSemanticDraftDigest(answerPayload)};const existing=current.answers.find(x=>x.questionId===input.questionId);if(existing){if(existing.answerDigest!==answer.answerDigest)throw new Error("Semantic question already has a different explicit answer.");return current;}if(current.snapshotDigest!==input.expectedSnapshotDigest)throw new Error("Semantic answer is stale; reload the exact draft snapshot.");const deps=dependencies[input.questionId];if(!deps.every(id=>current.answers.some(x=>x.questionId===id)))throw new Error("Semantic answer attempted to bypass dependency order.");const updated=makeSnapshot(source,current.inputDigest,current.extractedFacts,[...current.answers,answer],current.revision+1,current.createdAt,this.now());if(input.dryRun)return updated;this.save(current,updated,"answer-confirmed");return clone(updated);}
 review(input:SdkSemanticDraftReviewInput){assertId(input.reviewerAlias,"Contract reviewer");if(Date.parse(input.reviewedAt)<=0||Date.parse(input.expiresAt)<=Date.parse(input.reviewedAt))throw new Error("Contract review time or expiry is invalid.");const current=this.read(input.sessionId);if(current.inputDigest!==input.expectedInputDigest||current.snapshotDigest!==input.expectedSnapshotDigest)throw new Error("Semantic contract review is stale.");if(current.blockers.length>0||current.answers.length!==SDK_SEMANTIC_QUESTION_ORDER.length)throw new Error("Semantic contract cannot be reviewed while questions remain.");if(current.reviewedContract)return current;const source=this.source(input.sessionId),partial=partialContract(source,current.answers);const reviewFact:ConfirmedFact={provenance:"engineer-confirmed",confirmedBy:input.reviewerAlias,confirmedAt:input.reviewedAt,sourcePointer:`draft://${input.sessionId}/final-review`};const contractPayload={...partial,contractId:`${source.providerId}-semantic-v1`,expiresAt:input.expiresAt,sourceDigest:sdkSemanticDraftDigest({draft:current.snapshotDigest,review:reviewFact})} as Omit<SdkSemanticContract,"contractDigest">,contract={...contractPayload,contractDigest:sdkSemanticDigest(contractPayload)};const updated=makeSnapshot(source,current.inputDigest,current.extractedFacts,current.answers,current.revision+1,current.createdAt,this.now(),contract);if(input.dryRun)return updated;this.save(current,updated,"contract-reviewed");return clone(updated);}
 read(sessionId:string){assertId(sessionId,"Draft session");const row=this.database.prepare("SELECT input_digest,snapshot_json,snapshot_digest FROM sdk_semantic_drafts WHERE session_id=?").get(sessionId) as {input_digest:string;snapshot_json:string;snapshot_digest:string}|undefined;if(!row)throw new Error("SDK semantic draft session does not exist.");const snapshot=JSON.parse(row.snapshot_json) as SdkSemanticDraftSnapshot;assertSnapshot(snapshot);if(snapshot.inputDigest!==row.input_digest||snapshot.snapshotDigest!==row.snapshot_digest)throw new Error("Durable semantic draft metadata is inconsistent.");return clone(snapshot);}
 events(sessionId:string):SdkSemanticDraftEvent[]{this.read(sessionId);return(this.database.prepare("SELECT sequence,session_id,event_type,snapshot_digest,occurred_at FROM sdk_semantic_draft_events WHERE session_id=? ORDER BY sequence").all(sessionId) as Array<{sequence:number;session_id:string;event_type:SdkSemanticDraftEvent["eventType"];snapshot_digest:string;occurred_at:string}>).map(x=>({sequence:x.sequence,sessionId:x.session_id,eventType:x.event_type,snapshotDigest:x.snapshot_digest,occurredAt:x.occurred_at}));}
 close(){this.database.close();}
 private source(sessionId:string){const row=this.database.prepare("SELECT source_json FROM sdk_semantic_drafts WHERE session_id=?").get(sessionId) as {source_json:string}|undefined;if(!row)throw new Error("SDK semantic draft source does not exist.");const source=JSON.parse(row.source_json) as SdkSemanticDraftStartInput;assertSource(source);return source;}
 private save(current:SdkSemanticDraftSnapshot,updated:SdkSemanticDraftSnapshot,eventType:SdkSemanticDraftEvent["eventType"]){this.database.exec("BEGIN IMMEDIATE");try{const result=this.database.prepare("UPDATE sdk_semantic_drafts SET snapshot_json=?,snapshot_digest=? WHERE session_id=? AND snapshot_digest=?").run(JSON.stringify(updated),updated.snapshotDigest,current.sessionId,current.snapshotDigest);if(Number(result.changes)!==1)throw new Error("Semantic draft changed concurrently.");this.event(current.sessionId,eventType,updated.snapshotDigest,updated.updatedAt);this.database.exec("COMMIT");}catch(error){this.database.exec("ROLLBACK");throw error;}}
 private event(sessionId:string,eventType:SdkSemanticDraftEvent["eventType"],snapshotDigest:string,occurredAt:string){this.database.prepare("INSERT INTO sdk_semantic_draft_events(session_id,event_type,snapshot_digest,occurred_at) VALUES(?,?,?,?)").run(sessionId,eventType,snapshotDigest,occurredAt);}
}
