import fs from "node:fs";
import path from "node:path";
import { DurableCustomerLocalOnboardingJourney, type JourneyArtifactInput } from "./customer-local-onboarding-journey.js";

export interface JourneyCliIo {stdout:{write(value:string):unknown};stderr:{write(value:string):unknown}}
interface Args {command:"start"|"status"|"attach"|"restart"|"rollback"|"events"|"export";state:string;tenant:string;journey?:string;input?:string}
function parse(argv:string[]):Args{const[raw,...rest]=argv;if(!(["start","status","attach","restart","rollback","events","export"] as const).includes(raw as Args["command"]))throw new Error("Usage: onboarding:journey <start|status|attach|restart|rollback|events|export> --state <sqlite> --tenant <id> [--journey <id>] [--input <json>]");const values=new Map<string,string>();for(let i=0;i<rest.length;i+=2){const key=rest[i],value=rest[i+1];if(!key?.startsWith("--")||!value||value.startsWith("--")||values.has(key))throw new Error("Journey CLI options are missing, duplicate or malformed.");values.set(key,value);}for(const key of values.keys())if(!["--state","--tenant","--journey","--input"].includes(key))throw new Error(`Unknown option ${key}.`);const command=raw as Args["command"],state=values.get("--state"),tenant=values.get("--tenant"),journey=values.get("--journey"),input=values.get("--input");if(!state||!tenant)throw new Error("--state and --tenant are required.");if(["start","attach","rollback"].includes(command)!==Boolean(input))throw new Error(`${command} requires the matching input form.`);if(["status","attach","restart","rollback","events","export"].includes(command)!==Boolean(journey))throw new Error(`${command} requires --journey.`);return{command,state:path.resolve(state),tenant,...(journey?{journey}:{}),...(input?{input:path.resolve(input)}:{})};}
function read(file:string){const stats=fs.statSync(file);if(!stats.isFile()||stats.size>10_000_000)throw new Error("Journey CLI input must be a local JSON file below 10 MB.");return JSON.parse(fs.readFileSync(file,"utf8")) as unknown;}
export async function runCustomerLocalOnboardingJourneyCli(argv:string[],io:JourneyCliIo={stdout:process.stdout,stderr:process.stderr}){let journey:DurableCustomerLocalOnboardingJourney|undefined;try{const args=parse(argv);journey=new DurableCustomerLocalOnboardingJourney(args.state);let result:unknown;if(args.command==="start")result=journey.start({...read(args.input!) as {journeyId:string;sourceIdentity:string;recordedAt:string},tenantId:args.tenant});else if(args.command==="status")result=journey.read(args.journey!,args.tenant);else if(args.command==="attach")result=journey.attach(args.journey!,args.tenant,read(args.input!) as JourneyArtifactInput);else if(args.command==="restart")result=journey.observeRestart(args.journey!,args.tenant);else if(args.command==="rollback")result=journey.rollback(args.journey!,args.tenant,read(args.input!) as Parameters<DurableCustomerLocalOnboardingJourney["rollback"]>[2]);else if(args.command==="events")result={events:journey.events(args.journey!,args.tenant)};else result=journey.exportRedacted(args.journey!,args.tenant);io.stdout.write(`${JSON.stringify(result,null,2)}\n`);return 0;}catch(error){io.stderr.write(`${error instanceof Error?error.message:"Journey command failed."}\n`);return 1;}finally{journey?.close();}}
