import{createHash}from"node:crypto";
import{closeSync,fstatSync,openSync,readSync,statSync}from"node:fs";
import{types as utilTypes}from"node:util";

export const CUSTOMER_LOCAL_RESOURCE_LIMITS={
 inputBytes:2_000_000,maxDepth:32,maxNodes:50_000,maxStringBytes:262_144,maxArrayItems:2_048,maxObjectProperties:2_048,
 evidenceLinks:128,failuresPerArtifact:64,failureResolutionsPerArtifact:64,journeyEvents:10_000,
 registryEntriesPerScope:256,registryDependencies:64,registryEventsPerScope:5_000,registryImportBytes:2_000_000,
 providerPrerequisites:14,providerInvalidationsPerTask:512,providerEvents:10_000,
 trustKeys:128,trustEvents:4_096,trustEvidence:10_000,sourceArtifacts:32,
 manifestBytes:1_000_000,databaseFileBytes:536_870_912,backupTotalBytes:1_610_612_736,
 claimsConfigBytes:1_000_000,claimsSealBytes:64_000,claimsSourceArtifacts:256,claimsSourceFileBytes:134_217_728,
}as const;

export interface ResourceBounds{maxBytes:number;maxDepth:number;maxNodes:number;maxStringBytes:number;maxArrayItems:number;maxObjectProperties:number}
const defaults:ResourceBounds={maxBytes:CUSTOMER_LOCAL_RESOURCE_LIMITS.inputBytes,maxDepth:CUSTOMER_LOCAL_RESOURCE_LIMITS.maxDepth,maxNodes:CUSTOMER_LOCAL_RESOURCE_LIMITS.maxNodes,maxStringBytes:CUSTOMER_LOCAL_RESOURCE_LIMITS.maxStringBytes,maxArrayItems:CUSTOMER_LOCAL_RESOURCE_LIMITS.maxArrayItems,maxObjectProperties:CUSTOMER_LOCAL_RESOURCE_LIMITS.maxObjectProperties};
const secret=/(?:bearer|password|secret|token|api[_ -]?key)\s*[:=]\s*[^\s,;}]+|CF_CANARY_[A-Z0-9_-]+/gi;
const malformed=/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/;
const utf8=(value:string)=>Buffer.byteLength(value,"utf8");

export function assertBoundedString(value:unknown,label:string,maxBytes:number=CUSTOMER_LOCAL_RESOURCE_LIMITS.maxStringBytes){if(typeof value!=="string"||malformed.test(value)||utf8(value)>maxBytes)throw new Error(`${label} exceeds its UTF-8 or encoding limit.`);return value;}
export function assertUniqueBoundedStrings(values:unknown,label:string,maxItems:number,maxStringBytes:number=512){if(!Array.isArray(values)||values.length>maxItems)throw new Error(`${label} exceeds its count limit.`);const seen=new Set<string>();for(const value of values){assertBoundedString(value,label,maxStringBytes);if(seen.has(value))throw new Error(`${label} contains a duplicate identity.`);seen.add(value);}return values as string[];}
export function assertBoundedValue(value:unknown,label:string,overrides:Partial<ResourceBounds>={}){
 const limits={...defaults,...overrides},stack:Array<{kind:"value";value:unknown;depth:number}|{kind:"exit";value:object}>=[{kind:"value",value,depth:0}],active=new WeakSet<object>();let nodes=0,bytes=0;
 while(stack.length){const current=stack.pop()!;if(current.kind==="exit"){active.delete(current.value);continue;}if(++nodes>limits.maxNodes)throw new Error(`${label} exceeds its node limit.`);if(current.depth>limits.maxDepth)throw new Error(`${label} exceeds its nesting-depth limit.`);const item=current.value;if(typeof item==="string"){if(malformed.test(item))throw new Error(`${label} contains malformed Unicode.`);const size=utf8(item);if(size>limits.maxStringBytes)throw new Error(`${label} contains an oversized string.`);bytes+=size;}else if(typeof item==="number"){if(!Number.isFinite(item))throw new Error(`${label} contains a non-finite number.`);bytes+=16;}else if(typeof item==="bigint"||typeof item==="function"||typeof item==="symbol"||typeof item==="undefined")throw new Error(`${label} contains a non-JSON value.`);else if(item&&typeof item==="object"){if(utilTypes.isProxy(item))throw new Error(`${label} contains an unsupported proxy object.`);if(active.has(item))throw new Error(`${label} contains a cyclic object.`);active.add(item);stack.push({kind:"exit",value:item});const descriptors=Object.getOwnPropertyDescriptors(item),keys=Reflect.ownKeys(descriptors);if(keys.some(key=>typeof key==="symbol"))throw new Error(`${label} contains a symbol-keyed property.`);if(Array.isArray(item)){if(item.length>limits.maxArrayItems)throw new Error(`${label} exceeds its array-item limit.`);for(const key of keys){if(typeof key!=="string")continue;const descriptor=descriptors[key]!;if(descriptor.get||descriptor.set)throw new Error(`${label} contains an unsupported accessor.`);if(key==="length")continue;const numeric=/^(0|[1-9][0-9]*)$/.test(key)?Number(key):-1;if(!Number.isSafeInteger(numeric)||numeric<0||numeric>=item.length||String(numeric)!==key)throw new Error(`${label} contains a non-index array property.`);bytes+=utf8(key);stack.push({kind:"value",value:descriptor.value,depth:current.depth+1});}}else{if(Object.getPrototypeOf(item)!==Object.prototype&&Object.getPrototypeOf(item)!==null)throw new Error(`${label} contains a non-plain object.`);const entries=Object.entries(descriptors).filter(([key])=>key!=="__proto__");if(entries.length>limits.maxObjectProperties)throw new Error(`${label} exceeds its object-property limit.`);for(let index=entries.length-1;index>=0;index--){const[key,descriptor]=entries[index]!;assertBoundedString(key,label,512);if(descriptor.get||descriptor.set)throw new Error(`${label} contains an unsupported accessor.`);bytes+=utf8(key);stack.push({kind:"value",value:descriptor.value,depth:current.depth+1});}}}else bytes+=4;if(bytes>limits.maxBytes)throw new Error(`${label} exceeds its total UTF-8 byte limit.`);
 }let exact:string;try{exact=JSON.stringify(value);}catch{throw new Error(`${label} cannot be safely serialized.`);}if(Buffer.byteLength(exact,"utf8")>limits.maxBytes)throw new Error(`${label} exceeds its exact serialized UTF-8 byte limit.`);return value;
}
export function assertHistoryCapacity(current:number,limit:number,label:string){if(!Number.isInteger(current)||current<0||current>=limit)throw new Error(`${label} reached its durable history limit; export evidence and start an explicitly linked successor.`);}
export function boundedFileSize(path:string,maxBytes:number,label:string){const size=statSync(path).size;if(size<0||size>maxBytes)throw new Error(`${label} exceeds its file-size limit.`);return size;}
export function readBoundedFile(path:string,maxBytes:number,label:string){boundedFileSize(path,maxBytes,label);const fd=openSync(path,"r");try{const size=fstatSync(fd).size,buffer=Buffer.alloc(size),read=readSync(fd,buffer,0,size,0);if(read!==size)throw new Error(`${label} changed or truncated while being read.`);return buffer;}finally{closeSync(fd);}}
export function readBoundedPrefix(path:string,prefixBytes:number,maxBytes:number,label:string){boundedFileSize(path,maxBytes,label);const fd=openSync(path,"r"),buffer=Buffer.alloc(prefixBytes);try{const read=readSync(fd,buffer,0,prefixBytes,0);if(read!==prefixBytes)throw new Error(`${label} is truncated.`);return buffer;}finally{closeSync(fd);}}
export function sha256BoundedFile(path:string,maxBytes:number,label:string){const size=boundedFileSize(path,maxBytes,label),fd=openSync(path,"r"),hash=createHash("sha256"),buffer=Buffer.allocUnsafe(Math.min(1_048_576,Math.max(1,size)));let offset=0;try{while(offset<size){const count=readSync(fd,buffer,0,Math.min(buffer.length,size-offset),offset);if(count<=0)throw new Error(`${label} changed or truncated while being hashed.`);hash.update(buffer.subarray(0,count));offset+=count;}if(fstatSync(fd).size!==size)throw new Error(`${label} changed while being hashed.`);return hash.digest("hex");}finally{closeSync(fd);}}
export function redactResourceError(value:unknown,fallback="Customer-local operation rejected."){const message=value instanceof Error?value.message:fallback;return message.replace(secret,"[REDACTED]").slice(0,500);}
