import fs from "node:fs";
import path from "node:path";
import { DurableSdkSemanticDraftWorkflow, type SdkSemanticDraftAnswerInput, type SdkSemanticDraftReviewInput, type SdkSemanticDraftSnapshot, type SdkSemanticDraftStartInput } from "./customer-local-sdk-semantic-drafting.js";

export interface SdkSemanticDraftCliIo {stdout:{write(value:string):unknown};stderr:{write(value:string):unknown}}
interface Arguments {command:"start"|"status"|"answer"|"review"|"events";statePath:string;inputPath?:string;sessionId?:string;includeArtifacts:boolean}
function parse(argv:string[]):Arguments{const[raw,...rest]=argv;if(!(["start","status","answer","review","events"] as const).includes(raw as Arguments["command"]))throw new Error("Usage: sdk:semantic:draft <start|status|answer|review|events> --state <local.sqlite> [--input <json>] [--session <id>] [--include-artifacts]");const values=new Map<string,string>();let includeArtifacts=false;for(let i=0;i<rest.length;i++){const token=rest[i];if(token==="--include-artifacts"){if(includeArtifacts)throw new Error("--include-artifacts may be supplied once.");includeArtifacts=true;continue;}if(!token?.startsWith("--")||values.has(token))throw new Error("Semantic drafting CLI contains an unexpected or duplicate option.");const value=rest[++i];if(!value||value.startsWith("--"))throw new Error(`${token} requires a value.`);values.set(token,value);}for(const key of values.keys())if(!["--state","--input","--session"].includes(key))throw new Error(`Unknown option ${key}.`);const command=raw as Arguments["command"],state=values.get("--state"),input=values.get("--input"),session=values.get("--session");if(!state)throw new Error("--state is required.");if(["start","answer","review"].includes(command)!==Boolean(input)||["status","events"].includes(command)!==Boolean(session))throw new Error("Command requires exactly one matching --input or --session argument.");return{command,statePath:path.resolve(state),...(input?{inputPath:path.resolve(input)}:{}),...(session?{sessionId:session}:{}),includeArtifacts};}
function read(file:string){const stats=fs.statSync(file);if(!stats.isFile()||stats.size>10_000_000)throw new Error("Semantic drafting input must be a regular local JSON file under 10 MB.");return JSON.parse(fs.readFileSync(file,"utf8")) as unknown;}
function project(snapshot:SdkSemanticDraftSnapshot,include:boolean){if(include)return snapshot;return{schemaVersion:snapshot.schemaVersion,sessionId:snapshot.sessionId,providerId:snapshot.providerId,state:snapshot.state,revision:snapshot.revision,inputDigest:snapshot.inputDigest,snapshotDigest:snapshot.snapshotDigest,questions:snapshot.questions.map(x=>({questionId:x.questionId,dependsOn:x.dependsOn,prompt:x.prompt,why:x.why,requiredAnswerShape:x.requiredAnswerShape,status:x.status,sourceHintCount:x.sourceHints.length})),blockers:snapshot.blockers,metrics:snapshot.metrics,executionAuthorityEffect:snapshot.executionAuthorityEffect,activationEffect:snapshot.activationEffect,reviewedContractDigest:snapshot.reviewedContract?.contractDigest,artifactHint:"Use --include-artifacts only inside the trusted customer-local environment."};}
export async function runSdkSemanticDraftCli(argv:string[],io:SdkSemanticDraftCliIo={stdout:process.stdout,stderr:process.stderr}){let workflow:DurableSdkSemanticDraftWorkflow|undefined;try{const args=parse(argv);workflow=new DurableSdkSemanticDraftWorkflow(args.statePath);let result:unknown;if(args.command==="start")result=project(workflow.start(read(args.inputPath!) as SdkSemanticDraftStartInput),args.includeArtifacts);else if(args.command==="answer")result=project(workflow.answer(read(args.inputPath!) as SdkSemanticDraftAnswerInput),args.includeArtifacts);else if(args.command==="review")result=project(workflow.review(read(args.inputPath!) as SdkSemanticDraftReviewInput),args.includeArtifacts);else if(args.command==="status")result=project(workflow.read(args.sessionId!),args.includeArtifacts);else result={sessionId:args.sessionId,events:workflow.events(args.sessionId!)};io.stdout.write(`${JSON.stringify(result,null,2)}\n`);return 0;}catch(error){io.stderr.write(`${error instanceof Error?error.message:"SDK semantic drafting command failed."}\n`);return 1;}finally{workflow?.close();}}
