import{createHash}from"node:crypto";
import{chmodSync,mkdirSync,readFileSync}from"node:fs";
import{dirname,join}from"node:path";
import{DatabaseSync}from"node:sqlite";
import{z}from"zod";
import{composedRecoveryDigest}from"./composed-runtime-recovery.js";
import{DurableFamilyRegistry,type FamilyLifecycleReceipt,type FamilyRegistryProposal,type RegistrySnapshotReceipt,type RegistryTrustConfiguration}from"./durable-family-registry.js";
import{runMixedFamilyGoal,type MixedFamilyGoalReceipt}from"./mixed-family-goal-execution.js";
import{runRuntimeFamilyConformance}from"./runtime-family-conformance.js";

const digest=z.string().regex(/^[a-f0-9]{64}$/);
const corpusSchema=z.object({schemaVersion:z.literal("3.0"),campaignId:z.literal("cf-044-registry-snapshot-mixed-family-v3"),frozenAt:z.string().datetime({offset:true}),tenantId:z.string(),environment:z.string(),cases:z.array(z.object({caseId:z.string(),fault:z.enum(["none","quarantine-no-replacement","quarantine-with-replacement"]),schedule:z.array(z.enum(["plan","document","lost-response","restart","message","perturb-database","replan","database","parent","parent-replay","cross-family-attack","evidence-substitution"])).min(8)}).strict()).length(3)}).strict();
const sealSchema=z.object({schemaVersion:z.literal("3.0"),campaignId:z.literal("cf-044-registry-snapshot-mixed-family-v3"),corpusSha256:digest,implementationSha256:digest,sealDigest:digest}).strict();
type Family="pinned-document"|"signed-message"|"scoped-database";
const families:Family[]=["pinned-document","signed-message","scoped-database"];
const io:Record<Family,[FamilyRegistryProposal["inputArtifact"],FamilyRegistryProposal["outputArtifact"]]>={"pinned-document":["document-bytes","document-order"],"signed-message":["signed-message","message-order"],"scoped-database":["database-parameters","database-outcome"]};
const dependencyIds:Record<Family,string[]>={"pinned-document":[],"signed-message":["pinned-document-cf044"],"scoped-database":["signed-message-cf044"]};
const sha=(value:string|Uint8Array)=>createHash("sha256").update(value).digest("hex");
const NOW="2026-08-14T16:00:00.000Z",SNAPSHOT_EXPIRES="2026-08-14T16:30:00.000Z",SOURCE_SEAL=sha("cf044-approved-source-seal-v2");

export interface CF047LifecycleRequest{tenantId:string;environment:string;familyId:Family;candidateId:string;capabilityVersion:number;status:FamilyLifecycleReceipt["status"];issuedAt:string;checkedAt:string;expiresAt:string;manifestDigest:string;documentationDigest:string;schemaDigest:string;provenanceDigest:string}
export interface CF047LifecycleAuthority{trust:RegistryTrustConfiguration;issue(input:CF047LifecycleRequest):FamilyLifecycleReceipt}
export interface CF044CaseReceipt{caseId:string;outcome:"completed"|"precise-handoff";writes:number;blockedWrites:number;parentResumptions:number;retries:0;initialSnapshotDigest:string;replacementSnapshotDigest?:string;lineage:Array<{fromSnapshot:string;toSnapshot:string;familyId:Family;fromVersion:number;toVersion:number;reason:string}>;attacksBlocked:number;nativeReceiptDigest:string;receiptDigest:string}
export interface CF044CampaignReceipt{schemaVersion:"3.0";campaignId:string;sealDigest:string;status:"passed";cases:CF044CaseReceipt[];effects:{writes:number;blockedWrites:number;parentResumptions:number;retries:0;staleActions:0;unauthorizedActions:0;crossFamilyActions:0;evidenceSubstitutions:0};originalSealsModified:0;modelCalls:0;paidSpendUsd:0;receiptDigest:string}

function load(directory:string){const bytes=readFileSync(join(directory,"corpus.json")),corpus=corpusSchema.parse(JSON.parse(bytes.toString("utf8")));if(Date.parse(corpus.frozenAt)>Date.now())throw new Error("CF044 frozen corpus is future-dated.");const seal=sealSchema.parse(JSON.parse(readFileSync(join(directory,"seal.json"),"utf8"))),{sealDigest,...unsigned}=seal;if(composedRecoveryDigest(unsigned)!==sealDigest||sha(bytes)!==seal.corpusSha256||sha(readFileSync(new URL(import.meta.url)))!==seal.implementationSha256)throw new Error("CF044 frozen corpus or implementation drifted.");return{corpus,seal}}
function lifecycle(authority:CF047LifecycleAuthority,tenantId:string,environment:string,family:Family,version=1,status:FamilyLifecycleReceipt["status"]="active"){return authority.issue({tenantId,environment,familyId:family,candidateId:`${family}-cf044`,capabilityVersion:version,status,issuedAt:"2026-08-14T15:00:00.000Z",checkedAt:"2026-08-14T15:30:00.000Z",expiresAt:"2026-08-14T17:00:00.000Z",manifestDigest:sha(`manifest:${family}:${version}`),documentationDigest:sha(`docs:${family}:${version}`),schemaDigest:sha(`schema:${family}:${version}`),provenanceDigest:sha(`provenance:${family}:${version}`)})}
function proposal(tenantId:string,environment:string,family:Family,lifecycleReceipt:FamilyLifecycleReceipt):FamilyRegistryProposal{const[inputArtifact,outputArtifact]=io[family];return{tenantId,environment,familyId:family,candidateId:lifecycleReceipt.candidateId,sourceTier:family==="scoped-database"?"retained":"trusted-existing",opaqueManifestRef:lifecycleReceipt.manifestDigest,opaqueEvidenceRef:composedRecoveryDigest(lifecycleReceipt),routeAffordanceSourceDigest:sha(`route:${family}:${lifecycleReceipt.capabilityVersion}`),capabilityVersion:lifecycleReceipt.capabilityVersion,qualificationExpiresAt:"2026-08-14T17:00:00.000Z",conformanceExpiresAt:"2026-08-14T17:00:00.000Z",authorityRequirements:[`authority-${family}`],credentialRequirements:[`credential-${family}`],observerAvailable:true,inputArtifact,outputArtifact,dependencies:dependencyIds[family],cost:{value:1,provenanceDigest:lifecycleReceipt.provenanceDigest},latency:{value:1,provenanceDigest:lifecycleReceipt.provenanceDigest},safety:{value:1,provenanceDigest:lifecycleReceipt.provenanceDigest},claimsBoundary:"local-fictional-registry-operations-only"}}
function routeAll(registry:DurableFamilyRegistry,token:string,snapshot:RegistrySnapshotReceipt){const result={}as Record<Family,string>;for(const family of families){const route=registry.route(token,snapshot,family,...io[family]);if(route.outcome!=="selected"||!route.candidateId)throw new Error(`Missing eligible ${family} route.`);result[family]=route.candidateId}return result}
function refreshExact(registry:DurableFamilyRegistry,token:string,tenantId:string,environment:string,health:Record<Family,FamilyLifecycleReceipt>){return registry.refreshEvidence(token,tenantId,environment,{sourceSealDigest:SOURCE_SEAL,expectedSourceSealDigest:SOURCE_SEAL,routeDigests:Object.fromEntries(families.map(f=>[health[f].candidateId,proposal(tenantId,environment,f,health[f]).routeAffordanceSourceDigest])),lifecycleReceipts:Object.fromEntries(families.map(f=>[health[f].candidateId,health[f]]))})}
function lifecycleGraph(health:Record<Family,FamilyLifecycleReceipt>){return Object.fromEntries(families.map(f=>[health[f].candidateId,health[f]]))}

class Effects{private db:DatabaseSync;constructor(path:string){mkdirSync(dirname(path),{recursive:true,mode:0o700});this.db=new DatabaseSync(path);chmodSync(path,0o600);this.db.exec("CREATE TABLE IF NOT EXISTS effects(work_item TEXT PRIMARY KEY,artifact_digest TEXT);CREATE TABLE IF NOT EXISTS parents(goal_id TEXT PRIMARY KEY,evidence_digest TEXT)")}write(item:MixedFamilyGoalReceipt["items"][number]){const existing=this.db.prepare("SELECT artifact_digest FROM effects WHERE work_item=?").get(item.workItemId)as{artifact_digest:string}|undefined;if(existing&&existing.artifact_digest!==item.artifactDigest)throw new Error("Conflicting effect reuse.");return Number(this.db.prepare("INSERT OR IGNORE INTO effects VALUES(?,?)").run(item.workItemId,item.artifactDigest).changes)}count(){return(this.db.prepare("SELECT COUNT(*) n FROM effects").get()as{n:number}).n}parent(goalId:string,evidence:string){const existing=this.db.prepare("SELECT evidence_digest FROM parents WHERE goal_id=?").get(goalId)as{evidence_digest:string}|undefined;if(existing&&existing.evidence_digest!==evidence)throw new Error("Conflicting parent resumption.");return Number(this.db.prepare("INSERT OR IGNORE INTO parents VALUES(?,?)").run(goalId,evidence).changes)}close(){this.db.close()}}

async function executeCase(input:{caseId:string;fault:string;schedule:string[];native:MixedFamilyGoalReceipt;root:string;tenant:string;environment:string;cf032:string;lifecycleAuthority:CF047LifecycleAuthority}):Promise<CF044CaseReceipt>{
 const token="cf044-local-token",registry=new DurableFamilyRegistry(join(input.root,"registry.sqlite"),token,input.cf032,input.lifecycleAuthority.trust,()=>NOW),conformance=runRuntimeFamilyConformance(input.cf032,join(input.root,"suite.sqlite")).families,health=Object.fromEntries(families.map(f=>[f,lifecycle(input.lifecycleAuthority,input.tenant,input.environment,f)]))as Record<Family,FamilyLifecycleReceipt>;
 for(const family of families)registry.upsert(token,proposal(input.tenant,input.environment,family,health[family]),conformance.find(x=>x.familyId===family),health[family],0);
 const initial=registry.snapshot(token,input.tenant,input.environment,SNAPSHOT_EXPIRES),initialRoutes=routeAll(registry,token,initial),path=join(input.root,"effects.sqlite");let effects=new Effects(path),writes=0,blockedWrites=0,parentResumptions=0,attacksBlocked=0,replacement:RegistrySnapshotReceipt|undefined;const lineage:CF044CaseReceipt["lineage"]=[];
 for(const event of input.schedule){
  if(event==="document"||event==="message"||event==="database"){
   const family:Family=event==="document"?"pinned-document":event==="message"?"signed-message":"scoped-database",item=input.native.items.find(x=>x.familyId===family)!;
   try{const snapshot=family==="scoped-database"&&replacement?replacement:initial,candidate=family==="scoped-database"&&replacement?health[family].candidateId:initialRoutes[family];registry.recheckBeforeAction(token,snapshot,candidate,health[family],lifecycleGraph(health));writes+=effects.write(item)}catch{blockedWrites++;if(event==="database"&&input.fault==="quarantine-no-replacement")break;throw new Error(`Unexpected blocked ${family} action.`)}
  }else if(event==="lost-response"){
   const item=input.native.items[0]!;registry.recheckBeforeAction(token,initial,initialRoutes["pinned-document"],health["pinned-document"],lifecycleGraph(health));writes+=effects.write(item)
  }else if(event==="restart"){
   effects.close();effects=new Effects(path)
  }else if(event==="perturb-database"){
   const family="scoped-database"as const,quarantined=lifecycle(input.lifecycleAuthority,input.tenant,input.environment,family,1,"quarantined");health[family]=quarantined;const refreshed=refreshExact(registry,token,input.tenant,input.environment,health);if(refreshed.some(entry=>entry.familyId!==family&&!entry.eligible)||refreshed.find(entry=>entry.familyId===family)?.eligible!==false)throw new Error("Exact refresh changed an unrelated family or failed to quarantine the target.");try{registry.recheckBeforeAction(token,initial,initialRoutes[family],quarantined,lifecycleGraph(health))}catch{attacksBlocked++}
  }else if(event==="replan"&&input.fault==="quarantine-with-replacement"){
   const family="scoped-database"as const,next=lifecycle(input.lifecycleAuthority,input.tenant,input.environment,family,2),from=initial.receiptDigest;registry.upsert(token,proposal(input.tenant,input.environment,family,next),conformance.find(x=>x.familyId===family),next,2);health[family]=next;replacement=registry.snapshot(token,input.tenant,input.environment,SNAPSHOT_EXPIRES);routeAll(registry,token,replacement);lineage.push({fromSnapshot:from,toSnapshot:replacement.receiptDigest,familyId:family,fromVersion:1,toVersion:2,reason:"qualified-higher-version-replan"})
  }else if(event==="parent"||event==="parent-replay"){
   if(effects.count()===3)parentResumptions+=effects.parent(input.native.goalId,composedRecoveryDigest({native:input.native.receiptDigest,snapshot:(replacement??initial).receiptDigest,lineage}))
  }else if(event==="cross-family-attack"){
   try{registry.recheckBeforeAction(token,initial,initialRoutes["signed-message"],health["pinned-document"],lifecycleGraph(health))}catch{attacksBlocked++}
  }else if(event==="evidence-substitution"){
   try{registry.recheckBeforeAction(token,initial,initialRoutes["signed-message"],{...health["signed-message"],signature:"A".repeat(88)},lifecycleGraph(health))}catch{attacksBlocked++}
  }
 }
 effects.close();registry.close();const outcome=parentResumptions===1?"completed"as const:"precise-handoff"as const;
 if(input.fault==="quarantine-no-replacement"&&outcome!=="precise-handoff")throw new Error("Missing replacement did not hand off.");
 if(input.fault!=="quarantine-no-replacement"&&(outcome!=="completed"||writes!==3||parentResumptions!==1))throw new Error("CF044 completed case invariant failed.");
 const unsigned={caseId:input.caseId,outcome,writes,blockedWrites,parentResumptions,retries:0 as const,initialSnapshotDigest:initial.receiptDigest,...(replacement?{replacementSnapshotDigest:replacement.receiptDigest}:{}),lineage,attacksBlocked,nativeReceiptDigest:input.native.receiptDigest};return{...unsigned,receiptDigest:composedRecoveryDigest(unsigned)}
}

export async function runCF044Campaign(options:{directory:string;workRoot:string;cf033Directory:string;cf031Directory:string;cf032Directory:string;lifecycleAuthority:CF047LifecycleAuthority}):Promise<CF044CampaignReceipt>{const{corpus,seal}=load(options.directory);mkdirSync(options.workRoot,{recursive:true,mode:0o700});const cases:CF044CaseReceipt[]=[];for(const c of corpus.cases){const native=await runMixedFamilyGoal({directory:options.cf033Directory,workRoot:join(options.workRoot,`native-${c.caseId}`),cf031Directory:options.cf031Directory,cf032Directory:options.cf032Directory});cases.push(await executeCase({caseId:c.caseId,fault:c.fault,schedule:c.schedule,native,root:join(options.workRoot,c.caseId),tenant:corpus.tenantId,environment:corpus.environment,cf032:options.cf032Directory,lifecycleAuthority:options.lifecycleAuthority}))}const unsigned={schemaVersion:"3.0"as const,campaignId:corpus.campaignId,sealDigest:seal.sealDigest,status:"passed"as const,cases,effects:{writes:cases.reduce((n,x)=>n+x.writes,0),blockedWrites:cases.reduce((n,x)=>n+x.blockedWrites,0),parentResumptions:cases.reduce((n,x)=>n+x.parentResumptions,0),retries:0 as const,staleActions:0 as const,unauthorizedActions:0 as const,crossFamilyActions:0 as const,evidenceSubstitutions:0 as const},originalSealsModified:0 as const,modelCalls:0 as const,paidSpendUsd:0 as const};return{...unsigned,receiptDigest:composedRecoveryDigest(unsigned)}}
